# Run pipeline: all fires

Clean, repeatable batch runner. Fire selection/exploration/diagnostics stay in
`data.ipynb`; this notebook just runs `build_cell_table` over a defined list of
fires and saves the pooled result. Re-running is cheap once biomass/dNBR/forest-type
are cached locally (only new fires trigger a real Earth Engine wait).

Known issues that still apply to everything produced here (see README):
- GLAD height unreliable on steep terrain (#8) - exclude `<10m` from conclusions.
- CCI biomass sensitivity varies a lot by fire for unexplained reasons (Section 10).
- Fire Atlas `landcover` label does not reliably predict pixel-level forest type
  (Section 12) - always check `forest_type_label`, never the Atlas label.

In [2]:
import sys
sys.path.append("..")

import ee
ee.Authenticate()   # skip if already authenticated this session
ee.Initialize(project="tree-fire-510209")

import pandas as pd
from src.pipeline import build_cell_table
from src.fires import utm_epsg_for

Enter verification code:  4/1AXlqoi50UgIL_SchwD_xG0dtEmQIxIxl3ujN_6MBMFgojz8p__huIAMUCZI

Successfully saved authorization token.

## Fire configs

One entry per fire run so far (11 total): 4 NAM (Evergreen Needleleaf), 4 SE Asia
(mostly Evergreen Broadleaf), 3 new biomes (southern Africa, Amazon, Australia).
UTM zone is computed from each fire's coordinates rather than hardcoded.

In [3]:
fire_configs = [
    # NAM
    dict(uid="2020_112", lon=-122.782, lat=39.6938,
         pre_fire_window=("2020-07-01", "2020-08-10"), post_fire_window=("2021-07-01", "2021-08-31"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
    dict(uid="2020_135", lon=-121.094, lat=39.8396,
         pre_fire_window=("2020-07-01", "2020-08-15"), post_fire_window=("2021-07-01", "2021-08-31"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
    dict(uid="2020_464", lon=-122.128, lat=37.0396,
         pre_fire_window=("2020-07-01", "2020-08-10"), post_fire_window=("2021-07-01", "2021-08-31"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
    dict(uid="2021_190", lon=-120.556, lat=38.5896,
         pre_fire_window=("2021-06-15", "2021-08-10"), post_fire_window=("2022-06-15", "2022-08-31"),
         agb_before_year=2020, agb_after_years=[2022]),
    # SE Asia
    dict(uid="2020_841874", lon=101.5797, lat=18.8730,
         pre_fire_window=("2020-01-01", "2020-03-15"), post_fire_window=("2021-01-01", "2021-03-15"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
    dict(uid="2020_838262", lon=97.6276, lat=18.9896,
         pre_fire_window=("2019-11-01", "2020-01-20"), post_fire_window=("2020-11-01", "2021-01-20"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
    dict(uid="2020_818141", lon=94.8991, lat=24.6730,
         pre_fire_window=("2020-01-01", "2020-03-15"), post_fire_window=("2021-01-01", "2021-03-15"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
    dict(uid="2021_750951", lon=98.9752, lat=20.9855,
         pre_fire_window=("2021-01-01", "2021-03-10"), post_fire_window=("2022-01-01", "2022-03-10"),
         agb_before_year=2020, agb_after_years=[2022]),
    # new biomes
    dict(uid="2020_325095", lon=19.8160, lat=-7.3770,
         pre_fire_window=("2020-04-15", "2020-06-15"), post_fire_window=("2021-04-15", "2021-06-15"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
    dict(uid="2020_66789", lon=-52.0190, lat=-8.1812,
         pre_fire_window=("2020-06-01", "2020-08-15"), post_fire_window=("2021-06-01", "2021-08-15"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
    dict(uid="2020_901450", lon=153.3236, lat=-25.0645,
         pre_fire_window=("2020-08-01", "2020-10-10"), post_fire_window=("2021-08-01", "2021-10-10"),
         agb_before_year=2019, agb_after_years=[2021, 2022]),
]
print(len(fire_configs), "fires configured")

11 fires configured

## Scaling up: stratified sample, not just the biggest fires

Every fire run so far (the 11 above) was picked as the largest of its forest type
within a region. That's a size-biased sample (README Section 14), not representative
of the ~16,000 candidate fires, most of which are far smaller (median ~10 km2).

This draws a random sample per (GFED region, landcover) stratum instead, subject to
a minimum size so a fire has enough cells to be worth running at all, and excludes
fires already run above. Review the printed count before running - more fires means
a longer, though still parallelised, wait.

In [4]:
import numpy as np

already_run = {cfg["uid"] for cfg in fire_configs}
min_size_km2 = 20       # big enough to likely yield usable cells, small enough to not re-pick giants
n_per_stratum = 5        # tune this - it is the main lever on total runtime
seed = 0

sel_full = pd.read_parquet("../data/processed/forest_fires_2020_2021_attrs.parquet")

# uid (file_year + fire_ID) is not actually always unique - Section 5 already
# found that a repeated fire_ID is usually a genuinely different fire, not a
# duplicate row, and load_fire() has no way to disambiguate which one is meant.
# Drop any ambiguous uid from the candidate pool rather than guess.
dupe_uids = sel_full["uid"][sel_full["uid"].duplicated(keep=False)].unique()
print(len(dupe_uids), "ambiguous uids excluded from sampling")
candidates = sel_full[
    (sel_full["size"] >= min_size_km2)
    & (~sel_full["uid"].isin(already_run))
    & (~sel_full["uid"].isin(dupe_uids))
]

# plain loop, not groupby().apply() - that drops the grouping columns from the
# result on some pandas versions, which then breaks the groupby right after it
parts = []
for _, g in candidates.groupby(["GFED_regio", "landcover"]):
    parts.append(g.sample(n=min(n_per_stratum, len(g)), random_state=seed))
sampled = pd.concat(parts, ignore_index=True)

print(len(sampled), "fires sampled across", sampled.groupby(["GFED_regio", "landcover"]).ngroups, "strata")
print(sampled.groupby("landcover").size())

import importlib, src.fires
importlib.reload(src.fires)
from src.fires import derive_fire_params
new_fire_configs = [derive_fire_params(row) for _, row in sampled.iterrows()]

0 ambiguous uids excluded from sampling
145 fires sampled across 36 strata
landcover
Deciduous Broadleaf forest     37
Deciduous Needleleaf forest     5
Evergreen Broadleaf forest     39
Evergreen Needleleaf forest    31
Mixed forest                   33
dtype: int64

### Targeting underrepresented forest types

In [5]:
# Targeted top-up: Deciduous Broadleaf (plenty of data) + best-effort Deciduous
# Needleleaf (genuinely scarce, lowering the size threshold to recover what's left)
sel_full = pd.read_parquet("../data/processed/forest_fires_2020_2021_attrs.parquet")

already_run = {cfg["uid"] for cfg in fire_configs} | {cfg["uid"] for cfg in new_fire_configs}
dupe_uids = sel_full["uid"][sel_full["uid"].duplicated(keep=False)].unique()

# Deciduous Broadleaf: healthy pool, sample across every region that has it
broadleaf_candidates = sel_full[
    (sel_full["landcover"] == "Deciduous Broadleaf forest")
    & (sel_full["size"] >= 20)
    & (~sel_full["uid"].isin(already_run))
    & (~sel_full["uid"].isin(dupe_uids))
]
n_per_region = 8
parts = []
for _, g in broadleaf_candidates.groupby("GFED_regio"):
    parts.append(g.sample(n=min(n_per_region, len(g)), random_state=1))
broadleaf_sample = pd.concat(parts, ignore_index=True)
print(len(broadleaf_sample), "Deciduous Broadleaf fires selected")
print(broadleaf_sample.groupby("GFED_regio").size())

# Deciduous Needleleaf: genuinely scarce (16 total, 5 at size>=20), lower the
# bar to size>=5 (matches the original candidate-selection threshold from
# early in the project) to recover whatever is left, best effort only
needleleaf_candidates = sel_full[
    (sel_full["landcover"] == "Deciduous Needleleaf forest")
    & (sel_full["size"] >= 5)
    & (~sel_full["uid"].isin(already_run))
    & (~sel_full["uid"].isin(dupe_uids))
]
print(len(needleleaf_candidates), "Deciduous Needleleaf fires available at size>=5")
needleleaf_sample = needleleaf_candidates

decid_sample = pd.concat([broadleaf_sample, needleleaf_sample], ignore_index=True)
print(len(decid_sample), "total new fires queued")

import importlib, src.fires
importlib.reload(src.fires)
from src.fires import derive_fire_params
new_fire_configs.extend(derive_fire_params(row) for _, row in decid_sample.iterrows())
print(len(new_fire_configs), "total new_fire_configs now queued (including earlier stratified sample)")

49 Deciduous Broadleaf fires selected
GFED_regio
3     8
5     8
8     8
9     8
10    8
11    1
12    8
dtype: int64
11 Deciduous Needleleaf fires available at size>=5
60 total new fires queued
205 total new_fire_configs now queued (including earlier stratified sample)

## Submit severity exports and build per-fire cell tables

Everything sampled above (hand-picked fires, the stratified sample, and the
Deciduous top-up) is combined into one `all_fire_configs` here, then submitted
as a single batch so Earth Engine runs every export in parallel. Re-run the
cell below any time a sampling cell above changes `new_fire_configs` - it
always rebuilds from scratch rather than assuming a stale value.

In [6]:
import importlib
import src.fires, src.biomass, src.height, src.grids, src.severity, src.forest_type, src.temperature, src.pipeline
for m in [src.fires, src.biomass, src.height, src.grids, src.severity, src.forest_type, src.temperature, src.pipeline]:
    importlib.reload(m)
from src.pipeline import submit_severity_tasks, wait_and_download_severity, build_cell_table

all_fire_configs = fire_configs + globals().get("new_fire_configs", [])
print(len(all_fire_configs), "fires queued")

216 fires queued

In [7]:
import importlib, src.severity, src.pipeline
importlib.reload(src.severity)
importlib.reload(src.pipeline)
from src.pipeline import submit_severity_tasks, wait_and_download_severity

submitted = submit_severity_tasks(all_fire_configs)

reusing cached severity for 2020_112: ../data/severity/severity_2020_112.tif
reusing cached severity for 2020_135: ../data/severity/severity_2020_135.tif
reusing cached severity for 2020_464: ../data/severity/severity_2020_464.tif
reusing cached severity for 2021_190: ../data/severity/severity_2021_190.tif
reusing cached severity for 2020_841874: ../data/severity/severity_2020_841874.tif
reusing cached severity for 2020_838262: ../data/severity/severity_2020_838262.tif
reusing cached severity for 2020_818141: ../data/severity/severity_2020_818141.tif
reusing cached severity for 2021_750951: ../data/severity/severity_2021_750951.tif
reusing cached severity for 2020_325095: ../data/severity/severity_2020_325095.tif
reusing cached severity for 2020_66789: ../data/severity/severity_2020_66789.tif
reusing cached severity for 2020_901450: ../data/severity/severity_2020_901450.tif
reusing cached severity for 2021_45882: ../data/severity/severity_2021_45882.tif
reusing cached severity for 2021_13058: ../data/severity/severity_2021_13058.tif
reusing cached severity for 2021_12957: ../data/severity/severity_2021_12957.tif
reusing cached severity for 2021_12895: ../data/severity/severity_2021_12895.tif
reusing cached severity for 2021_12806: ../data/severity/severity_2021_12806.tif
reusing cached severity for 2021_26098: ../data/severity/severity_2021_26098.tif
reusing cached severity for 2021_26579: ../data/severity/severity_2021_26579.tif
reusing cached severity for 2021_26587: ../data/severity/severity_2021_26587.tif
reusing cached severity for 2021_26580: ../data/severity/severity_2021_26580.tif
reusing cached severity for 2021_26577: ../data/severity/severity_2021_26577.tif
reusing cached severity for 2021_17228: ../data/severity/severity_2021_17228.tif
reusing cached severity for 2020_61912: ../data/severity/severity_2020_61912.tif
reusing cached severity for 2021_18246: ../data/severity/severity_2021_18246.tif
reusing cached severity for 2021_18206: ../data/severity/severity_2021_18206.tif
reusing cached severity for 2020_6787: ../data/severity/severity_2020_6787.tif
reusing cached severity for 2020_6783: ../data/severity/severity_2020_6783.tif
reusing cached severity for 2021_53: ../data/severity/severity_2021_53.tif
reusing cached severity for 2020_6785: ../data/severity/severity_2020_6785.tif
reusing cached severity for 2020_6781: ../data/severity/severity_2020_6781.tif
reusing cached severity for 2021_16489: ../data/severity/severity_2021_16489.tif
reusing cached severity for 2021_26650: ../data/severity/severity_2021_26650.tif
reusing cached severity for 2021_5641: ../data/severity/severity_2021_5641.tif
reusing cached severity for 2020_4470: ../data/severity/severity_2020_4470.tif
reusing cached severity for 2020_12804: ../data/severity/severity_2020_12804.tif
reusing cached severity for 2020_9413: ../data/severity/severity_2020_9413.tif
reusing cached severity for 2020_4074: ../data/severity/severity_2020_4074.tif
reusing cached severity for 2020_10820: ../data/severity/severity_2020_10820.tif
reusing cached severity for 2020_10559: ../data/severity/severity_2020_10559.tif
reusing cached severity for 2020_8602: ../data/severity/severity_2020_8602.tif
reusing cached severity for 2020_14027: ../data/severity/severity_2020_14027.tif
reusing cached severity for 2020_11452: ../data/severity/severity_2020_11452.tif
reusing cached severity for 2021_2338: ../data/severity/severity_2021_2338.tif
reusing cached severity for 2020_5401: ../data/severity/severity_2020_5401.tif
reusing cached severity for 2020_4157: ../data/severity/severity_2020_4157.tif
reusing cached severity for 2022_25568: ../data/severity/severity_2022_25568.tif
reusing cached severity for 2020_26676: ../data/severity/severity_2020_26676.tif
reusing cached severity for 2020_36740: ../data/severity/severity_2020_36740.tif
reusing cached severity for 2020_73873: ../data/severity/severity_2020_73873.tif
reusing cached severity for 2020_75745: ../data/severity/severity_2020_75745.tif
2020_78182 FAILED to submit: expected exactly one match for uid '2020_78182' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2
reusing cached severity for 2020_75386: ../data/severity/severity_2020_75386.tif
reusing cached severity for 2020_76404: ../data/severity/severity_2020_76404.tif
reusing cached severity for 2021_53264: ../data/severity/severity_2021_53264.tif
reusing cached severity for 2021_47676: ../data/severity/severity_2021_47676.tif
reusing cached severity for 2020_118847: ../data/severity/severity_2020_118847.tif
reusing cached severity for 2020_59053: ../data/severity/severity_2020_59053.tif
reusing cached severity for 2021_36949: ../data/severity/severity_2021_36949.tif
reusing cached severity for 2022_92446: ../data/severity/severity_2022_92446.tif
reusing cached severity for 2021_54221: ../data/severity/severity_2021_54221.tif
reusing cached severity for 2020_167821: ../data/severity/severity_2020_167821.tif
reusing cached severity for 2020_167823: ../data/severity/severity_2020_167823.tif
reusing cached severity for 2020_167819: ../data/severity/severity_2020_167819.tif
reusing cached severity for 2020_167817: ../data/severity/severity_2020_167817.tif
reusing cached severity for 2021_169727: ../data/severity/severity_2021_169727.tif
reusing cached severity for 2021_169679: ../data/severity/severity_2021_169679.tif
reusing cached severity for 2020_408081: ../data/severity/severity_2020_408081.tif
reusing cached severity for 2019_248585: ../data/severity/severity_2019_248585.tif
reusing cached severity for 2020_439111: ../data/severity/severity_2020_439111.tif
reusing cached severity for 2020_444856: ../data/severity/severity_2020_444856.tif
reusing cached severity for 2020_258807: ../data/severity/severity_2020_258807.tif
reusing cached severity for 2021_576827: ../data/severity/severity_2021_576827.tif
reusing cached severity for 2019_277640: ../data/severity/severity_2019_277640.tif
reusing cached severity for 2019_273963: ../data/severity/severity_2019_273963.tif
reusing cached severity for 2020_273534: ../data/severity/severity_2020_273534.tif
reusing cached severity for 2020_453366: ../data/severity/severity_2020_453366.tif
reusing cached severity for 2020_233896: ../data/severity/severity_2020_233896.tif
reusing cached severity for 2020_433804: ../data/severity/severity_2020_433804.tif
reusing cached severity for 2019_420144: ../data/severity/severity_2019_420144.tif
reusing cached severity for 2020_281026: ../data/severity/severity_2020_281026.tif
reusing cached severity for 2020_431722: ../data/severity/severity_2020_431722.tif
reusing cached severity for 2020_435947: ../data/severity/severity_2020_435947.tif
reusing cached severity for 2020_531717: ../data/severity/severity_2020_531717.tif
reusing cached severity for 2021_424594: ../data/severity/severity_2021_424594.tif
reusing cached severity for 2021_644772: ../data/severity/severity_2021_644772.tif
reusing cached severity for 2021_647591: ../data/severity/severity_2021_647591.tif
reusing cached severity for 2020_352273: ../data/severity/severity_2020_352273.tif
reusing cached severity for 2020_668666: ../data/severity/severity_2020_668666.tif
reusing cached severity for 2020_358189: ../data/severity/severity_2020_358189.tif
reusing cached severity for 2020_468868: ../data/severity/severity_2020_468868.tif
reusing cached severity for 2021_418114: ../data/severity/severity_2021_418114.tif
reusing cached severity for 2021_271563: ../data/severity/severity_2021_271563.tif
reusing cached severity for 2020_653693: ../data/severity/severity_2020_653693.tif
reusing cached severity for 2021_293463: ../data/severity/severity_2021_293463.tif
reusing cached severity for 2020_489538: ../data/severity/severity_2020_489538.tif
reusing cached severity for 2021_482050: ../data/severity/severity_2021_482050.tif
reusing cached severity for 2020_519852: ../data/severity/severity_2020_519852.tif
reusing cached severity for 2020_810300: ../data/severity/severity_2020_810300.tif
reusing cached severity for 2021_746132: ../data/severity/severity_2021_746132.tif
reusing cached severity for 2021_731666: ../data/severity/severity_2021_731666.tif
reusing cached severity for 2021_731669: ../data/severity/severity_2021_731669.tif
reusing cached severity for 2021_731883: ../data/severity/severity_2021_731883.tif
reusing cached severity for 2020_780587: ../data/severity/severity_2020_780587.tif
reusing cached severity for 2020_780981: ../data/severity/severity_2020_780981.tif
reusing cached severity for 2020_780980: ../data/severity/severity_2020_780980.tif
reusing cached severity for 2020_786681: ../data/severity/severity_2020_786681.tif
reusing cached severity for 2021_703537: ../data/severity/severity_2021_703537.tif
reusing cached severity for 2021_703863: ../data/severity/severity_2021_703863.tif
reusing cached severity for 2020_781287: ../data/severity/severity_2020_781287.tif
reusing cached severity for 2021_703862: ../data/severity/severity_2021_703862.tif
reusing cached severity for 2021_704076: ../data/severity/severity_2021_704076.tif
reusing cached severity for 2021_673205: ../data/severity/severity_2021_673205.tif
reusing cached severity for 2020_781644: ../data/severity/severity_2020_781644.tif
reusing cached severity for 2020_781083: ../data/severity/severity_2020_781083.tif
reusing cached severity for 2020_781189: ../data/severity/severity_2020_781189.tif
reusing cached severity for 2021_745780: ../data/severity/severity_2021_745780.tif
reusing cached severity for 2021_704158: ../data/severity/severity_2021_704158.tif
reusing cached severity for 2021_732469: ../data/severity/severity_2021_732469.tif
reusing cached severity for 2020_812710: ../data/severity/severity_2020_812710.tif
reusing cached severity for 2020_810900: ../data/severity/severity_2020_810900.tif
reusing cached severity for 2020_812775: ../data/severity/severity_2020_812775.tif
reusing cached severity for 2020_407304: ../data/severity/severity_2020_407304.tif
reusing cached severity for 2021_737791: ../data/severity/severity_2021_737791.tif
reusing cached severity for 2020_816566: ../data/severity/severity_2020_816566.tif
reusing cached severity for 2020_816568: ../data/severity/severity_2020_816568.tif
reusing cached severity for 2020_398266: ../data/severity/severity_2020_398266.tif
reusing cached severity for 2020_816562: ../data/severity/severity_2020_816562.tif
reusing cached severity for 2020_235778: ../data/severity/severity_2020_235778.tif
reusing cached severity for 2020_235787: ../data/severity/severity_2020_235787.tif
reusing cached severity for 2020_821228: ../data/severity/severity_2020_821228.tif
reusing cached severity for 2021_742138: ../data/severity/severity_2021_742138.tif
reusing cached severity for 2021_742139: ../data/severity/severity_2021_742139.tif
reusing cached severity for 2021_729195: ../data/severity/severity_2021_729195.tif
reusing cached severity for 2021_730324: ../data/severity/severity_2021_730324.tif
reusing cached severity for 2020_854951: ../data/severity/severity_2020_854951.tif
reusing cached severity for 2020_855450: ../data/severity/severity_2020_855450.tif
reusing cached severity for 2020_831135: ../data/severity/severity_2020_831135.tif
reusing cached severity for 2020_853020: ../data/severity/severity_2020_853020.tif
reusing cached severity for 2020_857446: ../data/severity/severity_2020_857446.tif
reusing cached severity for 2021_749622: ../data/severity/severity_2021_749622.tif
reusing cached severity for 2020_828439: ../data/severity/severity_2020_828439.tif
reusing cached severity for 2020_828421: ../data/severity/severity_2020_828421.tif
reusing cached severity for 2021_749741: ../data/severity/severity_2021_749741.tif
reusing cached severity for 2021_749758: ../data/severity/severity_2021_749758.tif
reusing cached severity for 2020_876837: ../data/severity/severity_2020_876837.tif
reusing cached severity for 2020_876693: ../data/severity/severity_2020_876693.tif
reusing cached severity for 2020_880547: ../data/severity/severity_2020_880547.tif
reusing cached severity for 2020_880546: ../data/severity/severity_2020_880546.tif
reusing cached severity for 2022_760657: ../data/severity/severity_2022_760657.tif
reusing cached severity for 2020_880551: ../data/severity/severity_2020_880551.tif
reusing cached severity for 2021_806957: ../data/severity/severity_2021_806957.tif
reusing cached severity for 2020_880293: ../data/severity/severity_2020_880293.tif
reusing cached severity for 2020_880315: ../data/severity/severity_2020_880315.tif
reusing cached severity for 2019_873628: ../data/severity/severity_2019_873628.tif
reusing cached severity for 2020_880577: ../data/severity/severity_2020_880577.tif
reusing cached severity for 2019_873630: ../data/severity/severity_2019_873630.tif
reusing cached severity for 2020_4304: ../data/severity/severity_2020_4304.tif
reusing cached severity for 2021_4325: ../data/severity/severity_2021_4325.tif
reusing cached severity for 2020_4149: ../data/severity/severity_2020_4149.tif
reusing cached severity for 2020_4075: ../data/severity/severity_2020_4075.tif
reusing cached severity for 2020_4076: ../data/severity/severity_2020_4076.tif
reusing cached severity for 2020_4836: ../data/severity/severity_2020_4836.tif
reusing cached severity for 2020_4326: ../data/severity/severity_2020_4326.tif
reusing cached severity for 2020_3812: ../data/severity/severity_2020_3812.tif
reusing cached severity for 2020_73408: ../data/severity/severity_2020_73408.tif
reusing cached severity for 2020_73348: ../data/severity/severity_2020_73348.tif
reusing cached severity for 2021_54350: ../data/severity/severity_2021_54350.tif
2020_77862 FAILED to submit: expected exactly one match for uid '2020_77862' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2
reusing cached severity for 2021_57070: ../data/severity/severity_2021_57070.tif
reusing cached severity for 2021_54976: ../data/severity/severity_2021_54976.tif
reusing cached severity for 2020_75746: ../data/severity/severity_2020_75746.tif
reusing cached severity for 2020_57281: ../data/severity/severity_2020_57281.tif
reusing cached severity for 2019_136948: ../data/severity/severity_2019_136948.tif
reusing cached severity for 2019_419994: ../data/severity/severity_2019_419994.tif
reusing cached severity for 2020_259866: ../data/severity/severity_2020_259866.tif
reusing cached severity for 2020_420267: ../data/severity/severity_2020_420267.tif
reusing cached severity for 2019_245076: ../data/severity/severity_2019_245076.tif
reusing cached severity for 2020_281573: ../data/severity/severity_2020_281573.tif
reusing cached severity for 2020_279667: ../data/severity/severity_2020_279667.tif
reusing cached severity for 2020_252376: ../data/severity/severity_2020_252376.tif
reusing cached severity for 2021_643242: ../data/severity/severity_2021_643242.tif
reusing cached severity for 2020_488743: ../data/severity/severity_2020_488743.tif
reusing cached severity for 2021_493671: ../data/severity/severity_2021_493671.tif
reusing cached severity for 2020_560719: ../data/severity/severity_2020_560719.tif
reusing cached severity for 2020_528754: ../data/severity/severity_2020_528754.tif
reusing cached severity for 2020_713150: ../data/severity/severity_2020_713150.tif
reusing cached severity for 2020_720689: ../data/severity/severity_2020_720689.tif
reusing cached severity for 2021_665174: ../data/severity/severity_2021_665174.tif
reusing cached severity for 2020_741958: ../data/severity/severity_2020_741958.tif
reusing cached severity for 2021_745528: ../data/severity/severity_2021_745528.tif
reusing cached severity for 2021_746115: ../data/severity/severity_2021_746115.tif
reusing cached severity for 2021_732473: ../data/severity/severity_2021_732473.tif
reusing cached severity for 2020_810454: ../data/severity/severity_2020_810454.tif
reusing cached severity for 2021_731668: ../data/severity/severity_2021_731668.tif
reusing cached severity for 2020_809898: ../data/severity/severity_2020_809898.tif
reusing cached severity for 2021_731670: ../data/severity/severity_2021_731670.tif
reusing cached severity for 2021_731492: ../data/severity/severity_2021_731492.tif
reusing cached severity for 2021_727715: ../data/severity/severity_2021_727715.tif
reusing cached severity for 2021_760960: ../data/severity/severity_2021_760960.tif
reusing cached severity for 2020_838229: ../data/severity/severity_2020_838229.tif
reusing cached severity for 2021_759784: ../data/severity/severity_2021_759784.tif
reusing cached severity for 2021_775977: ../data/severity/severity_2021_775977.tif
reusing cached severity for 2021_771670: ../data/severity/severity_2021_771670.tif
reusing cached severity for 2020_808510: ../data/severity/severity_2020_808510.tif
reusing cached severity for 2021_755506: ../data/severity/severity_2021_755506.tif
reusing cached severity for 2020_780975: ../data/severity/severity_2020_780975.tif
reusing cached severity for 2020_780497: ../data/severity/severity_2020_780497.tif
reusing cached severity for 2020_780797: ../data/severity/severity_2020_780797.tif
reusing cached severity for 2020_804171: ../data/severity/severity_2020_804171.tif
reusing cached severity for 2020_803393: ../data/severity/severity_2020_803393.tif
reusing cached severity for 2020_808992: ../data/severity/severity_2020_808992.tif
reusing cached severity for 2020_786680: ../data/severity/severity_2020_786680.tif
reusing cached severity for 2020_787440: ../data/severity/severity_2020_787440.tif
reusing cached severity for 2020_740519: ../data/severity/severity_2020_740519.tif
reusing cached severity for 2020_740562: ../data/severity/severity_2020_740562.tif
reusing cached severity for 2021_707663: ../data/severity/severity_2021_707663.tif

In [8]:
submitted = wait_and_download_severity(submitted)

In [9]:
failed = {uid: s["error"] for uid, s in submitted.items() if s.get("error")}
print(len(failed), "failed")
print(failed)

2 failed
{'2020_78182': "expected exactly one match for uid '2020_78182' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2", '2020_77862': "expected exactly one match for uid '2020_77862' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2"}

In [10]:
from src.pipeline import build_cell_table

results = {}
for cfg in all_fire_configs:
    uid = cfg["uid"]
    lon, lat = cfg.pop("lon"), cfg.pop("lat")
    print("running", uid)
    try:
        results[uid] = build_cell_table(
            utm_epsg=utm_epsg_for(lon, lat),
            severity_path=submitted[uid]["severity_path"],
            **cfg,
        )
        print(uid, "done:", len(results[uid]), "cells")
    except Exception as e:
        print(uid, "FAILED:", e)
    cfg["lon"], cfg["lat"] = lon, lat

running 2020_112
reusing cached AGB 2019 for 2020_112: ../data/cci_agb_ee/agb_2020_112_2019.tif
reusing cached AGB 2021 for 2020_112: ../data/cci_agb_ee/agb_2020_112_2021.tif
reusing cached AGB 2022 for 2020_112: ../data/cci_agb_ee/agb_2020_112_2022.tif
reusing cached landcover for 2020_112: ../data/forest_type/landcover_2020_112.tif
2020_112 done: 120632 cells
running 2020_135
reusing cached AGB 2019 for 2020_135: ../data/cci_agb_ee/agb_2020_135_2019.tif
reusing cached AGB 2021 for 2020_135: ../data/cci_agb_ee/agb_2020_135_2021.tif
reusing cached AGB 2022 for 2020_135: ../data/cci_agb_ee/agb_2020_135_2022.tif
reusing cached landcover for 2020_135: ../data/forest_type/landcover_2020_135.tif
2020_135 done: 109019 cells
running 2020_464
reusing cached AGB 2019 for 2020_464: ../data/cci_agb_ee/agb_2020_464_2019.tif
reusing cached AGB 2021 for 2020_464: ../data/cci_agb_ee/agb_2020_464_2021.tif
reusing cached AGB 2022 for 2020_464: ../data/cci_agb_ee/agb_2020_464_2022.tif
reusing cached landcover for 2020_464: ../data/forest_type/landcover_2020_464.tif
2020_464 done: 62 cells
running 2021_190

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_190: ../data/cci_agb_ee/agb_2021_190_2020.tif
reusing cached AGB 2022 for 2021_190: ../data/cci_agb_ee/agb_2021_190_2022.tif
reusing cached landcover for 2021_190: ../data/forest_type/landcover_2021_190.tif
2021_190 done: 50016 cells
running 2020_841874
reusing cached AGB 2019 for 2020_841874: ../data/cci_agb_ee/agb_2020_841874_2019.tif
reusing cached AGB 2021 for 2020_841874: ../data/cci_agb_ee/agb_2020_841874_2021.tif
reusing cached AGB 2022 for 2020_841874: ../data/cci_agb_ee/agb_2020_841874_2022.tif
reusing cached landcover for 2020_841874: ../data/forest_type/landcover_2020_841874.tif
2020_841874 done: 462 cells
running 2020_838262
reusing cached AGB 2019 for 2020_838262: ../data/cci_agb_ee/agb_2020_838262_2019.tif
reusing cached AGB 2021 for 2020_838262: ../data/cci_agb_ee/agb_2020_838262_2021.tif
reusing cached AGB 2022 for 2020_838262: ../data/cci_agb_ee/agb_2020_838262_2022.tif
reusing cached landcover for 2020_838262: ../data/forest_type/landcover_2020_838262.tif
2020_838262 done: 1473 cells
running 2020_818141
reusing cached AGB 2019 for 2020_818141: ../data/cci_agb_ee/agb_2020_818141_2019.tif
reusing cached AGB 2021 for 2020_818141: ../data/cci_agb_ee/agb_2020_818141_2021.tif
reusing cached AGB 2022 for 2020_818141: ../data/cci_agb_ee/agb_2020_818141_2022.tif
reusing cached landcover for 2020_818141: ../data/forest_type/landcover_2020_818141.tif
2020_818141 done: 382 cells
running 2021_750951

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_750951: ../data/cci_agb_ee/agb_2021_750951_2020.tif
reusing cached AGB 2022 for 2021_750951: ../data/cci_agb_ee/agb_2021_750951_2022.tif
reusing cached landcover for 2021_750951: ../data/forest_type/landcover_2021_750951.tif
2021_750951 done: 61 cells
running 2020_325095
reusing cached AGB 2019 for 2020_325095: ../data/cci_agb_ee/agb_2020_325095_2019.tif
reusing cached AGB 2021 for 2020_325095: ../data/cci_agb_ee/agb_2020_325095_2021.tif
reusing cached AGB 2022 for 2020_325095: ../data/cci_agb_ee/agb_2020_325095_2022.tif
reusing cached landcover for 2020_325095: ../data/forest_type/landcover_2020_325095.tif
2020_325095 done: 94 cells
running 2020_66789
reusing cached AGB 2019 for 2020_66789: ../data/cci_agb_ee/agb_2020_66789_2019.tif
reusing cached AGB 2021 for 2020_66789: ../data/cci_agb_ee/agb_2020_66789_2021.tif
reusing cached AGB 2022 for 2020_66789: ../data/cci_agb_ee/agb_2020_66789_2022.tif
reusing cached landcover for 2020_66789: ../data/forest_type/landcover_2020_66789.tif
2020_66789 done: 2250 cells
running 2020_901450
reusing cached AGB 2019 for 2020_901450: ../data/cci_agb_ee/agb_2020_901450_2019.tif
reusing cached AGB 2021 for 2020_901450: ../data/cci_agb_ee/agb_2020_901450_2021.tif
reusing cached AGB 2022 for 2020_901450: ../data/cci_agb_ee/agb_2020_901450_2022.tif
reusing cached landcover for 2020_901450: ../data/forest_type/landcover_2020_901450.tif
2020_901450 done: 16142 cells
running 2021_45882

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_45882: ../data/cci_agb_ee/agb_2021_45882_2020.tif
reusing cached AGB 2022 for 2021_45882: ../data/cci_agb_ee/agb_2021_45882_2022.tif
2021_45882 FAILED: no height mosaic covers (-92.36243928336802, 52.58428013742522) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_13058

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_13058: ../data/cci_agb_ee/agb_2021_13058_2020.tif
reusing cached AGB 2022 for 2021_13058: ../data/cci_agb_ee/agb_2021_13058_2022.tif
reusing cached landcover for 2021_13058: ../data/forest_type/landcover_2021_13058.tif
2021_13058 done: 2536 cells
running 2021_12957

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_12957: ../data/cci_agb_ee/agb_2021_12957_2020.tif
reusing cached AGB 2022 for 2021_12957: ../data/cci_agb_ee/agb_2021_12957_2022.tif
reusing cached landcover for 2021_12957: ../data/forest_type/landcover_2021_12957.tif
2021_12957 done: 13167 cells
running 2021_12895

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_12895: ../data/cci_agb_ee/agb_2021_12895_2020.tif
reusing cached AGB 2022 for 2021_12895: ../data/cci_agb_ee/agb_2021_12895_2022.tif
reusing cached landcover for 2021_12895: ../data/forest_type/landcover_2021_12895.tif
2021_12895 done: 0 cells
running 2021_12806

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_12806: ../data/cci_agb_ee/agb_2021_12806_2020.tif
reusing cached AGB 2022 for 2021_12806: ../data/cci_agb_ee/agb_2021_12806_2022.tif
reusing cached landcover for 2021_12806: ../data/forest_type/landcover_2021_12806.tif
2021_12806 done: 1112 cells
running 2021_26098

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_26098: ../data/cci_agb_ee/agb_2021_26098_2020.tif
reusing cached AGB 2022 for 2021_26098: ../data/cci_agb_ee/agb_2021_26098_2022.tif
2021_26098 FAILED: no height mosaic covers (-102.92090101626252, 53.186258815418135) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_26579

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_26579: ../data/cci_agb_ee/agb_2021_26579_2020.tif
reusing cached AGB 2022 for 2021_26579: ../data/cci_agb_ee/agb_2021_26579_2022.tif
reusing cached landcover for 2021_26579: ../data/forest_type/landcover_2021_26579.tif
2021_26579 done: 10352 cells
running 2021_26587

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_26587: ../data/cci_agb_ee/agb_2021_26587_2020.tif
reusing cached AGB 2022 for 2021_26587: ../data/cci_agb_ee/agb_2021_26587_2022.tif
reusing cached landcover for 2021_26587: ../data/forest_type/landcover_2021_26587.tif
2021_26587 done: 4367 cells
running 2021_26580

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_26580: ../data/cci_agb_ee/agb_2021_26580_2020.tif
reusing cached AGB 2022 for 2021_26580: ../data/cci_agb_ee/agb_2021_26580_2022.tif
reusing cached landcover for 2021_26580: ../data/forest_type/landcover_2021_26580.tif
2021_26580 done: 2846 cells
running 2021_26577

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_26577: ../data/cci_agb_ee/agb_2021_26577_2020.tif
reusing cached AGB 2022 for 2021_26577: ../data/cci_agb_ee/agb_2021_26577_2022.tif
reusing cached landcover for 2021_26577: ../data/forest_type/landcover_2021_26577.tif
2021_26577 done: 700 cells
running 2021_17228

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_17228: ../data/cci_agb_ee/agb_2021_17228_2020.tif
reusing cached AGB 2022 for 2021_17228: ../data/cci_agb_ee/agb_2021_17228_2022.tif
reusing cached landcover for 2021_17228: ../data/forest_type/landcover_2021_17228.tif
2021_17228 done: 51 cells
running 2020_61912
reusing cached AGB 2019 for 2020_61912: ../data/cci_agb_ee/agb_2020_61912_2019.tif
reusing cached AGB 2021 for 2020_61912: ../data/cci_agb_ee/agb_2020_61912_2021.tif
reusing cached AGB 2022 for 2020_61912: ../data/cci_agb_ee/agb_2020_61912_2022.tif
reusing cached landcover for 2020_61912: ../data/forest_type/landcover_2020_61912.tif
2020_61912 done: 63 cells
running 2021_18246

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_18246: ../data/cci_agb_ee/agb_2021_18246_2020.tif
reusing cached AGB 2022 for 2021_18246: ../data/cci_agb_ee/agb_2021_18246_2022.tif
reusing cached landcover for 2021_18246: ../data/forest_type/landcover_2021_18246.tif
2021_18246 done: 37 cells
running 2021_18206

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_18206: ../data/cci_agb_ee/agb_2021_18206_2020.tif
reusing cached AGB 2022 for 2021_18206: ../data/cci_agb_ee/agb_2021_18206_2022.tif
reusing cached landcover for 2021_18206: ../data/forest_type/landcover_2021_18206.tif
2021_18206 done: 1 cells
running 2020_6787
reusing cached AGB 2019 for 2020_6787: ../data/cci_agb_ee/agb_2020_6787_2019.tif
reusing cached AGB 2021 for 2020_6787: ../data/cci_agb_ee/agb_2020_6787_2021.tif
reusing cached AGB 2022 for 2020_6787: ../data/cci_agb_ee/agb_2020_6787_2022.tif
reusing cached landcover for 2020_6787: ../data/forest_type/landcover_2020_6787.tif
2020_6787 done: 641 cells
running 2020_6783
reusing cached AGB 2019 for 2020_6783: ../data/cci_agb_ee/agb_2020_6783_2019.tif
reusing cached AGB 2021 for 2020_6783: ../data/cci_agb_ee/agb_2020_6783_2021.tif
reusing cached AGB 2022 for 2020_6783: ../data/cci_agb_ee/agb_2020_6783_2022.tif
reusing cached landcover for 2020_6783: ../data/forest_type/landcover_2020_6783.tif
2020_6783 done: 578 cells
running 2021_53

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_53: ../data/cci_agb_ee/agb_2021_53_2020.tif
reusing cached AGB 2022 for 2021_53: ../data/cci_agb_ee/agb_2021_53_2022.tif
reusing cached landcover for 2021_53: ../data/forest_type/landcover_2021_53.tif
2021_53 done: 1708 cells
running 2020_6785
reusing cached AGB 2019 for 2020_6785: ../data/cci_agb_ee/agb_2020_6785_2019.tif
reusing cached AGB 2021 for 2020_6785: ../data/cci_agb_ee/agb_2020_6785_2021.tif
reusing cached AGB 2022 for 2020_6785: ../data/cci_agb_ee/agb_2020_6785_2022.tif
reusing cached landcover for 2020_6785: ../data/forest_type/landcover_2020_6785.tif
2020_6785 done: 7052 cells
running 2020_6781
reusing cached AGB 2019 for 2020_6781: ../data/cci_agb_ee/agb_2020_6781_2019.tif
reusing cached AGB 2021 for 2020_6781: ../data/cci_agb_ee/agb_2020_6781_2021.tif
reusing cached AGB 2022 for 2020_6781: ../data/cci_agb_ee/agb_2020_6781_2022.tif
reusing cached landcover for 2020_6781: ../data/forest_type/landcover_2020_6781.tif
2020_6781 done: 28298 cells
running 2021_16489

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_16489: ../data/cci_agb_ee/agb_2021_16489_2020.tif
reusing cached AGB 2022 for 2021_16489: ../data/cci_agb_ee/agb_2021_16489_2022.tif
reusing cached landcover for 2021_16489: ../data/forest_type/landcover_2021_16489.tif
2021_16489 done: 0 cells
running 2021_26650

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_26650: ../data/cci_agb_ee/agb_2021_26650_2020.tif
reusing cached AGB 2022 for 2021_26650: ../data/cci_agb_ee/agb_2021_26650_2022.tif
reusing cached landcover for 2021_26650: ../data/forest_type/landcover_2021_26650.tif
2021_26650 done: 8360 cells
running 2021_5641

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_5641: ../data/cci_agb_ee/agb_2021_5641_2020.tif
reusing cached AGB 2022 for 2021_5641: ../data/cci_agb_ee/agb_2021_5641_2022.tif
reusing cached landcover for 2021_5641: ../data/forest_type/landcover_2021_5641.tif
2021_5641 done: 4 cells
running 2020_4470
reusing cached AGB 2019 for 2020_4470: ../data/cci_agb_ee/agb_2020_4470_2019.tif
reusing cached AGB 2021 for 2020_4470: ../data/cci_agb_ee/agb_2020_4470_2021.tif
reusing cached AGB 2022 for 2020_4470: ../data/cci_agb_ee/agb_2020_4470_2022.tif
reusing cached landcover for 2020_4470: ../data/forest_type/landcover_2020_4470.tif
2020_4470 done: 22 cells
running 2020_12804
reusing cached AGB 2019 for 2020_12804: ../data/cci_agb_ee/agb_2020_12804_2019.tif
reusing cached AGB 2021 for 2020_12804: ../data/cci_agb_ee/agb_2020_12804_2021.tif
reusing cached AGB 2022 for 2020_12804: ../data/cci_agb_ee/agb_2020_12804_2022.tif
reusing cached landcover for 2020_12804: ../data/forest_type/landcover_2020_12804.tif
2020_12804 done: 56 cells
running 2020_9413
reusing cached AGB 2019 for 2020_9413: ../data/cci_agb_ee/agb_2020_9413_2019.tif
reusing cached AGB 2021 for 2020_9413: ../data/cci_agb_ee/agb_2020_9413_2021.tif
reusing cached AGB 2022 for 2020_9413: ../data/cci_agb_ee/agb_2020_9413_2022.tif
reusing cached landcover for 2020_9413: ../data/forest_type/landcover_2020_9413.tif
2020_9413 done: 26 cells
running 2020_4074
reusing cached AGB 2019 for 2020_4074: ../data/cci_agb_ee/agb_2020_4074_2019.tif
reusing cached AGB 2021 for 2020_4074: ../data/cci_agb_ee/agb_2020_4074_2021.tif
reusing cached AGB 2022 for 2020_4074: ../data/cci_agb_ee/agb_2020_4074_2022.tif
reusing cached landcover for 2020_4074: ../data/forest_type/landcover_2020_4074.tif
2020_4074 done: 323 cells
running 2020_10820
reusing cached AGB 2019 for 2020_10820: ../data/cci_agb_ee/agb_2020_10820_2019.tif
reusing cached AGB 2021 for 2020_10820: ../data/cci_agb_ee/agb_2020_10820_2021.tif
reusing cached AGB 2022 for 2020_10820: ../data/cci_agb_ee/agb_2020_10820_2022.tif
reusing cached landcover for 2020_10820: ../data/forest_type/landcover_2020_10820.tif
2020_10820 done: 82 cells
running 2020_10559
reusing cached AGB 2019 for 2020_10559: ../data/cci_agb_ee/agb_2020_10559_2019.tif
reusing cached AGB 2021 for 2020_10559: ../data/cci_agb_ee/agb_2020_10559_2021.tif
reusing cached AGB 2022 for 2020_10559: ../data/cci_agb_ee/agb_2020_10559_2022.tif
reusing cached landcover for 2020_10559: ../data/forest_type/landcover_2020_10559.tif
2020_10559 done: 647 cells
running 2020_8602
reusing cached AGB 2019 for 2020_8602: ../data/cci_agb_ee/agb_2020_8602_2019.tif
reusing cached AGB 2021 for 2020_8602: ../data/cci_agb_ee/agb_2020_8602_2021.tif
reusing cached AGB 2022 for 2020_8602: ../data/cci_agb_ee/agb_2020_8602_2022.tif
reusing cached landcover for 2020_8602: ../data/forest_type/landcover_2020_8602.tif
2020_8602 done: 539 cells
running 2020_14027
reusing cached AGB 2019 for 2020_14027: ../data/cci_agb_ee/agb_2020_14027_2019.tif
reusing cached AGB 2021 for 2020_14027: ../data/cci_agb_ee/agb_2020_14027_2021.tif
reusing cached AGB 2022 for 2020_14027: ../data/cci_agb_ee/agb_2020_14027_2022.tif
reusing cached landcover for 2020_14027: ../data/forest_type/landcover_2020_14027.tif
2020_14027 done: 192 cells
running 2020_11452
reusing cached AGB 2019 for 2020_11452: ../data/cci_agb_ee/agb_2020_11452_2019.tif
reusing cached AGB 2021 for 2020_11452: ../data/cci_agb_ee/agb_2020_11452_2021.tif
reusing cached AGB 2022 for 2020_11452: ../data/cci_agb_ee/agb_2020_11452_2022.tif
reusing cached landcover for 2020_11452: ../data/forest_type/landcover_2020_11452.tif
2020_11452 done: 3 cells
running 2021_2338

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_2338: ../data/cci_agb_ee/agb_2021_2338_2020.tif
reusing cached AGB 2022 for 2021_2338: ../data/cci_agb_ee/agb_2021_2338_2022.tif
reusing cached landcover for 2021_2338: ../data/forest_type/landcover_2021_2338.tif
2021_2338 done: 16 cells
running 2020_5401
reusing cached AGB 2019 for 2020_5401: ../data/cci_agb_ee/agb_2020_5401_2019.tif
reusing cached AGB 2021 for 2020_5401: ../data/cci_agb_ee/agb_2020_5401_2021.tif
reusing cached AGB 2022 for 2020_5401: ../data/cci_agb_ee/agb_2020_5401_2022.tif
reusing cached landcover for 2020_5401: ../data/forest_type/landcover_2020_5401.tif
2020_5401 done: 8 cells
running 2020_4157
reusing cached AGB 2019 for 2020_4157: ../data/cci_agb_ee/agb_2020_4157_2019.tif
reusing cached AGB 2021 for 2020_4157: ../data/cci_agb_ee/agb_2020_4157_2021.tif
reusing cached AGB 2022 for 2020_4157: ../data/cci_agb_ee/agb_2020_4157_2022.tif
reusing cached landcover for 2020_4157: ../data/forest_type/landcover_2020_4157.tif
2020_4157 done: 109 cells
running 2022_25568
reusing cached AGB 2020 for 2022_25568: ../data/cci_agb_ee/agb_2022_25568_2020.tif
reusing cached AGB 2022 for 2022_25568: ../data/cci_agb_ee/agb_2022_25568_2022.tif
reusing cached landcover for 2022_25568: ../data/forest_type/landcover_2022_25568.tif
2022_25568 done: 85 cells
running 2020_26676
reusing cached AGB 2019 for 2020_26676: ../data/cci_agb_ee/agb_2020_26676_2019.tif
reusing cached AGB 2021 for 2020_26676: ../data/cci_agb_ee/agb_2020_26676_2021.tif
reusing cached AGB 2022 for 2020_26676: ../data/cci_agb_ee/agb_2020_26676_2022.tif
reusing cached landcover for 2020_26676: ../data/forest_type/landcover_2020_26676.tif
2020_26676 done: 121 cells
running 2020_36740
reusing cached AGB 2019 for 2020_36740: ../data/cci_agb_ee/agb_2020_36740_2019.tif
reusing cached AGB 2021 for 2020_36740: ../data/cci_agb_ee/agb_2020_36740_2021.tif
reusing cached AGB 2022 for 2020_36740: ../data/cci_agb_ee/agb_2020_36740_2022.tif
reusing cached landcover for 2020_36740: ../data/forest_type/landcover_2020_36740.tif
2020_36740 done: 49 cells
running 2020_73873
reusing cached AGB 2019 for 2020_73873: ../data/cci_agb_ee/agb_2020_73873_2019.tif
reusing cached AGB 2021 for 2020_73873: ../data/cci_agb_ee/agb_2020_73873_2021.tif
reusing cached AGB 2022 for 2020_73873: ../data/cci_agb_ee/agb_2020_73873_2022.tif
reusing cached landcover for 2020_73873: ../data/forest_type/landcover_2020_73873.tif
2020_73873 done: 1652 cells
running 2020_75745
reusing cached AGB 2019 for 2020_75745: ../data/cci_agb_ee/agb_2020_75745_2019.tif
reusing cached AGB 2021 for 2020_75745: ../data/cci_agb_ee/agb_2020_75745_2021.tif
reusing cached AGB 2022 for 2020_75745: ../data/cci_agb_ee/agb_2020_75745_2022.tif
reusing cached landcover for 2020_75745: ../data/forest_type/landcover_2020_75745.tif
2020_75745 done: 357 cells
running 2020_78182
2020_78182 FAILED: expected exactly one match for uid '2020_78182' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2
running 2020_75386
reusing cached AGB 2019 for 2020_75386: ../data/cci_agb_ee/agb_2020_75386_2019.tif
reusing cached AGB 2021 for 2020_75386: ../data/cci_agb_ee/agb_2020_75386_2021.tif
reusing cached AGB 2022 for 2020_75386: ../data/cci_agb_ee/agb_2020_75386_2022.tif
reusing cached landcover for 2020_75386: ../data/forest_type/landcover_2020_75386.tif
2020_75386 done: 189 cells
running 2020_76404
reusing cached AGB 2019 for 2020_76404: ../data/cci_agb_ee/agb_2020_76404_2019.tif
reusing cached AGB 2021 for 2020_76404: ../data/cci_agb_ee/agb_2020_76404_2021.tif
reusing cached AGB 2022 for 2020_76404: ../data/cci_agb_ee/agb_2020_76404_2022.tif
reusing cached landcover for 2020_76404: ../data/forest_type/landcover_2020_76404.tif
2020_76404 done: 613 cells
running 2021_53264

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_53264: ../data/cci_agb_ee/agb_2021_53264_2020.tif
reusing cached AGB 2022 for 2021_53264: ../data/cci_agb_ee/agb_2021_53264_2022.tif
reusing cached landcover for 2021_53264: ../data/forest_type/landcover_2021_53264.tif
2021_53264 done: 258 cells
running 2021_47676

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_47676: ../data/cci_agb_ee/agb_2021_47676_2020.tif
reusing cached AGB 2022 for 2021_47676: ../data/cci_agb_ee/agb_2021_47676_2022.tif
reusing cached landcover for 2021_47676: ../data/forest_type/landcover_2021_47676.tif
2021_47676 done: 28 cells
running 2020_118847
reusing cached AGB 2019 for 2020_118847: ../data/cci_agb_ee/agb_2020_118847_2019.tif
reusing cached AGB 2021 for 2020_118847: ../data/cci_agb_ee/agb_2020_118847_2021.tif
reusing cached AGB 2022 for 2020_118847: ../data/cci_agb_ee/agb_2020_118847_2022.tif
reusing cached landcover for 2020_118847: ../data/forest_type/landcover_2020_118847.tif
2020_118847 done: 1358 cells
running 2020_59053
reusing cached AGB 2019 for 2020_59053: ../data/cci_agb_ee/agb_2020_59053_2019.tif
reusing cached AGB 2021 for 2020_59053: ../data/cci_agb_ee/agb_2020_59053_2021.tif
reusing cached AGB 2022 for 2020_59053: ../data/cci_agb_ee/agb_2020_59053_2022.tif
reusing cached landcover for 2020_59053: ../data/forest_type/landcover_2020_59053.tif
2020_59053 done: 14462 cells
running 2021_36949

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_36949: ../data/cci_agb_ee/agb_2021_36949_2020.tif
reusing cached AGB 2022 for 2021_36949: ../data/cci_agb_ee/agb_2021_36949_2022.tif
reusing cached landcover for 2021_36949: ../data/forest_type/landcover_2021_36949.tif
2021_36949 done: 99 cells
running 2022_92446
reusing cached AGB 2020 for 2022_92446: ../data/cci_agb_ee/agb_2022_92446_2020.tif
reusing cached AGB 2022 for 2022_92446: ../data/cci_agb_ee/agb_2022_92446_2022.tif
reusing cached landcover for 2022_92446: ../data/forest_type/landcover_2022_92446.tif
2022_92446 done: 2364 cells
running 2021_54221

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_54221: ../data/cci_agb_ee/agb_2021_54221_2020.tif
reusing cached AGB 2022 for 2021_54221: ../data/cci_agb_ee/agb_2021_54221_2022.tif
reusing cached landcover for 2021_54221: ../data/forest_type/landcover_2021_54221.tif
2021_54221 done: 188 cells
running 2020_167821
reusing cached AGB 2019 for 2020_167821: ../data/cci_agb_ee/agb_2020_167821_2019.tif
reusing cached AGB 2021 for 2020_167821: ../data/cci_agb_ee/agb_2020_167821_2021.tif
reusing cached AGB 2022 for 2020_167821: ../data/cci_agb_ee/agb_2020_167821_2022.tif
reusing cached landcover for 2020_167821: ../data/forest_type/landcover_2020_167821.tif
2020_167821 done: 963 cells
running 2020_167823
reusing cached AGB 2019 for 2020_167823: ../data/cci_agb_ee/agb_2020_167823_2019.tif
reusing cached AGB 2021 for 2020_167823: ../data/cci_agb_ee/agb_2020_167823_2021.tif
reusing cached AGB 2022 for 2020_167823: ../data/cci_agb_ee/agb_2020_167823_2022.tif
reusing cached landcover for 2020_167823: ../data/forest_type/landcover_2020_167823.tif
2020_167823 done: 4861 cells
running 2020_167819
reusing cached AGB 2019 for 2020_167819: ../data/cci_agb_ee/agb_2020_167819_2019.tif
reusing cached AGB 2021 for 2020_167819: ../data/cci_agb_ee/agb_2020_167819_2021.tif
reusing cached AGB 2022 for 2020_167819: ../data/cci_agb_ee/agb_2020_167819_2022.tif
reusing cached landcover for 2020_167819: ../data/forest_type/landcover_2020_167819.tif
2020_167819 done: 1203 cells
running 2020_167817
reusing cached AGB 2019 for 2020_167817: ../data/cci_agb_ee/agb_2020_167817_2019.tif
reusing cached AGB 2021 for 2020_167817: ../data/cci_agb_ee/agb_2020_167817_2021.tif
reusing cached AGB 2022 for 2020_167817: ../data/cci_agb_ee/agb_2020_167817_2022.tif
reusing cached landcover for 2020_167817: ../data/forest_type/landcover_2020_167817.tif
2020_167817 done: 6510 cells
running 2021_169727

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_169727: ../data/cci_agb_ee/agb_2021_169727_2020.tif
reusing cached AGB 2022 for 2021_169727: ../data/cci_agb_ee/agb_2021_169727_2022.tif
reusing cached landcover for 2021_169727: ../data/forest_type/landcover_2021_169727.tif
2021_169727 done: 1429 cells
running 2021_169679

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_169679: ../data/cci_agb_ee/agb_2021_169679_2020.tif
reusing cached AGB 2022 for 2021_169679: ../data/cci_agb_ee/agb_2021_169679_2022.tif
reusing cached landcover for 2021_169679: ../data/forest_type/landcover_2021_169679.tif
2021_169679 done: 3070 cells
running 2020_408081
reusing cached AGB 2019 for 2020_408081: ../data/cci_agb_ee/agb_2020_408081_2019.tif
reusing cached AGB 2021 for 2020_408081: ../data/cci_agb_ee/agb_2020_408081_2021.tif
reusing cached AGB 2022 for 2020_408081: ../data/cci_agb_ee/agb_2020_408081_2022.tif
reusing cached landcover for 2020_408081: ../data/forest_type/landcover_2020_408081.tif
2020_408081 done: 2898 cells
running 2019_248585
reusing cached AGB 2019 for 2019_248585: ../data/cci_agb_ee/agb_2019_248585_2019.tif
reusing cached AGB 2021 for 2019_248585: ../data/cci_agb_ee/agb_2019_248585_2021.tif
reusing cached AGB 2022 for 2019_248585: ../data/cci_agb_ee/agb_2019_248585_2022.tif
reusing cached landcover for 2019_248585: ../data/forest_type/landcover_2019_248585.tif
2019_248585 done: 31 cells
running 2020_439111
reusing cached AGB 2020 for 2020_439111: ../data/cci_agb_ee/agb_2020_439111_2020.tif
reusing cached AGB 2022 for 2020_439111: ../data/cci_agb_ee/agb_2020_439111_2022.tif
reusing cached landcover for 2020_439111: ../data/forest_type/landcover_2020_439111.tif
2020_439111 done: 0 cells
running 2020_444856
reusing cached AGB 2020 for 2020_444856: ../data/cci_agb_ee/agb_2020_444856_2020.tif
reusing cached AGB 2022 for 2020_444856: ../data/cci_agb_ee/agb_2020_444856_2022.tif
reusing cached landcover for 2020_444856: ../data/forest_type/landcover_2020_444856.tif
2020_444856 done: 13 cells
running 2020_258807
reusing cached AGB 2020 for 2020_258807: ../data/cci_agb_ee/agb_2020_258807_2020.tif
reusing cached AGB 2022 for 2020_258807: ../data/cci_agb_ee/agb_2020_258807_2022.tif
reusing cached landcover for 2020_258807: ../data/forest_type/landcover_2020_258807.tif
2020_258807 done: 15 cells
running 2021_576827

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_576827: ../data/cci_agb_ee/agb_2021_576827_2020.tif
reusing cached AGB 2022 for 2021_576827: ../data/cci_agb_ee/agb_2021_576827_2022.tif
reusing cached landcover for 2021_576827: ../data/forest_type/landcover_2021_576827.tif
2021_576827 done: 0 cells
running 2019_277640
reusing cached AGB 2019 for 2019_277640: ../data/cci_agb_ee/agb_2019_277640_2019.tif
reusing cached AGB 2021 for 2019_277640: ../data/cci_agb_ee/agb_2019_277640_2021.tif
reusing cached AGB 2022 for 2019_277640: ../data/cci_agb_ee/agb_2019_277640_2022.tif
reusing cached landcover for 2019_277640: ../data/forest_type/landcover_2019_277640.tif
2019_277640 done: 7 cells
running 2019_273963
reusing cached AGB 2019 for 2019_273963: ../data/cci_agb_ee/agb_2019_273963_2019.tif
reusing cached AGB 2021 for 2019_273963: ../data/cci_agb_ee/agb_2019_273963_2021.tif
reusing cached AGB 2022 for 2019_273963: ../data/cci_agb_ee/agb_2019_273963_2022.tif
reusing cached landcover for 2019_273963: ../data/forest_type/landcover_2019_273963.tif
2019_273963 done: 0 cells
running 2020_273534
reusing cached AGB 2019 for 2020_273534: ../data/cci_agb_ee/agb_2020_273534_2019.tif
reusing cached AGB 2021 for 2020_273534: ../data/cci_agb_ee/agb_2020_273534_2021.tif
reusing cached AGB 2022 for 2020_273534: ../data/cci_agb_ee/agb_2020_273534_2022.tif
reusing cached landcover for 2020_273534: ../data/forest_type/landcover_2020_273534.tif
2020_273534 done: 6 cells
running 2020_453366
reusing cached AGB 2020 for 2020_453366: ../data/cci_agb_ee/agb_2020_453366_2020.tif
reusing cached AGB 2022 for 2020_453366: ../data/cci_agb_ee/agb_2020_453366_2022.tif
reusing cached landcover for 2020_453366: ../data/forest_type/landcover_2020_453366.tif
2020_453366 done: 93 cells
running 2020_233896
reusing cached AGB 2019 for 2020_233896: ../data/cci_agb_ee/agb_2020_233896_2019.tif
reusing cached AGB 2021 for 2020_233896: ../data/cci_agb_ee/agb_2020_233896_2021.tif
reusing cached AGB 2022 for 2020_233896: ../data/cci_agb_ee/agb_2020_233896_2022.tif
reusing cached landcover for 2020_233896: ../data/forest_type/landcover_2020_233896.tif
2020_233896 done: 56 cells
running 2020_433804
reusing cached AGB 2020 for 2020_433804: ../data/cci_agb_ee/agb_2020_433804_2020.tif
reusing cached AGB 2022 for 2020_433804: ../data/cci_agb_ee/agb_2020_433804_2022.tif
reusing cached landcover for 2020_433804: ../data/forest_type/landcover_2020_433804.tif
2020_433804 done: 0 cells
running 2019_420144
reusing cached AGB 2019 for 2019_420144: ../data/cci_agb_ee/agb_2019_420144_2019.tif
reusing cached AGB 2021 for 2019_420144: ../data/cci_agb_ee/agb_2019_420144_2021.tif
reusing cached AGB 2022 for 2019_420144: ../data/cci_agb_ee/agb_2019_420144_2022.tif
reusing cached landcover for 2019_420144: ../data/forest_type/landcover_2019_420144.tif
2019_420144 done: 0 cells
running 2020_281026
reusing cached AGB 2019 for 2020_281026: ../data/cci_agb_ee/agb_2020_281026_2019.tif
reusing cached AGB 2021 for 2020_281026: ../data/cci_agb_ee/agb_2020_281026_2021.tif
reusing cached AGB 2022 for 2020_281026: ../data/cci_agb_ee/agb_2020_281026_2022.tif
reusing cached landcover for 2020_281026: ../data/forest_type/landcover_2020_281026.tif
2020_281026 done: 32 cells
running 2020_431722
reusing cached AGB 2020 for 2020_431722: ../data/cci_agb_ee/agb_2020_431722_2020.tif
reusing cached AGB 2022 for 2020_431722: ../data/cci_agb_ee/agb_2020_431722_2022.tif
reusing cached landcover for 2020_431722: ../data/forest_type/landcover_2020_431722.tif
2020_431722 done: 0 cells
running 2020_435947
reusing cached AGB 2020 for 2020_435947: ../data/cci_agb_ee/agb_2020_435947_2020.tif
reusing cached AGB 2022 for 2020_435947: ../data/cci_agb_ee/agb_2020_435947_2022.tif
reusing cached landcover for 2020_435947: ../data/forest_type/landcover_2020_435947.tif
2020_435947 done: 0 cells
running 2020_531717
reusing cached AGB 2019 for 2020_531717: ../data/cci_agb_ee/agb_2020_531717_2019.tif
reusing cached AGB 2021 for 2020_531717: ../data/cci_agb_ee/agb_2020_531717_2021.tif
reusing cached AGB 2022 for 2020_531717: ../data/cci_agb_ee/agb_2020_531717_2022.tif
reusing cached landcover for 2020_531717: ../data/forest_type/landcover_2020_531717.tif
2020_531717 done: 3 cells
running 2021_424594

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_424594: ../data/cci_agb_ee/agb_2021_424594_2020.tif
reusing cached AGB 2022 for 2021_424594: ../data/cci_agb_ee/agb_2021_424594_2022.tif
reusing cached landcover for 2021_424594: ../data/forest_type/landcover_2021_424594.tif
2021_424594 done: 4 cells
running 2021_644772

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_644772: ../data/cci_agb_ee/agb_2021_644772_2020.tif
reusing cached AGB 2022 for 2021_644772: ../data/cci_agb_ee/agb_2021_644772_2022.tif
reusing cached landcover for 2021_644772: ../data/forest_type/landcover_2021_644772.tif
2021_644772 done: 62 cells
running 2021_647591

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_647591: ../data/cci_agb_ee/agb_2021_647591_2020.tif
reusing cached AGB 2022 for 2021_647591: ../data/cci_agb_ee/agb_2021_647591_2022.tif
reusing cached landcover for 2021_647591: ../data/forest_type/landcover_2021_647591.tif
2021_647591 done: 22 cells
running 2020_352273
reusing cached AGB 2019 for 2020_352273: ../data/cci_agb_ee/agb_2020_352273_2019.tif
reusing cached AGB 2021 for 2020_352273: ../data/cci_agb_ee/agb_2020_352273_2021.tif
reusing cached AGB 2022 for 2020_352273: ../data/cci_agb_ee/agb_2020_352273_2022.tif
reusing cached landcover for 2020_352273: ../data/forest_type/landcover_2020_352273.tif
2020_352273 done: 0 cells
running 2020_668666
reusing cached AGB 2019 for 2020_668666: ../data/cci_agb_ee/agb_2020_668666_2019.tif
reusing cached AGB 2021 for 2020_668666: ../data/cci_agb_ee/agb_2020_668666_2021.tif
reusing cached AGB 2022 for 2020_668666: ../data/cci_agb_ee/agb_2020_668666_2022.tif
reusing cached landcover for 2020_668666: ../data/forest_type/landcover_2020_668666.tif
2020_668666 done: 361 cells
running 2020_358189
reusing cached AGB 2019 for 2020_358189: ../data/cci_agb_ee/agb_2020_358189_2019.tif
reusing cached AGB 2021 for 2020_358189: ../data/cci_agb_ee/agb_2020_358189_2021.tif
reusing cached AGB 2022 for 2020_358189: ../data/cci_agb_ee/agb_2020_358189_2022.tif
reusing cached landcover for 2020_358189: ../data/forest_type/landcover_2020_358189.tif
2020_358189 done: 0 cells
running 2020_468868
reusing cached AGB 2019 for 2020_468868: ../data/cci_agb_ee/agb_2020_468868_2019.tif
reusing cached AGB 2021 for 2020_468868: ../data/cci_agb_ee/agb_2020_468868_2021.tif
reusing cached AGB 2022 for 2020_468868: ../data/cci_agb_ee/agb_2020_468868_2022.tif
reusing cached landcover for 2020_468868: ../data/forest_type/landcover_2020_468868.tif
2020_468868 done: 21 cells
running 2021_418114

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_418114: ../data/cci_agb_ee/agb_2021_418114_2020.tif
reusing cached AGB 2022 for 2021_418114: ../data/cci_agb_ee/agb_2021_418114_2022.tif
reusing cached landcover for 2021_418114: ../data/forest_type/landcover_2021_418114.tif
2021_418114 done: 10 cells
running 2021_271563

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_271563: ../data/cci_agb_ee/agb_2021_271563_2020.tif
reusing cached AGB 2022 for 2021_271563: ../data/cci_agb_ee/agb_2021_271563_2022.tif
reusing cached landcover for 2021_271563: ../data/forest_type/landcover_2021_271563.tif
2021_271563 done: 2 cells
running 2020_653693
reusing cached AGB 2019 for 2020_653693: ../data/cci_agb_ee/agb_2020_653693_2019.tif
reusing cached AGB 2021 for 2020_653693: ../data/cci_agb_ee/agb_2020_653693_2021.tif
reusing cached AGB 2022 for 2020_653693: ../data/cci_agb_ee/agb_2020_653693_2022.tif
reusing cached landcover for 2020_653693: ../data/forest_type/landcover_2020_653693.tif
2020_653693 done: 0 cells
running 2021_293463

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_293463: ../data/cci_agb_ee/agb_2021_293463_2020.tif
reusing cached AGB 2022 for 2021_293463: ../data/cci_agb_ee/agb_2021_293463_2022.tif
reusing cached landcover for 2021_293463: ../data/forest_type/landcover_2021_293463.tif
2021_293463 done: 0 cells
running 2020_489538
reusing cached AGB 2019 for 2020_489538: ../data/cci_agb_ee/agb_2020_489538_2019.tif
reusing cached AGB 2021 for 2020_489538: ../data/cci_agb_ee/agb_2020_489538_2021.tif
reusing cached AGB 2022 for 2020_489538: ../data/cci_agb_ee/agb_2020_489538_2022.tif
reusing cached landcover for 2020_489538: ../data/forest_type/landcover_2020_489538.tif
2020_489538 done: 0 cells
running 2021_482050

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_482050: ../data/cci_agb_ee/agb_2021_482050_2020.tif
reusing cached AGB 2022 for 2021_482050: ../data/cci_agb_ee/agb_2021_482050_2022.tif
reusing cached landcover for 2021_482050: ../data/forest_type/landcover_2021_482050.tif
2021_482050 done: 215 cells
running 2020_519852
reusing cached AGB 2019 for 2020_519852: ../data/cci_agb_ee/agb_2020_519852_2019.tif
reusing cached AGB 2021 for 2020_519852: ../data/cci_agb_ee/agb_2020_519852_2021.tif
reusing cached AGB 2022 for 2020_519852: ../data/cci_agb_ee/agb_2020_519852_2022.tif
reusing cached landcover for 2020_519852: ../data/forest_type/landcover_2020_519852.tif
2020_519852 done: 14 cells
running 2020_810300
reusing cached AGB 2019 for 2020_810300: ../data/cci_agb_ee/agb_2020_810300_2019.tif
reusing cached AGB 2021 for 2020_810300: ../data/cci_agb_ee/agb_2020_810300_2021.tif
reusing cached AGB 2022 for 2020_810300: ../data/cci_agb_ee/agb_2020_810300_2022.tif
reusing cached landcover for 2020_810300: ../data/forest_type/landcover_2020_810300.tif
2020_810300 done: 51 cells
running 2021_746132

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_746132: ../data/cci_agb_ee/agb_2021_746132_2020.tif
reusing cached AGB 2022 for 2021_746132: ../data/cci_agb_ee/agb_2021_746132_2022.tif
reusing cached landcover for 2021_746132: ../data/forest_type/landcover_2021_746132.tif
2021_746132 done: 0 cells
running 2021_731666

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731666: ../data/cci_agb_ee/agb_2021_731666_2020.tif
reusing cached AGB 2022 for 2021_731666: ../data/cci_agb_ee/agb_2021_731666_2022.tif
reusing cached landcover for 2021_731666: ../data/forest_type/landcover_2021_731666.tif
2021_731666 done: 0 cells
running 2021_731669

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731669: ../data/cci_agb_ee/agb_2021_731669_2020.tif
reusing cached AGB 2022 for 2021_731669: ../data/cci_agb_ee/agb_2021_731669_2022.tif
reusing cached landcover for 2021_731669: ../data/forest_type/landcover_2021_731669.tif
2021_731669 done: 0 cells
running 2021_731883

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731883: ../data/cci_agb_ee/agb_2021_731883_2020.tif
reusing cached AGB 2022 for 2021_731883: ../data/cci_agb_ee/agb_2021_731883_2022.tif
reusing cached landcover for 2021_731883: ../data/forest_type/landcover_2021_731883.tif
2021_731883 done: 0 cells
running 2020_780587
reusing cached AGB 2019 for 2020_780587: ../data/cci_agb_ee/agb_2020_780587_2019.tif
reusing cached AGB 2021 for 2020_780587: ../data/cci_agb_ee/agb_2020_780587_2021.tif
reusing cached AGB 2022 for 2020_780587: ../data/cci_agb_ee/agb_2020_780587_2022.tif
2020_780587 FAILED: no height mosaic covers (133.47877805325197, 63.31199079646372) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_780981
reusing cached AGB 2019 for 2020_780981: ../data/cci_agb_ee/agb_2020_780981_2019.tif
reusing cached AGB 2021 for 2020_780981: ../data/cci_agb_ee/agb_2020_780981_2021.tif
reusing cached AGB 2022 for 2020_780981: ../data/cci_agb_ee/agb_2020_780981_2022.tif
2020_780981 FAILED: no height mosaic covers (104.32337489183202, 59.591631110215005) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_780980
reusing cached AGB 2019 for 2020_780980: ../data/cci_agb_ee/agb_2020_780980_2019.tif
reusing cached AGB 2021 for 2020_780980: ../data/cci_agb_ee/agb_2020_780980_2021.tif
reusing cached AGB 2022 for 2020_780980: ../data/cci_agb_ee/agb_2020_780980_2022.tif
2020_780980 FAILED: no height mosaic covers (104.4048274037901, 59.55337196618652) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_786681
reusing cached AGB 2019 for 2020_786681: ../data/cci_agb_ee/agb_2020_786681_2019.tif
reusing cached AGB 2021 for 2020_786681: ../data/cci_agb_ee/agb_2020_786681_2021.tif
reusing cached AGB 2022 for 2020_786681: ../data/cci_agb_ee/agb_2020_786681_2022.tif
2020_786681 FAILED: no height mosaic covers (133.63009365375262, 63.297874339417625) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_703537

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_703537: ../data/cci_agb_ee/agb_2021_703537_2020.tif
reusing cached AGB 2022 for 2021_703537: ../data/cci_agb_ee/agb_2021_703537_2022.tif
2021_703537 FAILED: no height mosaic covers (107.95942412477558, 59.906099008814124) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_703863

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_703863: ../data/cci_agb_ee/agb_2021_703863_2020.tif
reusing cached AGB 2022 for 2021_703863: ../data/cci_agb_ee/agb_2021_703863_2022.tif
2021_703863 FAILED: no height mosaic covers (109.5213991014624, 58.31657677663986) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_781287
reusing cached AGB 2019 for 2020_781287: ../data/cci_agb_ee/agb_2020_781287_2019.tif
reusing cached AGB 2021 for 2020_781287: ../data/cci_agb_ee/agb_2020_781287_2021.tif
reusing cached AGB 2022 for 2020_781287: ../data/cci_agb_ee/agb_2020_781287_2022.tif
2020_781287 FAILED: no height mosaic covers (101.08278094188832, 57.98995854906995) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_703862

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_703862: ../data/cci_agb_ee/agb_2021_703862_2020.tif
reusing cached AGB 2022 for 2021_703862: ../data/cci_agb_ee/agb_2021_703862_2022.tif
2021_703862 FAILED: no height mosaic covers (109.55866650371247, 58.35782533757724) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_704076

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_704076: ../data/cci_agb_ee/agb_2021_704076_2020.tif
reusing cached AGB 2022 for 2021_704076: ../data/cci_agb_ee/agb_2021_704076_2022.tif
2021_704076 FAILED: no height mosaic covers (105.85474653547023, 56.37456685386934) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_673205

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_673205: ../data/cci_agb_ee/agb_2021_673205_2020.tif
reusing cached AGB 2022 for 2021_673205: ../data/cci_agb_ee/agb_2021_673205_2022.tif
2021_673205 FAILED: no height mosaic covers (91.03277175598178, 59.2505558203059) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_781644
reusing cached AGB 2019 for 2020_781644: ../data/cci_agb_ee/agb_2020_781644_2019.tif
reusing cached AGB 2021 for 2020_781644: ../data/cci_agb_ee/agb_2020_781644_2021.tif
reusing cached AGB 2022 for 2020_781644: ../data/cci_agb_ee/agb_2020_781644_2022.tif
2020_781644 FAILED: no height mosaic covers (107.26037502136357, 56.28011575529446) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_781083
reusing cached AGB 2019 for 2020_781083: ../data/cci_agb_ee/agb_2020_781083_2019.tif
reusing cached AGB 2021 for 2020_781083: ../data/cci_agb_ee/agb_2020_781083_2021.tif
reusing cached AGB 2022 for 2020_781083: ../data/cci_agb_ee/agb_2020_781083_2022.tif
2020_781083 FAILED: no height mosaic covers (100.84980978384436, 59.12392072571066) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_781189
reusing cached AGB 2019 for 2020_781189: ../data/cci_agb_ee/agb_2020_781189_2019.tif
reusing cached AGB 2021 for 2020_781189: ../data/cci_agb_ee/agb_2020_781189_2021.tif
reusing cached AGB 2022 for 2020_781189: ../data/cci_agb_ee/agb_2020_781189_2022.tif
2020_781189 FAILED: no height mosaic covers (101.8000430457856, 58.62506037614865) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_745780

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_745780: ../data/cci_agb_ee/agb_2021_745780_2020.tif
reusing cached AGB 2022 for 2021_745780: ../data/cci_agb_ee/agb_2021_745780_2022.tif
reusing cached landcover for 2021_745780: ../data/forest_type/landcover_2021_745780.tif
2021_745780 done: 2098 cells
running 2021_704158

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_704158: ../data/cci_agb_ee/agb_2021_704158_2020.tif
reusing cached AGB 2022 for 2021_704158: ../data/cci_agb_ee/agb_2021_704158_2022.tif
2021_704158 FAILED: no height mosaic covers (103.37256554958164, 55.88609387615238) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_732469

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_732469: ../data/cci_agb_ee/agb_2021_732469_2020.tif
reusing cached AGB 2022 for 2021_732469: ../data/cci_agb_ee/agb_2021_732469_2022.tif
reusing cached landcover for 2021_732469: ../data/forest_type/landcover_2021_732469.tif
2021_732469 done: 0 cells
running 2020_812710
reusing cached AGB 2019 for 2020_812710: ../data/cci_agb_ee/agb_2020_812710_2019.tif
reusing cached AGB 2021 for 2020_812710: ../data/cci_agb_ee/agb_2020_812710_2021.tif
reusing cached AGB 2022 for 2020_812710: ../data/cci_agb_ee/agb_2020_812710_2022.tif
reusing cached landcover for 2020_812710: ../data/forest_type/landcover_2020_812710.tif
2020_812710 done: 66 cells
running 2020_810900
reusing cached AGB 2019 for 2020_810900: ../data/cci_agb_ee/agb_2020_810900_2019.tif
reusing cached AGB 2021 for 2020_810900: ../data/cci_agb_ee/agb_2020_810900_2021.tif
reusing cached AGB 2022 for 2020_810900: ../data/cci_agb_ee/agb_2020_810900_2022.tif
reusing cached landcover for 2020_810900: ../data/forest_type/landcover_2020_810900.tif
2020_810900 done: 1 cells
running 2020_812775
reusing cached AGB 2019 for 2020_812775: ../data/cci_agb_ee/agb_2020_812775_2019.tif
reusing cached AGB 2021 for 2020_812775: ../data/cci_agb_ee/agb_2020_812775_2021.tif
reusing cached AGB 2022 for 2020_812775: ../data/cci_agb_ee/agb_2020_812775_2022.tif
reusing cached landcover for 2020_812775: ../data/forest_type/landcover_2020_812775.tif
2020_812775 done: 1855 cells
running 2020_407304
reusing cached AGB 2019 for 2020_407304: ../data/cci_agb_ee/agb_2020_407304_2019.tif
reusing cached AGB 2021 for 2020_407304: ../data/cci_agb_ee/agb_2020_407304_2021.tif
reusing cached AGB 2022 for 2020_407304: ../data/cci_agb_ee/agb_2020_407304_2022.tif
reusing cached landcover for 2020_407304: ../data/forest_type/landcover_2020_407304.tif
2020_407304 done: 920 cells
running 2021_737791

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_737791: ../data/cci_agb_ee/agb_2021_737791_2020.tif
reusing cached AGB 2022 for 2021_737791: ../data/cci_agb_ee/agb_2021_737791_2022.tif
reusing cached landcover for 2021_737791: ../data/forest_type/landcover_2021_737791.tif
2021_737791 done: 1268 cells
running 2020_816566
reusing cached AGB 2019 for 2020_816566: ../data/cci_agb_ee/agb_2020_816566_2019.tif
reusing cached AGB 2021 for 2020_816566: ../data/cci_agb_ee/agb_2020_816566_2021.tif
reusing cached AGB 2022 for 2020_816566: ../data/cci_agb_ee/agb_2020_816566_2022.tif
reusing cached landcover for 2020_816566: ../data/forest_type/landcover_2020_816566.tif
2020_816566 done: 2482 cells
running 2020_816568
reusing cached AGB 2019 for 2020_816568: ../data/cci_agb_ee/agb_2020_816568_2019.tif
reusing cached AGB 2021 for 2020_816568: ../data/cci_agb_ee/agb_2020_816568_2021.tif
reusing cached AGB 2022 for 2020_816568: ../data/cci_agb_ee/agb_2020_816568_2022.tif
reusing cached landcover for 2020_816568: ../data/forest_type/landcover_2020_816568.tif
2020_816568 done: 2327 cells
running 2020_398266
reusing cached AGB 2019 for 2020_398266: ../data/cci_agb_ee/agb_2020_398266_2019.tif
reusing cached AGB 2021 for 2020_398266: ../data/cci_agb_ee/agb_2020_398266_2021.tif
reusing cached AGB 2022 for 2020_398266: ../data/cci_agb_ee/agb_2020_398266_2022.tif
reusing cached landcover for 2020_398266: ../data/forest_type/landcover_2020_398266.tif
2020_398266 done: 1002 cells
running 2020_816562
reusing cached AGB 2019 for 2020_816562: ../data/cci_agb_ee/agb_2020_816562_2019.tif
reusing cached AGB 2021 for 2020_816562: ../data/cci_agb_ee/agb_2020_816562_2021.tif
reusing cached AGB 2022 for 2020_816562: ../data/cci_agb_ee/agb_2020_816562_2022.tif
reusing cached landcover for 2020_816562: ../data/forest_type/landcover_2020_816562.tif
2020_816562 done: 1089 cells
running 2020_235778
reusing cached AGB 2019 for 2020_235778: ../data/cci_agb_ee/agb_2020_235778_2019.tif
reusing cached AGB 2021 for 2020_235778: ../data/cci_agb_ee/agb_2020_235778_2021.tif
reusing cached AGB 2022 for 2020_235778: ../data/cci_agb_ee/agb_2020_235778_2022.tif
reusing cached landcover for 2020_235778: ../data/forest_type/landcover_2020_235778.tif
2020_235778 done: 151 cells
running 2020_235787
reusing cached AGB 2019 for 2020_235787: ../data/cci_agb_ee/agb_2020_235787_2019.tif
reusing cached AGB 2021 for 2020_235787: ../data/cci_agb_ee/agb_2020_235787_2021.tif
reusing cached AGB 2022 for 2020_235787: ../data/cci_agb_ee/agb_2020_235787_2022.tif
reusing cached landcover for 2020_235787: ../data/forest_type/landcover_2020_235787.tif
2020_235787 done: 270 cells
running 2020_821228
reusing cached AGB 2019 for 2020_821228: ../data/cci_agb_ee/agb_2020_821228_2019.tif
reusing cached AGB 2021 for 2020_821228: ../data/cci_agb_ee/agb_2020_821228_2021.tif
reusing cached AGB 2022 for 2020_821228: ../data/cci_agb_ee/agb_2020_821228_2022.tif
reusing cached landcover for 2020_821228: ../data/forest_type/landcover_2020_821228.tif
2020_821228 done: 3235 cells
running 2021_742138

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_742138: ../data/cci_agb_ee/agb_2021_742138_2020.tif
reusing cached AGB 2022 for 2021_742138: ../data/cci_agb_ee/agb_2021_742138_2022.tif
reusing cached landcover for 2021_742138: ../data/forest_type/landcover_2021_742138.tif
2021_742138 done: 19 cells
running 2021_742139

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_742139: ../data/cci_agb_ee/agb_2021_742139_2020.tif
reusing cached AGB 2022 for 2021_742139: ../data/cci_agb_ee/agb_2021_742139_2022.tif
reusing cached landcover for 2021_742139: ../data/forest_type/landcover_2021_742139.tif
2021_742139 done: 0 cells
running 2021_729195

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_729195: ../data/cci_agb_ee/agb_2021_729195_2020.tif
reusing cached AGB 2022 for 2021_729195: ../data/cci_agb_ee/agb_2021_729195_2022.tif
reusing cached landcover for 2021_729195: ../data/forest_type/landcover_2021_729195.tif
2021_729195 done: 18 cells
running 2021_730324

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_730324: ../data/cci_agb_ee/agb_2021_730324_2020.tif
reusing cached AGB 2022 for 2021_730324: ../data/cci_agb_ee/agb_2021_730324_2022.tif
reusing cached landcover for 2021_730324: ../data/forest_type/landcover_2021_730324.tif
2021_730324 done: 18 cells
running 2020_854951
reusing cached AGB 2019 for 2020_854951: ../data/cci_agb_ee/agb_2020_854951_2019.tif
reusing cached AGB 2021 for 2020_854951: ../data/cci_agb_ee/agb_2020_854951_2021.tif
reusing cached AGB 2022 for 2020_854951: ../data/cci_agb_ee/agb_2020_854951_2022.tif
reusing cached landcover for 2020_854951: ../data/forest_type/landcover_2020_854951.tif
2020_854951 done: 14 cells
running 2020_855450
reusing cached AGB 2019 for 2020_855450: ../data/cci_agb_ee/agb_2020_855450_2019.tif
reusing cached AGB 2021 for 2020_855450: ../data/cci_agb_ee/agb_2020_855450_2021.tif
reusing cached AGB 2022 for 2020_855450: ../data/cci_agb_ee/agb_2020_855450_2022.tif
reusing cached landcover for 2020_855450: ../data/forest_type/landcover_2020_855450.tif
2020_855450 done: 6 cells
running 2020_831135
reusing cached AGB 2019 for 2020_831135: ../data/cci_agb_ee/agb_2020_831135_2019.tif
reusing cached AGB 2021 for 2020_831135: ../data/cci_agb_ee/agb_2020_831135_2021.tif
reusing cached AGB 2022 for 2020_831135: ../data/cci_agb_ee/agb_2020_831135_2022.tif
reusing cached landcover for 2020_831135: ../data/forest_type/landcover_2020_831135.tif
2020_831135 done: 190 cells
running 2020_853020
reusing cached AGB 2019 for 2020_853020: ../data/cci_agb_ee/agb_2020_853020_2019.tif
reusing cached AGB 2021 for 2020_853020: ../data/cci_agb_ee/agb_2020_853020_2021.tif
reusing cached AGB 2022 for 2020_853020: ../data/cci_agb_ee/agb_2020_853020_2022.tif
reusing cached landcover for 2020_853020: ../data/forest_type/landcover_2020_853020.tif
2020_853020 done: 42 cells
running 2020_857446
reusing cached AGB 2019 for 2020_857446: ../data/cci_agb_ee/agb_2020_857446_2019.tif
reusing cached AGB 2021 for 2020_857446: ../data/cci_agb_ee/agb_2020_857446_2021.tif
reusing cached AGB 2022 for 2020_857446: ../data/cci_agb_ee/agb_2020_857446_2022.tif
reusing cached landcover for 2020_857446: ../data/forest_type/landcover_2020_857446.tif
2020_857446 done: 1353 cells
running 2021_749622

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_749622: ../data/cci_agb_ee/agb_2021_749622_2020.tif
reusing cached AGB 2022 for 2021_749622: ../data/cci_agb_ee/agb_2021_749622_2022.tif
reusing cached landcover for 2021_749622: ../data/forest_type/landcover_2021_749622.tif
2021_749622 done: 8 cells
running 2020_828439
reusing cached AGB 2019 for 2020_828439: ../data/cci_agb_ee/agb_2020_828439_2019.tif
reusing cached AGB 2021 for 2020_828439: ../data/cci_agb_ee/agb_2020_828439_2021.tif
reusing cached AGB 2022 for 2020_828439: ../data/cci_agb_ee/agb_2020_828439_2022.tif
reusing cached landcover for 2020_828439: ../data/forest_type/landcover_2020_828439.tif
2020_828439 done: 460 cells
running 2020_828421
reusing cached AGB 2019 for 2020_828421: ../data/cci_agb_ee/agb_2020_828421_2019.tif
reusing cached AGB 2021 for 2020_828421: ../data/cci_agb_ee/agb_2020_828421_2021.tif
reusing cached AGB 2022 for 2020_828421: ../data/cci_agb_ee/agb_2020_828421_2022.tif
reusing cached landcover for 2020_828421: ../data/forest_type/landcover_2020_828421.tif
2020_828421 done: 126 cells
running 2021_749741

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_749741: ../data/cci_agb_ee/agb_2021_749741_2020.tif
reusing cached AGB 2022 for 2021_749741: ../data/cci_agb_ee/agb_2021_749741_2022.tif
reusing cached landcover for 2021_749741: ../data/forest_type/landcover_2021_749741.tif
2021_749741 done: 467 cells
running 2021_749758

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_749758: ../data/cci_agb_ee/agb_2021_749758_2020.tif
reusing cached AGB 2022 for 2021_749758: ../data/cci_agb_ee/agb_2021_749758_2022.tif
reusing cached landcover for 2021_749758: ../data/forest_type/landcover_2021_749758.tif
2021_749758 done: 143 cells
running 2020_876837
reusing cached AGB 2019 for 2020_876837: ../data/cci_agb_ee/agb_2020_876837_2019.tif
reusing cached AGB 2021 for 2020_876837: ../data/cci_agb_ee/agb_2020_876837_2021.tif
reusing cached AGB 2022 for 2020_876837: ../data/cci_agb_ee/agb_2020_876837_2022.tif
reusing cached landcover for 2020_876837: ../data/forest_type/landcover_2020_876837.tif
2020_876837 done: 277 cells
running 2020_876693
reusing cached AGB 2019 for 2020_876693: ../data/cci_agb_ee/agb_2020_876693_2019.tif
reusing cached AGB 2021 for 2020_876693: ../data/cci_agb_ee/agb_2020_876693_2021.tif
reusing cached AGB 2022 for 2020_876693: ../data/cci_agb_ee/agb_2020_876693_2022.tif
reusing cached landcover for 2020_876693: ../data/forest_type/landcover_2020_876693.tif
2020_876693 done: 284 cells
running 2020_880547
reusing cached AGB 2019 for 2020_880547: ../data/cci_agb_ee/agb_2020_880547_2019.tif
reusing cached AGB 2021 for 2020_880547: ../data/cci_agb_ee/agb_2020_880547_2021.tif
reusing cached AGB 2022 for 2020_880547: ../data/cci_agb_ee/agb_2020_880547_2022.tif
reusing cached landcover for 2020_880547: ../data/forest_type/landcover_2020_880547.tif
2020_880547 done: 15286 cells
running 2020_880546
reusing cached AGB 2019 for 2020_880546: ../data/cci_agb_ee/agb_2020_880546_2019.tif
reusing cached AGB 2021 for 2020_880546: ../data/cci_agb_ee/agb_2020_880546_2021.tif
reusing cached AGB 2022 for 2020_880546: ../data/cci_agb_ee/agb_2020_880546_2022.tif
reusing cached landcover for 2020_880546: ../data/forest_type/landcover_2020_880546.tif
2020_880546 done: 1541 cells
running 2022_760657
reusing cached AGB 2020 for 2022_760657: ../data/cci_agb_ee/agb_2022_760657_2020.tif
reusing cached AGB 2022 for 2022_760657: ../data/cci_agb_ee/agb_2022_760657_2022.tif
reusing cached landcover for 2022_760657: ../data/forest_type/landcover_2022_760657.tif
2022_760657 done: 203 cells
running 2020_880551
reusing cached AGB 2019 for 2020_880551: ../data/cci_agb_ee/agb_2020_880551_2019.tif
reusing cached AGB 2021 for 2020_880551: ../data/cci_agb_ee/agb_2020_880551_2021.tif
reusing cached AGB 2022 for 2020_880551: ../data/cci_agb_ee/agb_2020_880551_2022.tif
reusing cached landcover for 2020_880551: ../data/forest_type/landcover_2020_880551.tif
2020_880551 done: 1376 cells
running 2021_806957

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_806957: ../data/cci_agb_ee/agb_2021_806957_2020.tif
reusing cached AGB 2022 for 2021_806957: ../data/cci_agb_ee/agb_2021_806957_2022.tif
reusing cached landcover for 2021_806957: ../data/forest_type/landcover_2021_806957.tif
2021_806957 done: 764 cells
running 2020_880293
reusing cached AGB 2019 for 2020_880293: ../data/cci_agb_ee/agb_2020_880293_2019.tif
reusing cached AGB 2021 for 2020_880293: ../data/cci_agb_ee/agb_2020_880293_2021.tif
reusing cached AGB 2022 for 2020_880293: ../data/cci_agb_ee/agb_2020_880293_2022.tif
reusing cached landcover for 2020_880293: ../data/forest_type/landcover_2020_880293.tif
2020_880293 done: 3256 cells
running 2020_880315
reusing cached AGB 2019 for 2020_880315: ../data/cci_agb_ee/agb_2020_880315_2019.tif
reusing cached AGB 2021 for 2020_880315: ../data/cci_agb_ee/agb_2020_880315_2021.tif
reusing cached AGB 2022 for 2020_880315: ../data/cci_agb_ee/agb_2020_880315_2022.tif
reusing cached landcover for 2020_880315: ../data/forest_type/landcover_2020_880315.tif
2020_880315 done: 2808 cells
running 2019_873628
reusing cached AGB 2019 for 2019_873628: ../data/cci_agb_ee/agb_2019_873628_2019.tif
reusing cached AGB 2021 for 2019_873628: ../data/cci_agb_ee/agb_2019_873628_2021.tif
reusing cached AGB 2022 for 2019_873628: ../data/cci_agb_ee/agb_2019_873628_2022.tif
reusing cached landcover for 2019_873628: ../data/forest_type/landcover_2019_873628.tif
2019_873628 done: 4899 cells
running 2020_880577
reusing cached AGB 2019 for 2020_880577: ../data/cci_agb_ee/agb_2020_880577_2019.tif
reusing cached AGB 2021 for 2020_880577: ../data/cci_agb_ee/agb_2020_880577_2021.tif
reusing cached AGB 2022 for 2020_880577: ../data/cci_agb_ee/agb_2020_880577_2022.tif
reusing cached landcover for 2020_880577: ../data/forest_type/landcover_2020_880577.tif
2020_880577 done: 7425 cells
running 2019_873630
reusing cached AGB 2019 for 2019_873630: ../data/cci_agb_ee/agb_2019_873630_2019.tif
reusing cached AGB 2021 for 2019_873630: ../data/cci_agb_ee/agb_2019_873630_2021.tif
reusing cached AGB 2022 for 2019_873630: ../data/cci_agb_ee/agb_2019_873630_2022.tif
reusing cached landcover for 2019_873630: ../data/forest_type/landcover_2019_873630.tif
2019_873630 done: 3943 cells
running 2020_4304
reusing cached AGB 2019 for 2020_4304: ../data/cci_agb_ee/agb_2020_4304_2019.tif
reusing cached AGB 2021 for 2020_4304: ../data/cci_agb_ee/agb_2020_4304_2021.tif
reusing cached AGB 2022 for 2020_4304: ../data/cci_agb_ee/agb_2020_4304_2022.tif
reusing cached landcover for 2020_4304: ../data/forest_type/landcover_2020_4304.tif
2020_4304 done: 0 cells
running 2021_4325

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_4325: ../data/cci_agb_ee/agb_2021_4325_2020.tif
reusing cached AGB 2022 for 2021_4325: ../data/cci_agb_ee/agb_2021_4325_2022.tif
reusing cached landcover for 2021_4325: ../data/forest_type/landcover_2021_4325.tif
2021_4325 done: 30 cells
running 2020_4149
reusing cached AGB 2019 for 2020_4149: ../data/cci_agb_ee/agb_2020_4149_2019.tif
reusing cached AGB 2021 for 2020_4149: ../data/cci_agb_ee/agb_2020_4149_2021.tif
reusing cached AGB 2022 for 2020_4149: ../data/cci_agb_ee/agb_2020_4149_2022.tif
reusing cached landcover for 2020_4149: ../data/forest_type/landcover_2020_4149.tif
2020_4149 done: 20 cells
running 2020_4075
reusing cached AGB 2019 for 2020_4075: ../data/cci_agb_ee/agb_2020_4075_2019.tif
reusing cached AGB 2021 for 2020_4075: ../data/cci_agb_ee/agb_2020_4075_2021.tif
reusing cached AGB 2022 for 2020_4075: ../data/cci_agb_ee/agb_2020_4075_2022.tif
reusing cached landcover for 2020_4075: ../data/forest_type/landcover_2020_4075.tif
2020_4075 done: 291 cells
running 2020_4076
reusing cached AGB 2019 for 2020_4076: ../data/cci_agb_ee/agb_2020_4076_2019.tif
reusing cached AGB 2021 for 2020_4076: ../data/cci_agb_ee/agb_2020_4076_2021.tif
reusing cached AGB 2022 for 2020_4076: ../data/cci_agb_ee/agb_2020_4076_2022.tif
reusing cached landcover for 2020_4076: ../data/forest_type/landcover_2020_4076.tif
2020_4076 done: 1720 cells
running 2020_4836
reusing cached AGB 2019 for 2020_4836: ../data/cci_agb_ee/agb_2020_4836_2019.tif
reusing cached AGB 2021 for 2020_4836: ../data/cci_agb_ee/agb_2020_4836_2021.tif
reusing cached AGB 2022 for 2020_4836: ../data/cci_agb_ee/agb_2020_4836_2022.tif
reusing cached landcover for 2020_4836: ../data/forest_type/landcover_2020_4836.tif
2020_4836 done: 322 cells
running 2020_4326
reusing cached AGB 2019 for 2020_4326: ../data/cci_agb_ee/agb_2020_4326_2019.tif
reusing cached AGB 2021 for 2020_4326: ../data/cci_agb_ee/agb_2020_4326_2021.tif
reusing cached AGB 2022 for 2020_4326: ../data/cci_agb_ee/agb_2020_4326_2022.tif
reusing cached landcover for 2020_4326: ../data/forest_type/landcover_2020_4326.tif
2020_4326 done: 8 cells
running 2020_3812
reusing cached AGB 2019 for 2020_3812: ../data/cci_agb_ee/agb_2020_3812_2019.tif
reusing cached AGB 2021 for 2020_3812: ../data/cci_agb_ee/agb_2020_3812_2021.tif
reusing cached AGB 2022 for 2020_3812: ../data/cci_agb_ee/agb_2020_3812_2022.tif
reusing cached landcover for 2020_3812: ../data/forest_type/landcover_2020_3812.tif
2020_3812 done: 50 cells
running 2020_73408
reusing cached AGB 2019 for 2020_73408: ../data/cci_agb_ee/agb_2020_73408_2019.tif
reusing cached AGB 2021 for 2020_73408: ../data/cci_agb_ee/agb_2020_73408_2021.tif
reusing cached AGB 2022 for 2020_73408: ../data/cci_agb_ee/agb_2020_73408_2022.tif
reusing cached landcover for 2020_73408: ../data/forest_type/landcover_2020_73408.tif
2020_73408 done: 631 cells
running 2020_73348
reusing cached AGB 2019 for 2020_73348: ../data/cci_agb_ee/agb_2020_73348_2019.tif
reusing cached AGB 2021 for 2020_73348: ../data/cci_agb_ee/agb_2020_73348_2021.tif
reusing cached AGB 2022 for 2020_73348: ../data/cci_agb_ee/agb_2020_73348_2022.tif
reusing cached landcover for 2020_73348: ../data/forest_type/landcover_2020_73348.tif
2020_73348 done: 134 cells
running 2021_54350

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_54350: ../data/cci_agb_ee/agb_2021_54350_2020.tif
reusing cached AGB 2022 for 2021_54350: ../data/cci_agb_ee/agb_2021_54350_2022.tif
reusing cached landcover for 2021_54350: ../data/forest_type/landcover_2021_54350.tif
2021_54350 done: 1032 cells
running 2020_77862
2020_77862 FAILED: expected exactly one match for uid '2020_77862' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2
running 2021_57070

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_57070: ../data/cci_agb_ee/agb_2021_57070_2020.tif
reusing cached AGB 2022 for 2021_57070: ../data/cci_agb_ee/agb_2021_57070_2022.tif
reusing cached landcover for 2021_57070: ../data/forest_type/landcover_2021_57070.tif
2021_57070 done: 350 cells
running 2021_54976

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_54976: ../data/cci_agb_ee/agb_2021_54976_2020.tif
reusing cached AGB 2022 for 2021_54976: ../data/cci_agb_ee/agb_2021_54976_2022.tif
reusing cached landcover for 2021_54976: ../data/forest_type/landcover_2021_54976.tif
2021_54976 done: 0 cells
running 2020_75746
reusing cached AGB 2019 for 2020_75746: ../data/cci_agb_ee/agb_2020_75746_2019.tif
reusing cached AGB 2021 for 2020_75746: ../data/cci_agb_ee/agb_2020_75746_2021.tif
reusing cached AGB 2022 for 2020_75746: ../data/cci_agb_ee/agb_2020_75746_2022.tif
reusing cached landcover for 2020_75746: ../data/forest_type/landcover_2020_75746.tif
2020_75746 done: 5826 cells
running 2020_57281
reusing cached AGB 2019 for 2020_57281: ../data/cci_agb_ee/agb_2020_57281_2019.tif
reusing cached AGB 2021 for 2020_57281: ../data/cci_agb_ee/agb_2020_57281_2021.tif
reusing cached AGB 2022 for 2020_57281: ../data/cci_agb_ee/agb_2020_57281_2022.tif
reusing cached landcover for 2020_57281: ../data/forest_type/landcover_2020_57281.tif
2020_57281 done: 831 cells
running 2019_136948
reusing cached AGB 2019 for 2019_136948: ../data/cci_agb_ee/agb_2019_136948_2019.tif
reusing cached AGB 2021 for 2019_136948: ../data/cci_agb_ee/agb_2019_136948_2021.tif
reusing cached AGB 2022 for 2019_136948: ../data/cci_agb_ee/agb_2019_136948_2022.tif
reusing cached landcover for 2019_136948: ../data/forest_type/landcover_2019_136948.tif
2019_136948 done: 228 cells
running 2019_419994
reusing cached AGB 2019 for 2019_419994: ../data/cci_agb_ee/agb_2019_419994_2019.tif
reusing cached AGB 2021 for 2019_419994: ../data/cci_agb_ee/agb_2019_419994_2021.tif
reusing cached AGB 2022 for 2019_419994: ../data/cci_agb_ee/agb_2019_419994_2022.tif
reusing cached landcover for 2019_419994: ../data/forest_type/landcover_2019_419994.tif
2019_419994 done: 4 cells
running 2020_259866
reusing cached AGB 2020 for 2020_259866: ../data/cci_agb_ee/agb_2020_259866_2020.tif
reusing cached AGB 2022 for 2020_259866: ../data/cci_agb_ee/agb_2020_259866_2022.tif
reusing cached landcover for 2020_259866: ../data/forest_type/landcover_2020_259866.tif
2020_259866 done: 63 cells
running 2020_420267
reusing cached AGB 2019 for 2020_420267: ../data/cci_agb_ee/agb_2020_420267_2019.tif
reusing cached AGB 2021 for 2020_420267: ../data/cci_agb_ee/agb_2020_420267_2021.tif
reusing cached AGB 2022 for 2020_420267: ../data/cci_agb_ee/agb_2020_420267_2022.tif
reusing cached landcover for 2020_420267: ../data/forest_type/landcover_2020_420267.tif
2020_420267 done: 0 cells
running 2019_245076
reusing cached AGB 2019 for 2019_245076: ../data/cci_agb_ee/agb_2019_245076_2019.tif
reusing cached AGB 2021 for 2019_245076: ../data/cci_agb_ee/agb_2019_245076_2021.tif
reusing cached AGB 2022 for 2019_245076: ../data/cci_agb_ee/agb_2019_245076_2022.tif
reusing cached landcover for 2019_245076: ../data/forest_type/landcover_2019_245076.tif
2019_245076 done: 0 cells
running 2020_281573
reusing cached AGB 2019 for 2020_281573: ../data/cci_agb_ee/agb_2020_281573_2019.tif
reusing cached AGB 2021 for 2020_281573: ../data/cci_agb_ee/agb_2020_281573_2021.tif
reusing cached AGB 2022 for 2020_281573: ../data/cci_agb_ee/agb_2020_281573_2022.tif
reusing cached landcover for 2020_281573: ../data/forest_type/landcover_2020_281573.tif
2020_281573 done: 25 cells
running 2020_279667
reusing cached AGB 2019 for 2020_279667: ../data/cci_agb_ee/agb_2020_279667_2019.tif
reusing cached AGB 2021 for 2020_279667: ../data/cci_agb_ee/agb_2020_279667_2021.tif
reusing cached AGB 2022 for 2020_279667: ../data/cci_agb_ee/agb_2020_279667_2022.tif
reusing cached landcover for 2020_279667: ../data/forest_type/landcover_2020_279667.tif
2020_279667 done: 257 cells
running 2020_252376
reusing cached AGB 2020 for 2020_252376: ../data/cci_agb_ee/agb_2020_252376_2020.tif
reusing cached AGB 2022 for 2020_252376: ../data/cci_agb_ee/agb_2020_252376_2022.tif

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_643242: ../data/cci_agb_ee/agb_2021_643242_2020.tif
reusing cached AGB 2022 for 2021_643242: ../data/cci_agb_ee/agb_2021_643242_2022.tif
reusing cached landcover for 2021_746115: ../data/forest_type/landcover_2021_746115.tif
2021_746115 done: 116 cells
running 2021_732473

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_732473: ../data/cci_agb_ee/agb_2021_732473_2020.tif
reusing cached AGB 2022 for 2021_732473: ../data/cci_agb_ee/agb_2021_732473_2022.tif
reusing cached landcover for 2021_732473: ../data/forest_type/landcover_2021_732473.tif
2021_732473 done: 0 cells
running 2020_810454
reusing cached AGB 2019 for 2020_810454: ../data/cci_agb_ee/agb_2020_810454_2019.tif
reusing cached AGB 2021 for 2020_810454: ../data/cci_agb_ee/agb_2020_810454_2021.tif
reusing cached AGB 2022 for 2020_810454: ../data/cci_agb_ee/agb_2020_810454_2022.tif
reusing cached landcover for 2020_810454: ../data/forest_type/landcover_2020_810454.tif
2020_810454 done: 0 cells
running 2021_731668

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731668: ../data/cci_agb_ee/agb_2021_731668_2020.tif
reusing cached AGB 2022 for 2021_731668: ../data/cci_agb_ee/agb_2021_731668_2022.tif
reusing cached landcover for 2021_731668: ../data/forest_type/landcover_2021_731668.tif
2021_731668 done: 0 cells
running 2020_809898
reusing cached AGB 2019 for 2020_809898: ../data/cci_agb_ee/agb_2020_809898_2019.tif
reusing cached AGB 2021 for 2020_809898: ../data/cci_agb_ee/agb_2020_809898_2021.tif
reusing cached AGB 2022 for 2020_809898: ../data/cci_agb_ee/agb_2020_809898_2022.tif
reusing cached landcover for 2020_809898: ../data/forest_type/landcover_2020_809898.tif
2020_809898 done: 556 cells
running 2021_731670

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731670: ../data/cci_agb_ee/agb_2021_731670_2020.tif
reusing cached AGB 2022 for 2021_731670: ../data/cci_agb_ee/agb_2021_731670_2022.tif
reusing cached landcover for 2021_731670: ../data/forest_type/landcover_2021_731670.tif
2021_731670 done: 0 cells
running 2021_731492

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731492: ../data/cci_agb_ee/agb_2021_731492_2020.tif
reusing cached AGB 2022 for 2021_731492: ../data/cci_agb_ee/agb_2021_731492_2022.tif
reusing cached landcover for 2021_731492: ../data/forest_type/landcover_2021_731492.tif
2021_731492 done: 3604 cells
running 2021_727715

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_727715: ../data/cci_agb_ee/agb_2021_727715_2020.tif
reusing cached AGB 2022 for 2021_727715: ../data/cci_agb_ee/agb_2021_727715_2022.tif
reusing cached landcover for 2021_727715: ../data/forest_type/landcover_2021_727715.tif
2021_727715 done: 43 cells
running 2021_760960

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_760960: ../data/cci_agb_ee/agb_2021_760960_2020.tif
reusing cached AGB 2022 for 2021_760960: ../data/cci_agb_ee/agb_2021_760960_2022.tif
reusing cached landcover for 2021_760960: ../data/forest_type/landcover_2021_760960.tif
2021_760960 done: 11 cells
running 2020_838229
reusing cached AGB 2019 for 2020_838229: ../data/cci_agb_ee/agb_2020_838229_2019.tif
reusing cached AGB 2021 for 2020_838229: ../data/cci_agb_ee/agb_2020_838229_2021.tif
reusing cached AGB 2022 for 2020_838229: ../data/cci_agb_ee/agb_2020_838229_2022.tif
reusing cached landcover for 2020_838229: ../data/forest_type/landcover_2020_838229.tif
2020_838229 done: 375 cells
running 2021_759784

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_759784: ../data/cci_agb_ee/agb_2021_759784_2020.tif
reusing cached AGB 2022 for 2021_759784: ../data/cci_agb_ee/agb_2021_759784_2022.tif
reusing cached landcover for 2021_759784: ../data/forest_type/landcover_2021_759784.tif
2021_759784 done: 0 cells
running 2021_775977

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_775977: ../data/cci_agb_ee/agb_2021_775977_2020.tif
reusing cached AGB 2022 for 2021_775977: ../data/cci_agb_ee/agb_2021_775977_2022.tif
reusing cached landcover for 2021_775977: ../data/forest_type/landcover_2021_775977.tif
2021_775977 done: 32 cells
running 2021_771670

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_771670: ../data/cci_agb_ee/agb_2021_771670_2020.tif
reusing cached AGB 2022 for 2021_771670: ../data/cci_agb_ee/agb_2021_771670_2022.tif
reusing cached landcover for 2021_771670: ../data/forest_type/landcover_2021_771670.tif
2021_771670 done: 252 cells
running 2020_808510
reusing cached AGB 2019 for 2020_808510: ../data/cci_agb_ee/agb_2020_808510_2019.tif
reusing cached AGB 2021 for 2020_808510: ../data/cci_agb_ee/agb_2020_808510_2021.tif
reusing cached AGB 2022 for 2020_808510: ../data/cci_agb_ee/agb_2020_808510_2022.tif
reusing cached landcover for 2020_808510: ../data/forest_type/landcover_2020_808510.tif
2020_808510 done: 38 cells
running 2021_755506

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_755506: ../data/cci_agb_ee/agb_2021_755506_2020.tif
reusing cached AGB 2022 for 2021_755506: ../data/cci_agb_ee/agb_2021_755506_2022.tif
reusing cached landcover for 2021_755506: ../data/forest_type/landcover_2021_755506.tif
2021_755506 done: 0 cells
running 2020_780975
reusing cached AGB 2019 for 2020_780975: ../data/cci_agb_ee/agb_2020_780975_2019.tif
reusing cached AGB 2021 for 2020_780975: ../data/cci_agb_ee/agb_2020_780975_2021.tif
reusing cached AGB 2022 for 2020_780975: ../data/cci_agb_ee/agb_2020_780975_2022.tif
2020_780975 FAILED: no height mosaic covers (108.7229342644759, 59.62837418006809) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_780497
reusing cached AGB 2019 for 2020_780497: ../data/cci_agb_ee/agb_2020_780497_2019.tif
reusing cached AGB 2021 for 2020_780497: ../data/cci_agb_ee/agb_2020_780497_2021.tif
reusing cached AGB 2022 for 2020_780497: ../data/cci_agb_ee/agb_2020_780497_2022.tif
2020_780497 FAILED: no height mosaic covers (131.32007578347847, 63.4559516318431) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_780797
reusing cached AGB 2019 for 2020_780797: ../data/cci_agb_ee/agb_2020_780797_2019.tif
reusing cached AGB 2021 for 2020_780797: ../data/cci_agb_ee/agb_2020_780797_2021.tif
reusing cached AGB 2022 for 2020_780797: ../data/cci_agb_ee/agb_2020_780797_2022.tif
2020_780797 FAILED: no height mosaic covers (125.72241280115598, 61.51882198057349) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_804171
reusing cached AGB 2019 for 2020_804171: ../data/cci_agb_ee/agb_2020_804171_2019.tif
reusing cached AGB 2021 for 2020_804171: ../data/cci_agb_ee/agb_2020_804171_2021.tif
reusing cached AGB 2022 for 2020_804171: ../data/cci_agb_ee/agb_2020_804171_2022.tif
2020_804171 FAILED: no height mosaic covers (130.27890356599175, 53.582369959829244) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_803393
reusing cached AGB 2019 for 2020_803393: ../data/cci_agb_ee/agb_2020_803393_2019.tif
reusing cached AGB 2021 for 2020_803393: ../data/cci_agb_ee/agb_2020_803393_2021.tif
reusing cached AGB 2022 for 2020_803393: ../data/cci_agb_ee/agb_2020_803393_2022.tif
2020_803393 FAILED: no height mosaic covers (153.36239161646438, 62.42307169565812) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_808992
reusing cached AGB 2019 for 2020_808992: ../data/cci_agb_ee/agb_2020_808992_2019.tif
reusing cached AGB 2021 for 2020_808992: ../data/cci_agb_ee/agb_2020_808992_2021.tif
reusing cached AGB 2022 for 2020_808992: ../data/cci_agb_ee/agb_2020_808992_2022.tif
2020_808992 FAILED: no height mosaic covers (132.06904069015894, 52.60956026928432) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_786680
reusing cached AGB 2019 for 2020_786680: ../data/cci_agb_ee/agb_2020_786680_2019.tif
reusing cached AGB 2021 for 2020_786680: ../data/cci_agb_ee/agb_2020_786680_2021.tif
reusing cached AGB 2022 for 2020_786680: ../data/cci_agb_ee/agb_2020_786680_2022.tif
2020_786680 FAILED: no height mosaic covers (133.64397335110493, 63.273095247113744) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_787440
reusing cached AGB 2019 for 2020_787440: ../data/cci_agb_ee/agb_2020_787440_2019.tif
reusing cached AGB 2021 for 2020_787440: ../data/cci_agb_ee/agb_2020_787440_2021.tif
reusing cached AGB 2022 for 2020_787440: ../data/cci_agb_ee/agb_2020_787440_2022.tif
2020_787440 FAILED: no height mosaic covers (134.92343796817232, 61.66068990525767) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_740519
reusing cached AGB 2019 for 2020_740519: ../data/cci_agb_ee/agb_2020_740519_2019.tif
reusing cached AGB 2021 for 2020_740519: ../data/cci_agb_ee/agb_2020_740519_2021.tif
reusing cached AGB 2022 for 2020_740519: ../data/cci_agb_ee/agb_2020_740519_2022.tif
2020_740519 FAILED: no height mosaic covers (99.79222230179725, 60.52059010387322) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2020_740562
reusing cached AGB 2019 for 2020_740562: ../data/cci_agb_ee/agb_2020_740562_2019.tif
reusing cached AGB 2021 for 2020_740562: ../data/cci_agb_ee/agb_2020_740562_2021.tif
reusing cached AGB 2022 for 2020_740562: ../data/cci_agb_ee/agb_2020_740562_2022.tif
2020_740562 FAILED: no height mosaic covers (99.65252709020098, 60.124480518771584) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry
running 2021_707663

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_707663: ../data/cci_agb_ee/agb_2021_707663_2020.tif
reusing cached AGB 2022 for 2021_707663: ../data/cci_agb_ee/agb_2021_707663_2022.tif
2021_707663 FAILED: no height mosaic covers (133.9561098482611, 62.725745479928136) - likely beyond GLAD's real coverage (~52S-52N, see README known issue #4, boreal limitation), not a missing config entry

In [11]:
print(len(results))
print(list(results[next(iter(results))].columns))

186
['uid', 'height', 'dnbr', 'rbr', 'forest_type', 'forest_type_label', 'a2019', 'a2021', 'a2022', 'severity', 'loss2021', 'loss2022']

### Rerun with severity reprojection

In [12]:
import rasterio
import numpy as np
import glob
import pandas as pd

results_check = []
for path in sorted(glob.glob("../data/severity/severity_*.tif")):
    uid = path.split("severity_")[1].replace(".tif", "")
    with rasterio.open(path) as src:
        arr = src.read(1)  # dNBR band, raw, no masking
        nan_frac = np.isnan(arr).mean()
        results_check.append((uid, nan_frac))

results_check.sort(key=lambda x: -x[1])
print("Top 20 fires by severity NaN fraction:")
for uid, frac in results_check[:20]:
    print(f"  {uid}: {frac:.1%}")

fracs = pd.Series([f for _, f in results_check])
print("\noverall distribution:")
print(fracs.describe())
print("fires with >5% NaN:", (fracs > 0.05).sum(), "of", len(fracs))
print("fires with >1% NaN:", (fracs > 0.01).sum(), "of", len(fracs))

Top 20 fires by severity NaN fraction:
  2017_17487: 85.2%
  2021_12895: 71.6%
  2021_731670: 63.0%
  2021_731668: 59.2%
  2020_810454: 58.4%
  2020_810300: 51.5%
  2021_731669: 50.1%
  2016_35438: 47.7%
  2020_464: 38.3%
  2021_771670: 22.9%
  2021_731666: 21.7%
  2020_14027: 21.1%
  2020_876693: 13.6%
  2021_731492: 3.2%
  2021_731883: 3.2%
  2021_732473: 2.5%
  2022_25568: 2.0%
  2020_281573: 1.5%
  2020_876837: 1.3%
  2020_233896: 1.0%

overall distribution:
count    223.000000
mean       0.028214
std        0.120133
min        0.000000
25%        0.000000
50%        0.000405
75%        0.000852
max        0.851664
dtype: float64
fires with >5% NaN: 13 of 223
fires with >1% NaN: 19 of 223

In [13]:
import importlib, src.grids, src.pipeline
importlib.reload(src.grids)
importlib.reload(src.pipeline)
from src.pipeline import build_cell_table

affected_uids = [uid for uid, frac in results_check if frac > 0.01]
print(len(affected_uids), "fires with >1% severity NaN (candidates for re-run)")

cfg_by_uid = {cfg["uid"]: cfg for cfg in all_fire_configs}

19 fires with >1% severity NaN (candidates for re-run)

In [14]:
main_uids = {cfg["uid"] for cfg in all_fire_configs}
affected_uids_main = [uid for uid in affected_uids if uid in main_uids]
not_in_main = [uid for uid in affected_uids if uid not in main_uids]

print(len(affected_uids_main), "affected fires actually in the main pipeline")
print("skipped (not part of main results, e.g. the 2016-2018 side test):", not_in_main)

17 affected fires actually in the main pipeline
skipped (not part of main results, e.g. the 2016-2018 side test): ['2017_17487', '2016_35438']

In [15]:
for uid in affected_uids_main:
    cfg = cfg_by_uid[uid]
    lon, lat = cfg.pop("lon"), cfg.pop("lat")
    print("re-running", uid)
    try:
        results[uid] = build_cell_table(
            utm_epsg=utm_epsg_for(lon, lat),
            severity_path=f"../data/severity/severity_{uid}.tif",
            landcover_path=f"../data/forest_type/landcover_{uid}.tif",
            **cfg,
        )
        print(uid, "done:", len(results[uid]), "cells")
    except Exception as e:
        print(uid, "FAILED:", e)
    cfg["lon"], cfg["lat"] = lon, lat

re-running 2021_12895

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_12895: ../data/cci_agb_ee/agb_2021_12895_2020.tif
reusing cached AGB 2022 for 2021_12895: ../data/cci_agb_ee/agb_2021_12895_2022.tif
2021_12895 done: 0 cells
re-running 2021_731670

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731670: ../data/cci_agb_ee/agb_2021_731670_2020.tif
reusing cached AGB 2022 for 2021_731670: ../data/cci_agb_ee/agb_2021_731670_2022.tif
2021_731670 done: 0 cells
re-running 2021_731668

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731668: ../data/cci_agb_ee/agb_2021_731668_2020.tif
reusing cached AGB 2022 for 2021_731668: ../data/cci_agb_ee/agb_2021_731668_2022.tif
2021_731668 done: 0 cells
re-running 2020_810454
reusing cached AGB 2019 for 2020_810454: ../data/cci_agb_ee/agb_2020_810454_2019.tif
reusing cached AGB 2021 for 2020_810454: ../data/cci_agb_ee/agb_2020_810454_2021.tif
reusing cached AGB 2022 for 2020_810454: ../data/cci_agb_ee/agb_2020_810454_2022.tif
2020_810454 done: 0 cells
re-running 2020_810300
reusing cached AGB 2019 for 2020_810300: ../data/cci_agb_ee/agb_2020_810300_2019.tif
reusing cached AGB 2021 for 2020_810300: ../data/cci_agb_ee/agb_2020_810300_2021.tif
reusing cached AGB 2022 for 2020_810300: ../data/cci_agb_ee/agb_2020_810300_2022.tif
2020_810300 done: 51 cells
re-running 2021_731669

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731669: ../data/cci_agb_ee/agb_2021_731669_2020.tif
reusing cached AGB 2022 for 2021_731669: ../data/cci_agb_ee/agb_2021_731669_2022.tif
2021_731669 done: 0 cells
re-running 2020_464
reusing cached AGB 2019 for 2020_464: ../data/cci_agb_ee/agb_2020_464_2019.tif
reusing cached AGB 2021 for 2020_464: ../data/cci_agb_ee/agb_2020_464_2021.tif
reusing cached AGB 2022 for 2020_464: ../data/cci_agb_ee/agb_2020_464_2022.tif
2020_464 done: 62 cells
re-running 2021_771670

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_771670: ../data/cci_agb_ee/agb_2021_771670_2020.tif
reusing cached AGB 2022 for 2021_771670: ../data/cci_agb_ee/agb_2021_771670_2022.tif
2021_771670 done: 252 cells
re-running 2021_731666

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731666: ../data/cci_agb_ee/agb_2021_731666_2020.tif
reusing cached AGB 2022 for 2021_731666: ../data/cci_agb_ee/agb_2021_731666_2022.tif
2021_731666 done: 0 cells
re-running 2020_14027
reusing cached AGB 2019 for 2020_14027: ../data/cci_agb_ee/agb_2020_14027_2019.tif
reusing cached AGB 2021 for 2020_14027: ../data/cci_agb_ee/agb_2020_14027_2021.tif
reusing cached AGB 2022 for 2020_14027: ../data/cci_agb_ee/agb_2020_14027_2022.tif
2020_14027 done: 192 cells
re-running 2020_876693
reusing cached AGB 2019 for 2020_876693: ../data/cci_agb_ee/agb_2020_876693_2019.tif
reusing cached AGB 2021 for 2020_876693: ../data/cci_agb_ee/agb_2020_876693_2021.tif
reusing cached AGB 2022 for 2020_876693: ../data/cci_agb_ee/agb_2020_876693_2022.tif
2020_876693 done: 284 cells
re-running 2021_731492

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731492: ../data/cci_agb_ee/agb_2021_731492_2020.tif
reusing cached AGB 2022 for 2021_731492: ../data/cci_agb_ee/agb_2021_731492_2022.tif
2021_731492 done: 3604 cells
re-running 2021_731883

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_731883: ../data/cci_agb_ee/agb_2021_731883_2020.tif
reusing cached AGB 2022 for 2021_731883: ../data/cci_agb_ee/agb_2021_731883_2022.tif
2021_731883 done: 0 cells
re-running 2021_732473

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

reusing cached AGB 2020 for 2021_732473: ../data/cci_agb_ee/agb_2021_732473_2020.tif
reusing cached AGB 2022 for 2021_732473: ../data/cci_agb_ee/agb_2021_732473_2022.tif
2021_732473 done: 0 cells
re-running 2022_25568
reusing cached AGB 2020 for 2022_25568: ../data/cci_agb_ee/agb_2022_25568_2020.tif
reusing cached AGB 2022 for 2022_25568: ../data/cci_agb_ee/agb_2022_25568_2022.tif
2022_25568 done: 85 cells
re-running 2020_281573
reusing cached AGB 2019 for 2020_281573: ../data/cci_agb_ee/agb_2020_281573_2019.tif
reusing cached AGB 2021 for 2020_281573: ../data/cci_agb_ee/agb_2020_281573_2021.tif
reusing cached AGB 2022 for 2020_281573: ../data/cci_agb_ee/agb_2020_281573_2022.tif
2020_281573 done: 25 cells
re-running 2020_876837
reusing cached AGB 2019 for 2020_876837: ../data/cci_agb_ee/agb_2020_876837_2019.tif
reusing cached AGB 2021 for 2020_876837: ../data/cci_agb_ee/agb_2020_876837_2021.tif
reusing cached AGB 2022 for 2020_876837: ../data/cci_agb_ee/agb_2020_876837_2022.tif
2020_876837 done: 277 cells

In [16]:
print(len(results))
print(all(uid in results for uid in affected_uids_main))

186
True

## Pool, check forest-type recovery, save

Compares the `unknown` share using the new two-band fallback (`forest_type_label`,
computed inside `build_cell_table`) against the old single-band approach, to see
how much the `discrete_classification` fallback actually recovered.

In [17]:
full = pd.concat([df.assign(uid=uid) for uid, df in results.items()], ignore_index=True)
full["height_class"] = pd.cut(full["height"], [0, 10, 20, 100], labels=["<10m", "10-20m", ">20m"])

print("fires:", full["uid"].nunique(), " total cells:", len(full))
print(full["forest_type_label"].value_counts(normalize=True))

# old (primary-band-only) unknown share, for comparison, using the raw forest_type codes
from src.forest_type import FOREST_TYPE_LABELS
old_label = full["forest_type"].map(FOREST_TYPE_LABELS)
print("old unknown share (forest_type band only):", (old_label == "unknown").mean())
print("new unknown share (with discrete_classification fallback):", (full["forest_type_label"] == "unknown").mean())

fires: 154  total cells: 507169
forest_type_label
evergreen_needleleaf    0.616195
evergreen_broadleaf     0.188809
unknown                 0.118889
not_forest              0.031563
mixed                   0.023659
deciduous_broadleaf     0.017422
deciduous_needleleaf    0.003462
Name: proportion, dtype: float64
old unknown share (forest_type band only): 0.1763179531872019
new unknown share (with discrete_classification fallback): 0.11888936429474199

In [18]:
import os
os.makedirs("../data/processed", exist_ok=True)
full.to_parquet("../data/processed/all_cells.parquet")
print("saved", len(full), "cells to ../data/processed/all_cells.parquet")

saved 507169 cells to ../data/processed/all_cells.parquet

In [19]:
dn = full[full["forest_type_label"] == "deciduous_needleleaf"]
print(dn["uid"].nunique(), "fires with at least one deciduous_needleleaf cell")
print(len(dn), "total deciduous_needleleaf cells")
print(dn.groupby("uid").size().sort_values(ascending=False))

4 fires with at least one deciduous_needleleaf cell
1756 total deciduous_needleleaf cells
uid
2021_731492    1322
2021_745780     370
2020_812775      45
2020_810300      19
dtype: int64

## Curve fits (draft, not final - uncertainty still wide, see README Section 12)

In [51]:
import importlib, src.curves
importlib.reload(src.curves)
from src.curves import fit_all_groups, bootstrap_curve_band, logistic, per_fire_severity_means

fit_table = fit_all_groups(full)
print(fit_table)

                                        status     l_max          k        x0  \
<10m   deciduous_broadleaf              fitted  0.166128  13.068274  0.377222
       deciduous_needleleaf  insufficient_data       NaN        NaN       NaN
       evergreen_broadleaf              fitted  0.421881  17.297382   0.31247
       evergreen_needleleaf     degenerate_fit  0.002943  25.672147  1.982347
       mixed                    degenerate_fit  0.305555       50.0  0.772502
10-20m deciduous_broadleaf              fitted   0.18086  41.921277  0.286035
       deciduous_needleleaf     degenerate_fit    0.1633  16.366795  1.689707
       evergreen_broadleaf              fitted  0.239924  15.576634  0.363218
       evergreen_needleleaf             fitted  0.170944  20.783718  0.521459
       mixed                            fitted  0.153603  14.296565  0.720549
>20m   deciduous_broadleaf      degenerate_fit  0.048018  14.759458  1.827267
       deciduous_needleleaf  insufficient_data       NaN        NaN       NaN
       evergreen_broadleaf      degenerate_fit  0.254235       50.0  0.985065
       evergreen_needleleaf             fitted  0.395952  13.900822  0.553664
       mixed                    degenerate_fit  0.090764        0.0  1.999832

                                                                 param_std_err  \
<10m   deciduous_broadleaf   [0.06084468641523381, 9.181687680338905, 0.098...
       deciduous_needleleaf                                                NaN
       evergreen_broadleaf   [0.017366052059585566, 1.677912669383521, 0.00...
       evergreen_needleleaf  [10490192.222979462, 5248548295.007583, 647516...
       mixed                 [0.12403747977014701, 53.27343818454913, 0.032...
10-20m deciduous_broadleaf   [0.02219019625175319, 21.2046375322959, 0.0175...
       deciduous_needleleaf  [16811415.5075291, 115500299.41801153, 9276454...
       evergreen_broadleaf   [0.008685995417527825, 1.3430574093831402, 0.0...
       evergreen_needleleaf  [0.004202463086586053, 2.2748924984975734, 0.0...
       mixed                 [0.02276744321579729, 3.556457085467058, 0.030...
>20m   deciduous_broadleaf   [71080676.52440515, 3203522343.897603, 3353011...
       deciduous_needleleaf                                                NaN
       evergreen_broadleaf   [0.49315012895059557, 142.48074363902884, 0.10...
       evergreen_needleleaf  [0.0024698849084085783, 0.49504169227870926, 0...
       mixed                     [0.43402391092490894, 5.710518915158255, 0.0]

                            n_fires n_cells
<10m   deciduous_broadleaf       55    1970
       deciduous_needleleaf       3     118
       evergreen_broadleaf       69   11354
       evergreen_needleleaf      32   22838
       mixed                     22    2367
10-20m deciduous_broadleaf       71    6508
       deciduous_needleleaf       4    1515
       evergreen_broadleaf       75   52865
       evergreen_needleleaf      36  121742
       mixed                     25    9323
>20m   deciduous_broadleaf       12     335
       deciduous_needleleaf       2     119
       evergreen_broadleaf       48   31339
       evergreen_needleleaf      31  167790
       mixed                     18     303

## dNBR vs RBR: does RBR actually tighten cross-forest-type consistency?

Repeatable comparison (README Section 15). Fits every group twice, once on
`dnbr`, once on `rbr`, and lines up `l_max` side by side. Re-run this as more
fires are added, the Section 15 conclusion (RBR is a wash, not an improvement,
at 118 fires) may not hold forever, especially once Mixed/Deciduous groups
have enough fires to stop being `insufficient_data`.

In [21]:
fit_table_dnbr = fit_all_groups(full, dnbr_col="dnbr")
fit_table_rbr = fit_all_groups(full, dnbr_col="rbr")

compare = fit_table_dnbr.add_suffix("_dnbr").join(fit_table_rbr.add_suffix("_rbr"))
compare[["status_dnbr", "status_rbr", "l_max_dnbr", "l_max_rbr", "n_fires_dnbr"]]

/home/jupyter/fire-impact-curves/notebooks/../src/curves.py:23: RuntimeWarning: overflow encountered in exp
  return l_max / (1 + np.exp(-k * (x - x0)))

                                   status_dnbr         status_rbr l_max_dnbr  \
<10m   deciduous_broadleaf              fitted             fitted   0.166128
       deciduous_needleleaf  insufficient_data  insufficient_data        NaN
       evergreen_broadleaf              fitted             fitted   0.421881
       evergreen_needleleaf     degenerate_fit     degenerate_fit   0.002943
       mixed                    degenerate_fit     degenerate_fit   0.305555
10-20m deciduous_broadleaf              fitted             fitted    0.18086
       deciduous_needleleaf     degenerate_fit     degenerate_fit     0.1633
       evergreen_broadleaf              fitted             fitted   0.239924
       evergreen_needleleaf             fitted             fitted   0.170944
       mixed                            fitted             fitted   0.153603
>20m   deciduous_broadleaf      degenerate_fit     degenerate_fit   0.048018
       deciduous_needleleaf  insufficient_data  insufficient_data        NaN
       evergreen_broadleaf      degenerate_fit     degenerate_fit   0.254235
       evergreen_needleleaf             fitted             fitted   0.395952
       mixed                    degenerate_fit     degenerate_fit   0.090764

                            l_max_rbr n_fires_dnbr
<10m   deciduous_broadleaf   0.202804           55
       deciduous_needleleaf       NaN            3
       evergreen_broadleaf   0.403155           69
       evergreen_needleleaf  0.203954           32
       mixed                 0.336459           22
10-20m deciduous_broadleaf   0.200267           71
       deciduous_needleleaf  0.209845            4
       evergreen_broadleaf   0.231858           75
       evergreen_needleleaf  0.184945           36
       mixed                 0.248907           25
>20m   deciduous_broadleaf   0.143134           12
       deciduous_needleleaf       NaN            2
       evergreen_broadleaf   0.256681           48
       evergreen_needleleaf  0.405811           31
       mixed                 0.090764           18

## Plot every usable (non-degenerate, past threshold) group

Generic - plots whatever is actually fitted, not a hardcoded group, so this keeps
working as more fires get added and different groups cross the usable threshold.

Each dot is one real fire. Took every fire, split its burnt area into mild, moderate, and severe patches, and worked out how much biomass that fire actually lost in each category. So if there's 50 fires, that's up to 150 dots, one per fire per severity level. The dot isn't a guess or a model output, it's a direct measurement from that one fire. The blue band is how confident it is in the average trend line. The orange band is how much real fires actually differ from each other. Those are different things, a fire can reasonably sit outside the blue band while still being completely normal, inside the orange one.

In [ ]:
import matplotlib.pyplot as plt
from src.curves import bootstrap_curve_band, logistic, per_fire_severity_means

os.makedirs("../data/processed/curves", exist_ok=True)

# <10m excluded by policy (README known issue #8, GLAD height unreliable on steep
# terrain) regardless of fit status - a numerically clean fit does not make the
# underlying height measurement trustworthy
usable = fit_table[(fit_table["status"] == "fitted") & (fit_table.index.get_level_values(0) != "<10m")]

# Two different bands, often confused for each other (this is what the
# supervisor flagged: dots falling "outside the shaded region"):
# - the bootstrap band answers "how much would the FITTED CURVE move if we had
#   sampled a different set of fires" - it narrows as more fires are added, since
#   it is about confidence in the average trend, not about individual fires.
# - the fire-spread band answers "how much do REAL FIRES actually vary" around
#   that trend - built directly from the same per-fire dots, so it does not
#   narrow with more data, and most dots fall inside it by construction.
sev_mid = {"mild": 0.185, "moderate": 0.465, "severe": 0.8}

curve_records = []   # one row per group: the fitted parameters, saved below
band_records = []    # one row per group per dNBR grid point: the uncertainty band, saved below

for (height_class, forest_type), row in usable.iterrows():
    grp = full[(full["height_class"] == height_class) & (full["forest_type_label"] == forest_type)]
    band = bootstrap_curve_band(grp)
    if band is None:
        continue
    x_grid = band["dnbr"]

    curve_records.append({
        "height_class": height_class, "forest_type": forest_type,
        "l_max": row["l_max"], "k": row["k"], "x0": row["x0"],
        "n_fires": row["n_fires"], "n_cells": row["n_cells"],
    })
    band_df = band.copy()
    band_df["height_class"] = height_class
    band_df["forest_type"] = forest_type
    band_records.append(band_df)

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.fill_between(x_grid, band["p10"], band["p90"], alpha=0.25, color="tab:blue",
                     label="confidence in the average trend (80% band)")
    ax.plot(x_grid, logistic(x_grid, row["l_max"], row["k"], row["x0"]), linewidth=2,
            color="tab:blue", label="fitted curve (pooled)")

    # fire-spread band: 10th-90th percentile of actual per-fire severity-class
    # means, i.e. the same values the dots show, not a resample of the curve -
    # drawn as a vertical range at each severity class's x position
    pfm = per_fire_severity_means(grp)
    for sev, x in sev_mid.items():
        if sev not in pfm.columns:
            continue
        vals = pfm[sev].dropna()
        if len(vals) < 3:
            continue
        lo, hi = vals.quantile([0.1, 0.9])
        ax.plot([x, x], [lo, hi], color="tab:orange", linewidth=6, alpha=0.4, zorder=3,
                solid_capstyle="butt",
                label="spread of individual fires (10-90th pct)" if sev == "mild" else None)

    ax.scatter([], [], color="black", s=40, label="individual fire (one severity class)")
    for uid, fire_grp in grp.groupby("uid"):
        means = fire_grp.groupby("severity", observed=True)["loss2022"].mean()
        xs = [sev_mid[s] for s in means.index]
        ax.scatter(xs, means.values, s=40, zorder=5, color="black", alpha=0.5)

    ax.set_xlabel("dNBR (fire severity)")
    ax.set_ylabel("share of CCI biomass lost by 2022")
    cv_row = cv_summary[(cv_summary["height_class"] == height_class) & (cv_summary["forest_type"] == forest_type)]
    if len(cv_row) and not cv_row["mae"].isna().all():
        mae_val = cv_row["mae"].iloc[0]
        ax.text(0.98, 0.04, f"cross-validated MAE: {mae_val:.3f}", transform=ax.transAxes,
                ha="right", fontsize=8, color="#444", style="italic")

    ax.set_title(f"{forest_type}, {height_class} ({row['n_fires']} fires, {row['n_cells']} cells)")
    ax.legend(fontsize=7, loc="upper left")
    ax.set_ylim(-0.1, 1.0)
    fig.tight_layout()
    fname = f"../data/processed/curves/{forest_type}_{height_class}.png".replace(">", "gt")
    fig.savefig(fname, dpi=150)
    plt.show()
    print("saved", fname)

# save the actual curve data, not just the images - this is the real deliverable
pd.DataFrame(curve_records).to_csv("../data/processed/curves/fit_parameters.csv", index=False)
pd.concat(band_records, ignore_index=True).to_csv("../data/processed/curves/uncertainty_bands.csv", index=False)
print("saved fit_parameters.csv and uncertainty_bands.csv")

## Leave-one-fire-out cross-validation

Fit quality on the fires used to build a curve does not tell you whether it
predicts a NEW fire well. For each fire, refit on every other fire in its
group, then predict this fire's own per-severity-class loss and compare to
what actually happened. This is the real accuracy number to report, not
whether the curve looks clean on the data it was built from.

In [52]:
import importlib, src.curves
importlib.reload(src.curves)
from src.curves import cross_validate_all_groups

cv_summary = cross_validate_all_groups(full)
cv_summary

   height_class           forest_type  n_folds       mae      rmse      bias
0          <10m   deciduous_broadleaf       80  0.258272  0.440702  0.090168
1          <10m  deciduous_needleleaf        0       NaN       NaN       NaN
2          <10m   evergreen_broadleaf      121  0.238259  0.357577 -0.000851
3          <10m  evergreen_needleleaf        0       NaN       NaN       NaN
4          <10m                 mixed        6  0.284814  0.312641 -0.284814
5        10-20m   deciduous_broadleaf      102  0.264889  0.336990  0.114784
6        10-20m  deciduous_needleleaf        0       NaN       NaN       NaN
7        10-20m   evergreen_broadleaf      137  0.204232  0.289153  0.069190
8        10-20m  evergreen_needleleaf       93  0.161915  0.223702  0.013868
9        10-20m                 mixed       50  0.155861  0.235202  0.027143
10         >20m   deciduous_broadleaf        0       NaN       NaN       NaN
11         >20m  deciduous_needleleaf        0       NaN       NaN       NaN
12         >20m   evergreen_broadleaf        0       NaN       NaN       NaN
13         >20m  evergreen_needleleaf       84  0.214638  0.333159  0.007444
14         >20m                 mixed        0       NaN       NaN       NaN

In [24]:
import pandas as pd

target_types = ["evergreen_needleleaf", "evergreen_broadleaf", "mixed", "deciduous_broadleaf"]

candidates = []
for ft in target_types:
    sub = full[full["forest_type_label"] == ft]
    per_fire = sub.groupby("uid").agg(
        n_cells=("severity", "size"),
        n_severity_classes=("severity", "nunique"),
    ).reset_index()
    # prefer fires covering all 3 severity classes, moderate size (not the single biggest)
    per_fire = per_fire[per_fire["n_severity_classes"] == 3]
    per_fire = per_fire.sort_values("n_cells", ascending=False)
    # skip the single largest (likely an outlier fire, slow to run through Artio),
    # take the next 2 instead
    picks = per_fire.iloc[1:3]
    picks["forest_type"] = ft
    candidates.append(picks)

candidates_df = pd.concat(candidates, ignore_index=True)
print(candidates_df)

           uid  n_cells  n_severity_classes           forest_type
0     2020_112    76651                   3  evergreen_needleleaf
1     2021_190    49431                   3  evergreen_needleleaf
2  2020_880547    15248                   3   evergreen_broadleaf
3   2020_59053    14462                   3   evergreen_broadleaf
4   2021_26587     2576                   3                 mixed
5   2021_26579     2249                   3                 mixed
6   2021_26650      516                   3   deciduous_broadleaf
7  2021_745780      157                   3   deciduous_broadleaf

In [26]:
already_tested = {"2020_112", "2021_190"}
candidates = full[(full["height_class"] == "10-20m") & (full["forest_type_label"] == "evergreen_needleleaf")]
summary = (candidates.groupby("uid")
           .agg(n_cells=("uid", "size"), n_severity=("severity", "nunique"))
           .reset_index())
summary = summary[~summary["uid"].isin(already_tested) & (summary["n_severity"] == 3)]
summary = summary.sort_values("n_cells", ascending=False)
print(summary.head(10))

            uid  n_cells  n_severity
1      2020_135    29462           3
11    2020_6781    10278           3
22   2021_12957     8821           3
29   2021_26579     6462           3
2   2020_167817     3948           3
32   2021_26650     3268           3
5   2020_167823     1820           3
9   2020_408081     1585           3
31   2021_26587     1368           3
3   2020_167819      979           3

In [27]:
from src.curves import leave_one_fire_out_cv

for height, ft in [("10-20m", "evergreen_needleleaf"), ("10-20m", "mixed")]:
    grp = full[(full["height_class"] == height) & (full["forest_type_label"] == ft)]
    cv = leave_one_fire_out_cv(grp)
    cv = cv[cv["fit_status"] == "fitted"].copy()
    cv["abs_residual"] = cv["residual"].abs()
    cv = cv.sort_values("abs_residual")

    print(f"=== {ft}, {height} ({len(cv)} held-out fire-severity folds) ===")
    median_idx = len(cv) // 2
    print("Typical case (median error):")
    print(cv.iloc[median_idx][["uid", "severity", "n_cells", "actual", "predicted", "residual"]])
    print()

=== evergreen_needleleaf, 10-20m (93 held-out fire-severity folds) ===
Typical case (median error):
uid          2020_167823
severity          severe
n_cells              273
actual          0.047607
predicted       0.170252
residual       -0.122646
Name: 59, dtype: object

=== mixed, 10-20m (50 held-out fire-severity folds) ===
Typical case (median error):
uid          2021_169679
severity        moderate
n_cells               99
actual          0.097453
predicted       0.003786
residual        0.093667
Name: 28, dtype: object

In [28]:
grp = full[(full["height_class"] == ">20m") & (full["forest_type_label"] == "evergreen_broadleaf")]
print(grp["severity"].value_counts())
print()
print(grp["dnbr"].describe())

severity
moderate    15116
mild        13967
severe       2256
Name: count, dtype: int64

count    31339.000000
mean         0.337152
std          0.186127
min          0.100009
25%          0.185975
50%          0.295541
75%          0.443982
max          1.092588
Name: dnbr, dtype: float64

In [30]:
print(grp.groupby("severity", observed=True)["loss2022"].mean())
print(grp.groupby("severity", observed=True)["loss2022"].std())

severity
mild        0.007767
moderate    0.137087
severe      0.296605
Name: loss2022, dtype: float64
severity
mild        0.512935
moderate    0.613408
severe      0.434119
Name: loss2022, dtype: float64

In [34]:
grp = full[(full["height_class"] == "10-20m") & (full["forest_type_label"] == "deciduous_broadleaf")]
print(grp.groupby("severity", observed=True)["loss2022"].mean())
print(grp.groupby("severity", observed=True)["loss2022"].std())

severity
mild       -0.002032
moderate    0.138697
severe      0.296400
Name: loss2022, dtype: float64
severity
mild        0.401347
moderate    0.396072
severe      0.262677
Name: loss2022, dtype: float64

In [36]:
import sys
sys.path.append("..")
import ee
from src.fires import load_fire
from src.ndvi import build_ndvi, export_ndvi, download_ndvi

test_batch = (
    full.groupby(["uid", "forest_type_label"], observed=True).size().reset_index()
    .groupby("forest_type_label", observed=True).head(3)["uid"].tolist()
)
print(f"{len(test_batch)} fires selected:", test_batch)

ndvi_tasks = {}
for cfg in all_fire_configs:
    if cfg["uid"] not in test_batch:
        continue
    uid = cfg["uid"]
    fire = load_fire(uid)
    aoi = ee.Geometry.Rectangle(list(fire.total_bounds))  # w, s, e, n
    image = build_ndvi(aoi, *cfg["pre_fire_window"], *cfg["post_fire_window"])
    ndvi_tasks[uid] = export_ndvi(image, uid, aoi)
    print(uid, "submitted")

21 fires selected: ['2019_136948', '2019_136948', '2019_248585', '2019_248585', '2019_277640', '2019_419994', '2019_873628', '2019_873628', '2019_873628', '2019_873630', '2019_873630', '2020_10559', '2020_112', '2020_12804', '2020_135', '2020_135', '2020_167817', '2020_235778', '2020_810300', '2020_812775', '2021_731492']
pre 2020-07-01..2020-08-10: 54 images; post 2021-07-01..2021-08-31: 79 images
2020_112 submitted
pre 2020-07-01..2020-08-15: 18 images; post 2021-07-01..2021-08-31: 21 images
2020_135 submitted
pre 2019-12-31..2020-03-15: 9 images; post 2020-12-31..2021-03-15: 14 images
2020_12804 submitted
pre 2020-01-10..2020-03-25: 14 images; post 2021-01-10..2021-03-25: 5 images
2020_10559 submitted
pre 2020-06-13..2020-08-27: 24 images; post 2021-06-13..2021-08-27: 20 images
2020_167817 submitted
pre 2019-11-24..2020-02-07: 50 images; post 2020-11-24..2021-02-07: 42 images
2019_248585 submitted
pre 2019-11-01..2020-01-15: 17 images; post 2020-11-01..2021-01-15: 12 images
2019_277640 submitted
pre 2019-12-19..2020-03-03: 34 images; post 2020-12-19..2021-03-03: 4 images
2020_810300 submitted
pre 2019-12-19..2020-03-03: 5 images; post 2020-12-19..2021-03-03: 2 images
2020_812775 submitted
pre 2020-01-13..2020-03-28: 6 images; post 2021-01-13..2021-03-28: 9 images
2020_235778 submitted
pre 2019-10-04..2019-12-18: 19 images; post 2020-10-04..2020-12-18: 13 images
2019_873628 submitted
pre 2019-10-05..2019-12-19: 19 images; post 2020-10-05..2020-12-19: 13 images
2019_873630 submitted
pre 2019-11-23..2020-02-06: 18 images; post 2020-11-23..2021-02-06: 22 images
2019_136948 submitted
pre 2019-11-15..2020-01-29: 28 images; post 2020-11-15..2021-01-29: 25 images
2019_419994 submitted

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-10..2021-02-23: 22 images; post 2021-12-10..2022-02-23: 39 images
2021_731492 submitted

## NDVI test: poll exports and download

In [37]:
import time

while True:
    states = {uid: t.status()["state"] for uid, t in ndvi_tasks.items()}
    print(states)
    if all(s in ("COMPLETED", "FAILED", "CANCELLED") for s in states.values()):
        break
    time.sleep(60)

ndvi_paths = {}
for uid, t in ndvi_tasks.items():
    if t.status()["state"] == "COMPLETED":
        ndvi_paths[uid] = download_ndvi(uid)
        print(uid, "downloaded ->", ndvi_paths[uid])
    else:
        print(uid, "FAILED, status:", t.status())

{'2020_112': 'RUNNING', '2020_135': 'RUNNING', '2020_12804': 'COMPLETED', '2020_10559': 'COMPLETED', '2020_167817': 'COMPLETED', '2019_248585': 'COMPLETED', '2019_277640': 'COMPLETED', '2020_810300': 'RUNNING', '2020_812775': 'RUNNING', '2020_235778': 'READY', '2019_873628': 'READY', '2019_873630': 'READY', '2019_136948': 'READY', '2019_419994': 'READY', '2021_731492': 'READY'}
{'2020_112': 'RUNNING', '2020_135': 'RUNNING', '2020_12804': 'COMPLETED', '2020_10559': 'COMPLETED', '2020_167817': 'COMPLETED', '2019_248585': 'COMPLETED', '2019_277640': 'COMPLETED', '2020_810300': 'COMPLETED', '2020_812775': 'COMPLETED', '2020_235778': 'RUNNING', '2019_873628': 'RUNNING', '2019_873630': 'READY', '2019_136948': 'READY', '2019_419994': 'READY', '2021_731492': 'READY'}
{'2020_112': 'COMPLETED', '2020_135': 'COMPLETED', '2020_12804': 'COMPLETED', '2020_10559': 'COMPLETED', '2020_167817': 'COMPLETED', '2019_248585': 'COMPLETED', '2019_277640': 'COMPLETED', '2020_810300': 'COMPLETED', '2020_812775': 'COMPLETED', '2020_235778': 'COMPLETED', '2019_873628': 'COMPLETED', '2019_873630': 'COMPLETED', '2019_136948': 'COMPLETED', '2019_419994': 'COMPLETED', '2021_731492': 'RUNNING'}
{'2020_112': 'COMPLETED', '2020_135': 'COMPLETED', '2020_12804': 'COMPLETED', '2020_10559': 'COMPLETED', '2020_167817': 'COMPLETED', '2019_248585': 'COMPLETED', '2019_277640': 'COMPLETED', '2020_810300': 'COMPLETED', '2020_812775': 'COMPLETED', '2020_235778': 'COMPLETED', '2019_873628': 'COMPLETED', '2019_873630': 'COMPLETED', '2019_136948': 'COMPLETED', '2019_419994': 'COMPLETED', '2021_731492': 'COMPLETED'}

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2020_112.tif...
/ [1 files][ 22.8 MiB/ 22.8 MiB]
Operation completed over 1 objects/22.8 MiB.

2020_112 downloaded -> ../data/ndvi/ndvi_2020_112.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2020_135.tif...
- [1 files][ 27.1 MiB/ 27.1 MiB]
Operation completed over 1 objects/27.1 MiB.

2020_135 downloaded -> ../data/ndvi/ndvi_2020_135.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2020_12804.tif...
/ [1 files][458.5 KiB/458.5 KiB]
Operation completed over 1 objects/458.5 KiB.

2020_12804 downloaded -> ../data/ndvi/ndvi_2020_12804.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2020_10559.tif...
/ [1 files][859.1 KiB/859.1 KiB]
Operation completed over 1 objects/859.1 KiB.

2020_10559 downloaded -> ../data/ndvi/ndvi_2020_10559.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2020_167817.tif...
/ [1 files][  1.8 MiB/  1.8 MiB]
Operation completed over 1 objects/1.8 MiB.

2020_167817 downloaded -> ../data/ndvi/ndvi_2020_167817.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2019_248585.tif...
/ [1 files][494.9 KiB/494.9 KiB]
Operation completed over 1 objects/494.9 KiB.

2019_248585 downloaded -> ../data/ndvi/ndvi_2019_248585.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2019_277640.tif...
/ [1 files][586.9 KiB/586.9 KiB]
Operation completed over 1 objects/586.9 KiB.

2019_277640 downloaded -> ../data/ndvi/ndvi_2019_277640.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2020_810300.tif...
/ [1 files][  2.3 MiB/  2.3 MiB]
Operation completed over 1 objects/2.3 MiB.

2020_810300 downloaded -> ../data/ndvi/ndvi_2020_810300.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2020_812775.tif...
/ [1 files][  6.1 MiB/  6.1 MiB]
Operation completed over 1 objects/6.1 MiB.

2020_812775 downloaded -> ../data/ndvi/ndvi_2020_812775.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2020_235778.tif...
/ [1 files][682.5 KiB/682.5 KiB]
Operation completed over 1 objects/682.5 KiB.

2020_235778 downloaded -> ../data/ndvi/ndvi_2020_235778.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2019_873628.tif...
/ [1 files][  4.2 MiB/  4.2 MiB]
Operation completed over 1 objects/4.2 MiB.

2019_873628 downloaded -> ../data/ndvi/ndvi_2019_873628.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2019_873630.tif...
/ [1 files][  2.2 MiB/  2.2 MiB]
Operation completed over 1 objects/2.2 MiB.

2019_873630 downloaded -> ../data/ndvi/ndvi_2019_873630.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2019_136948.tif...
/ [1 files][527.4 KiB/527.4 KiB]
Operation completed over 1 objects/527.4 KiB.

2019_136948 downloaded -> ../data/ndvi/ndvi_2019_136948.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2019_419994.tif...
/ [1 files][521.3 KiB/521.3 KiB]
Operation completed over 1 objects/521.3 KiB.

2019_419994 downloaded -> ../data/ndvi/ndvi_2019_419994.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/ndvi/ndvi_2021_731492.tif...
/ [1 files][ 11.7 MiB/ 11.7 MiB]
Operation completed over 1 objects/11.7 MiB.

2021_731492 downloaded -> ../data/ndvi/ndvi_2021_731492.tif

In [38]:
import numpy as np
import pandas as pd
from rasterio.warp import Resampling
from rasterio.features import rasterize
from src.grids import read_window, reproject_to_grid, pad_bounds
from src.fires import inner_burn_area, load_fire
from src.pipeline import DNBR_DROP_BELOW

def ndvi_loss_for_fire(uid, ndvi_path, cfg, pad=0.15, min_agb_before=10):
    fire = load_fire(uid)
    bounds = pad_bounds(fire.total_bounds, pad)
    utm_epsg = utm_epsg_for(cfg["lon"], cfg["lat"])
    inner = inner_burn_area(fire, utm_epsg=utm_epsg)

    # same reference grid every other layer uses: derived from the cached AGB-before file
    agb_path = f"../data/cci_agb_ee/agb_{uid}_{cfg['agb_before_year']}.tif"
    agb_before, tr_ref, crs_ref = read_window(agb_path, bounds)
    shape = agb_before.shape

    mask_inner = rasterize(
        [(g, 1) for g in inner.geometry], out_shape=shape,
        transform=tr_ref, fill=0, dtype="uint8",
    ).astype(bool)
    valid = np.isfinite(agb_before) & (agb_before > min_agb_before)
    for yr in cfg["agb_after_years"]:
        agb_after_path = f"../data/cci_agb_ee/agb_{uid}_{yr}.tif"
        agb_after, _, _ = read_window(agb_after_path, bounds)
        valid &= np.isfinite(agb_after)
    keep = mask_inner & valid

    # recompute dnbr the same way build_cell_table does, as a cross-check, not for its own sake
    severity_path = f"../data/severity/severity_{uid}.tif"
    dnbr_arr, tr_d, crs_d = read_window(severity_path, bounds, band=1)
    dnbr_100m = reproject_to_grid(
        np.nan_to_num(dnbr_arr, nan=-9999).astype("float32"), tr_d, crs_d, shape, tr_ref, crs_ref,
        resampling=Resampling.average, src_nodata=-9999,
    )

    # NDVI onto the same grid, same nodata handling as every other layer
    ndvi_pre_arr, tr_n, crs_n = read_window(ndvi_path, bounds, band=1)
    ndvi_post_arr, _, _ = read_window(ndvi_path, bounds, band=2)
    ndvi_pre_100m = reproject_to_grid(
        np.nan_to_num(ndvi_pre_arr, nan=-9999).astype("float32"), tr_n, crs_n, shape, tr_ref, crs_ref,
        resampling=Resampling.average, src_nodata=-9999,
    )
    ndvi_post_100m = reproject_to_grid(
        np.nan_to_num(ndvi_post_arr, nan=-9999).astype("float32"), tr_n, crs_n, shape, tr_ref, crs_ref,
        resampling=Resampling.average, src_nodata=-9999,
    )

    d = pd.DataFrame({
        "uid": uid,
        "dnbr_recomputed": dnbr_100m[keep],
        "ndvi_pre": ndvi_pre_100m[keep],
        "ndvi_post": ndvi_post_100m[keep],
    })
    d = d[d["dnbr_recomputed"] >= DNBR_DROP_BELOW].copy()
    d["ndvi_loss"] = (d["ndvi_pre"] - d["ndvi_post"]) / d["ndvi_pre"]
    return d

ndvi_results = []
for cfg in all_fire_configs:
    uid = cfg["uid"]
    if uid not in ndvi_paths:
        continue
    d = ndvi_loss_for_fire(uid, ndvi_paths[uid], cfg)
    ndvi_results.append(d)

ndvi_cells = pd.concat(ndvi_results, ignore_index=True)

# ALIGNMENT CHECK - do not trust anything below this until this looks right
for uid in ndvi_paths:
    recomputed = ndvi_cells[ndvi_cells["uid"] == uid]["dnbr_recomputed"].reset_index(drop=True)
    existing = full[full["uid"] == uid]["dnbr"].reset_index(drop=True)
    if len(recomputed) != len(existing):
        print(f"{uid}: MISMATCH in row count ({len(recomputed)} vs {len(existing)}) - do not trust this fire's NDVI merge")
    else:
        max_diff = (recomputed - existing).abs().max()
        print(f"{uid}: {len(existing)} cells, max dnbr difference = {max_diff:.6f}")

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

2020_112: 120632 cells, max dnbr difference = 0.000000
2020_135: 109019 cells, max dnbr difference = 0.000000
2020_12804: 56 cells, max dnbr difference = 0.000000
2020_10559: 647 cells, max dnbr difference = 0.000000
2020_167817: 6510 cells, max dnbr difference = 0.000000
2019_248585: 31 cells, max dnbr difference = 0.000000
2019_277640: 7 cells, max dnbr difference = 0.000000
2020_810300: 51 cells, max dnbr difference = 0.000000
2020_812775: 1855 cells, max dnbr difference = 0.000000
2020_235778: 151 cells, max dnbr difference = 0.000000
2019_873628: 4899 cells, max dnbr difference = 0.000000
2019_873630: 3943 cells, max dnbr difference = 0.000000
2019_136948: 228 cells, max dnbr difference = 0.000000
2019_419994: 4 cells, max dnbr difference = 0.000000
2021_731492: 3604 cells, max dnbr difference = 0.000000

In [39]:
rows = []
for uid in ndvi_paths:
    sub_full = full[full["uid"] == uid].reset_index(drop=True)
    sub_ndvi = ndvi_cells[ndvi_cells["uid"] == uid].reset_index(drop=True)
    merged = pd.concat(
        [sub_full[["dnbr", "severity", "forest_type_label", "height_class", "loss2022"]],
         sub_ndvi[["ndvi_pre", "ndvi_post", "ndvi_loss"]]],
        axis=1,
    )
    valid = merged["ndvi_loss"].notna() & merged["loss2022"].notna()
    merged = merged[valid]
    if len(merged) < 5:
        continue
    rows.append({
        "uid": uid,
        "forest_type": merged["forest_type_label"].mode().iloc[0],
        "n_cells": len(merged),
        "mean_biomass_loss": merged["loss2022"].mean(),
        "mean_ndvi_loss": merged["ndvi_loss"].mean(),
        "corr": merged["loss2022"].corr(merged["ndvi_loss"]),
    })

ndvi_vs_biomass = pd.DataFrame(rows)
print(ndvi_vs_biomass)

           uid           forest_type  n_cells  mean_biomass_loss  \
0     2020_112  evergreen_needleleaf    56870           0.060061
1     2020_135  evergreen_needleleaf    62152           0.178164
2  2021_731492   deciduous_broadleaf     1424          -0.026565

   mean_ndvi_loss      corr
0        0.412820 -0.005515
1        0.178598  0.001784
2       -0.117798  0.029883

In [60]:
fit_table.index.names = ["height_class", "forest_type"]

adjusted_rows = []
for _, row in fit_table.reset_index().iterrows():
    if row["status"] != "fitted":
        continue
    cv_row = cv_summary[(cv_summary["height_class"] == row["height_class"])
                         & (cv_summary["forest_type"] == row["forest_type"])]
    bias = cv_row["bias"].iloc[0] if len(cv_row) and not cv_row["bias"].isna().all() else 0.0
    l_max_adjusted = min(row["l_max"] + bias, 1.0)
    adjusted_rows.append({
        "height_class": row["height_class"], "forest_type": row["forest_type"],
        "l_max_raw": row["l_max"], "bias": bias, "l_max_adjusted": l_max_adjusted,
        "n_fires": row["n_fires"], "n_cells": row["n_cells"],
    })

adjusted_table = pd.DataFrame(adjusted_rows)
print(adjusted_table)

  height_class           forest_type  l_max_raw      bias  l_max_adjusted  \
0         <10m   deciduous_broadleaf   0.158763  0.084116        0.242879
1         <10m   evergreen_broadleaf   0.470637 -0.030389        0.440247
2       10-20m   deciduous_broadleaf   0.201581  0.121691        0.323272
3       10-20m   evergreen_broadleaf   0.313728  0.069410        0.383138
4       10-20m  evergreen_needleleaf   0.170938  0.007627        0.178565
5       10-20m                 mixed   0.155505  0.040235        0.195740
6         >20m  evergreen_needleleaf   0.395952  0.007005        0.402957
7         >20m                 mixed   0.182942  0.030901        0.213843

   n_fires  n_cells
0       86     3924
1      128    19674
2      102     8014
3      145    72625
4       40   122250
5       35    10214
6       33   167826
7       24      842

### Bias-correction

In [43]:
def validate_bias_correction(height, ft):
    grp = full[(full["height_class"] == height) & (full["forest_type_label"] == ft)]
    cv = leave_one_fire_out_cv(grp)
    cv = cv[cv["fit_status"] == "fitted"].copy()

    cv["loo_bias"] = cv.apply(
        lambda row: cv[cv["uid"] != row["uid"]]["residual"].mean(), axis=1
    )
    cv["corrected_predicted"] = cv["predicted"] + cv["loo_bias"]
    cv["corrected_residual"] = cv["actual"] - cv["corrected_predicted"]

    print(f"{ft}, {height}:")
    print(f"  raw       MAE={cv['residual'].abs().mean():.3f}  bias={cv['residual'].mean():.3f}")
    print(f"  corrected MAE={cv['corrected_residual'].abs().mean():.3f}  bias={cv['corrected_residual'].mean():.3f}")

for height, ft in [("10-20m", "evergreen_needleleaf"), ("10-20m", "mixed"),
                    ("10-20m", "evergreen_broadleaf"), ("10-20m", "deciduous_broadleaf"),
                    (">20m", "evergreen_needleleaf")]:
    validate_bias_correction(height, ft)

evergreen_needleleaf, 10-20m:
  raw       MAE=0.162  bias=0.014
  corrected MAE=0.165  bias=-0.000
mixed, 10-20m:
  raw       MAE=0.156  bias=0.027
  corrected MAE=0.157  bias=-0.000
evergreen_broadleaf, 10-20m:
  raw       MAE=0.204  bias=0.069
  corrected MAE=0.205  bias=-0.000
deciduous_broadleaf, 10-20m:
  raw       MAE=0.265  bias=0.115
  corrected MAE=0.258  bias=-0.000
evergreen_needleleaf, >20m:
  raw       MAE=0.215  bias=0.007
  corrected MAE=0.217  bias=-0.000

### CCI v7 validation

In [40]:
coll = ee.ImageCollection("projects/sat-io/open-datasets/ESA/ESA_CCI_AGB")
print("number of images:", coll.size().getInfo())

first = coll.first()
info = first.getInfo()
print("bands:", [b["id"] for b in info["bands"]])
print("properties:", info["properties"])
print("native resolution (m):", first.select(0).projection().nominalScale().getInfo())

# list every image's id/date so we can see how years are organised
ids = coll.aggregate_array("system:index").getInfo()
print("image ids:", ids)

number of images: 10
bands: ['AGB', 'SD']
properties: {'Conventions': 'CF-1.7', 'keywords': 'satellite, observation, forest, biomass', 'references': 'http://cci.esa.int/biomass', 'year': '2007', 'naming_authority': 'ch.gamma-rs', 'keywords_vocabulary': 'NASA Global Change Master Directory (GCMD) Science Keywords', 'project': 'Climate Change Initiative - European Space Agency', 'source': 'ALOS-2 PALSAR-2 FB and WB, Sentinel-1 GRD', 'platform': 'ALOS-2, Sentinel-1A, Sentinel-1B', 'institution': 'GAMMA Remote Sensing', 'cdm_data_type': 'INT', 'format_version': 'CCI Data Standards v2.1', 'creator_email': 'santoro@gamma-rs.ch', 'system:footprint': {'type': 'LinearRing', 'coordinates': [[-180, -90], [180, -90], [180, 90], [-180, 90], [-180, -90]]}, 'spatial_resolution': '100 m', 'EPSG': '4326', 'key_variables': 'AGB', 'product_version': '6.0', 'date_created': '2025-04-17', 'system:time_end': 1199059200000, 'version': '6.0', 'system:time_start': 1167609600000, 'license': 'ESA CCI Data Policy: free and open access', 'AREA_OR_POINT': 'Area', 'creator_name': 'GAMMA Remote Sensing', 'sensor': 'PALSAR-2, SAR-C', 'creator_url': 'www.gamma-rs.ch', 'system:asset_size': 25727052644, 'system:index': 'CCI_BIOMASS_100m_AGB_2007_V6'}
native resolution (m): 98.95065848290984
image ids: ['CCI_BIOMASS_100m_AGB_2007_V6', 'CCI_BIOMASS_100m_AGB_2010_V6', 'CCI_BIOMASS_100m_AGB_2015_V6', 'CCI_BIOMASS_100m_AGB_2016_V6', 'CCI_BIOMASS_100m_AGB_2017_V6', 'CCI_BIOMASS_100m_AGB_2018_V6', 'CCI_BIOMASS_100m_AGB_2019_V6', 'CCI_BIOMASS_100m_AGB_2020_V6', 'CCI_BIOMASS_100m_AGB_2021_V6', 'CCI_BIOMASS_100m_AGB_2022_V6']

## Round-2 top-up: Evergreen Broadleaf + Deciduous Broadleaf

Targeted addition, not a full rebuild, aimed specifically at pushing `Evergreen Broadleaf, >20m` past the degenerate threshold and reducing `Deciduous Broadleaf, 10-20m`'s error, per the noise diagnosis earlier.

In [44]:
# Round-2 top-up: Evergreen Broadleaf (to push its degenerate >20m group over
# the line) + Deciduous Broadleaf (to reduce its largest bias/error)
sel_full = pd.read_parquet("../data/processed/forest_fires_2020_2021_attrs.parquet")

already_run = {cfg["uid"] for cfg in fire_configs} | {cfg["uid"] for cfg in new_fire_configs}
dupe_uids = sel_full["uid"][sel_full["uid"].duplicated(keep=False)].unique()

topup2_candidates = sel_full[
    (sel_full["landcover"].isin(["Evergreen Broadleaf forest", "Deciduous Broadleaf forest"]))
    & (sel_full["size"] >= 20)
    & (~sel_full["uid"].isin(already_run))
    & (~sel_full["uid"].isin(dupe_uids))
]
n_per_region = 10
parts = []
for (lc, region), g in topup2_candidates.groupby(["landcover", "GFED_regio"]):
    parts.append(g.sample(n=min(n_per_region, len(g)), random_state=2))
topup2_sample = pd.concat(parts, ignore_index=True)
print(len(topup2_sample), "fires selected for round-2 top-up")
print(topup2_sample.groupby("landcover").size())

import importlib, src.fires
importlib.reload(src.fires)
from src.fires import derive_fire_params
topup2_configs = [derive_fire_params(row) for _, row in topup2_sample.iterrows()]
new_fire_configs.extend(topup2_configs)
print(len(new_fire_configs), "total new_fire_configs now queued")

113 fires selected for round-2 top-up
landcover
Deciduous Broadleaf forest    53
Evergreen Broadleaf forest    60
dtype: int64
318 total new_fire_configs now queued

In [45]:
# submit + build only for the new round-2 fires, not the whole dataset again
topup2_submitted = submit_severity_tasks(topup2_configs)
topup2_submitted = wait_and_download_severity(topup2_submitted)

topup2_results = {}
for cfg in topup2_configs:
    uid = cfg["uid"]
    lon, lat = cfg.pop("lon"), cfg.pop("lat")
    print("running", uid)
    try:
        topup2_results[uid] = build_cell_table(
            utm_epsg=utm_epsg_for(lon, lat),
            severity_path=topup2_submitted[uid]["severity_path"],
            **cfg,
        )
        print(uid, "done:", len(topup2_results[uid]), "cells")
    except Exception as e:
        print(uid, "FAILED:", e)
    cfg["lon"], cfg["lat"] = lon, lat

# attach new fires' cells onto the existing pooled table, rather than rebuild it
new_full = pd.concat(
    [full] + [df.assign(uid=uid) for uid, df in topup2_results.items()],
    ignore_index=True,
)
print(f"full: {len(full)} cells -> new_full: {len(new_full)} cells ({len(topup2_results)} new fires)")

pre 2019-12-15..2020-02-28: 12 images; post 2020-12-15..2021-02-28: 10 images
submitted severity export for 2020_18444
pre 2020-02-07..2020-04-22: 56 images; post 2021-02-07..2021-04-22: 52 images
submitted severity export for 2020_4073

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-01-08..2021-03-24: 26 images; post 2022-01-08..2022-03-24: 25 images
submitted severity export for 2021_4466
pre 2020-01-12..2020-03-27: 52 images; post 2021-01-12..2021-03-27: 50 images
submitted severity export for 2020_4403
pre 2020-02-16..2020-05-01: 97 images; post 2021-02-16..2021-05-01: 92 images
submitted severity export for 2020_4159
pre 2020-02-16..2020-05-01: 11 images; post 2021-02-16..2021-05-01: 14 images
submitted severity export for 2020_2313

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-02-10..2021-04-26: 86 images; post 2022-02-10..2022-04-26: 87 images
submitted severity export for 2021_2474

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-22..2021-03-07: 45 images; post 2021-12-22..2022-03-07: 42 images
submitted severity export for 2021_5536

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-14..2021-02-27: 13 images; post 2021-12-14..2022-02-27: 12 images
submitted severity export for 2021_1512

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-05-24..2021-08-07: 37 images; post 2022-05-24..2022-08-07: 41 images
submitted severity export for 2021_54726
pre 2020-07-06..2020-09-19: 46 images; post 2021-07-06..2021-09-19: 51 images
submitted severity export for 2020_73351
2020_86085 FAILED to submit: expected exactly one match for uid '2020_86085' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2
2020_77169 FAILED to submit: expected exactly one match for uid '2020_77169' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2
pre 2020-06-04..2020-08-18: 11 images; post 2021-06-04..2021-08-18: 12 images
submitted severity export for 2020_72488
pre 2020-06-16..2020-08-30: 18 images; post 2021-06-16..2021-08-30: 16 images
submitted severity export for 2020_61506

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-05-19..2021-08-02: 18 images; post 2022-05-19..2022-08-02: 14 images
submitted severity export for 2021_57075

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-05-24..2021-08-07: 19 images; post 2022-05-24..2022-08-07: 14 images
submitted severity export for 2021_57082
pre 2020-05-26..2020-08-09: 26 images; post 2021-05-26..2021-08-09: 23 images
submitted severity export for 2020_75388

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-05-24..2021-08-07: 15 images; post 2022-05-24..2022-08-07: 12 images
submitted severity export for 2021_58633
pre 2019-11-05..2020-01-19: 45 images; post 2020-11-05..2021-01-19: 46 images
submitted severity export for 2019_249284
pre 2020-11-02..2021-01-16: 20 images; post 2021-11-02..2022-01-16: 19 images
submitted severity export for 2020_263245
pre 2019-11-27..2020-02-10: 44 images; post 2020-11-27..2021-02-10: 40 images
submitted severity export for 2019_410603
pre 2019-10-31..2020-01-14: 65 images; post 2020-10-31..2021-01-14: 45 images
submitted severity export for 2019_419709
pre 2020-10-26..2021-01-09: 75 images; post 2021-10-26..2022-01-09: 64 images
submitted severity export for 2020_259594
pre 2019-11-06..2020-01-20: 29 images; post 2020-11-06..2021-01-20: 20 images
submitted severity export for 2019_424251
pre 2019-10-28..2020-01-11: 20 images; post 2020-10-28..2021-01-11: 23 images
submitted severity export for 2020_217656
pre 2020-10-30..2021-01-13: 10 images; post 2021-10-30..2022-01-13: 9 images
submitted severity export for 2020_438337

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-10-14..2020-12-28: 38 images; post 2021-10-14..2021-12-28: 24 images
submitted severity export for 2021_576744
pre 2019-11-15..2020-01-29: 57 images; post 2020-11-15..2021-01-29: 47 images
submitted severity export for 2019_419995

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-03-28..2021-06-11: 30 images; post 2022-03-28..2022-06-11: 36 images
submitted severity export for 2021_302107

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-06-07..2021-08-21: 50 images; post 2022-06-07..2022-08-21: 63 images
submitted severity export for 2021_605585

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-06-18..2021-09-01: 41 images; post 2022-06-18..2022-09-01: 23 images
submitted severity export for 2021_645771
pre 2020-05-28..2020-08-11: 14 images; post 2021-05-28..2021-08-11: 20 images
submitted severity export for 2020_722362
pre 2020-05-26..2020-08-09: 41 images; post 2021-05-26..2021-08-09: 33 images
submitted severity export for 2020_700666

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-06-06..2021-08-20: 18 images; post 2022-06-06..2022-08-20: 3 images
submitted severity export for 2021_656640

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-06-10..2021-08-24: 13 images; post 2022-06-10..2022-08-24: 17 images
submitted severity export for 2021_643517
pre 2020-05-31..2020-08-14: 19 images; post 2021-05-31..2021-08-14: 16 images
submitted severity export for 2020_700821
pre 2020-06-03..2020-08-17: 29 images; post 2021-06-03..2021-08-17: 27 images
submitted severity export for 2020_532233
pre 2020-05-22..2020-08-05: 11 images; post 2021-05-22..2021-08-05: 4 images
submitted severity export for 2020_700550

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-09..2021-02-22: 14 images; post 2021-12-09..2022-02-22: 25 images
submitted severity export for 2021_732436

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-05..2021-02-18: 19 images; post 2021-12-05..2022-02-18: 33 images
submitted severity export for 2021_732468

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-08..2021-02-21: 16 images; post 2021-12-08..2022-02-21: 45 images
submitted severity export for 2021_731891

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-13..2021-02-26: 7 images; post 2021-12-13..2022-02-26: 8 images
submitted severity export for 2021_731594

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-11-21..2021-02-04: 53 images; post 2021-11-21..2022-02-04: 43 images
submitted severity export for 2021_742140
pre 2019-11-25..2020-02-08: 14 images; post 2020-11-25..2021-02-08: 16 images
submitted severity export for 2020_838361

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-08..2021-02-21: 83 images; post 2021-12-08..2022-02-21: 70 images
submitted severity export for 2021_729725

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-11-20..2021-02-03: 48 images; post 2021-11-20..2022-02-03: 43 images
submitted severity export for 2021_728841
pre 2019-12-08..2020-02-21: 101 images; post 2020-12-08..2021-02-21: 111 images
submitted severity export for 2020_822693

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-24..2021-03-09: 52 images; post 2021-12-24..2022-03-09: 44 images
submitted severity export for 2021_728758
pre 2019-12-07..2020-02-20: 44 images; post 2020-12-07..2021-02-20: 58 images
submitted severity export for 2020_819696

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-11-18..2021-02-01: 118 images; post 2021-11-18..2022-02-01: 96 images
submitted severity export for 2021_743604

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-11-29..2021-02-12: 25 images; post 2021-11-29..2022-02-12: 20 images
submitted severity export for 2021_729445

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-12-15..2021-02-28: 27 images; post 2021-12-15..2022-02-28: 22 images
submitted severity export for 2021_728617
pre 2020-01-07..2020-03-22: 16 images; post 2021-01-07..2021-03-22: 17 images
submitted severity export for 2020_13394
pre 2020-01-07..2020-03-22: 18 images; post 2021-01-07..2021-03-22: 14 images
submitted severity export for 2020_10835

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-01-26..2021-04-11: 57 images; post 2022-01-26..2022-04-11: 54 images
submitted severity export for 2021_4864
pre 2019-12-29..2020-03-13: 37 images; post 2020-12-29..2021-03-13: 21 images
submitted severity export for 2020_9374
pre 2020-01-19..2020-04-03: 8 images; post 2021-01-19..2021-04-03: 8 images
submitted severity export for 2020_11894
pre 2020-01-04..2020-03-19: 20 images; post 2021-01-04..2021-03-19: 18 images
submitted severity export for 2020_10834
pre 2020-01-17..2020-04-01: 20 images; post 2021-01-17..2021-04-01: 16 images
submitted severity export for 2020_10779
pre 2020-01-20..2020-04-04: 12 images; post 2021-01-20..2021-04-04: 13 images
submitted severity export for 2020_11971
pre 2020-01-21..2020-04-05: 23 images; post 2021-01-21..2021-04-05: 13 images
submitted severity export for 2020_9438

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-01-27..2021-04-12: 57 images; post 2022-01-27..2022-04-12: 58 images
submitted severity export for 2021_3892
pre 2020-05-14..2020-07-28: 28 images; post 2021-05-14..2021-07-28: 28 images
submitted severity export for 2020_71239
pre 2020-05-08..2020-07-22: 48 images; post 2021-05-08..2021-07-22: 49 images
submitted severity export for 2020_67755
pre 2020-08-25..2020-11-08: 18 images; post 2021-08-25..2021-11-08: 21 images
submitted severity export for 2020_137781
pre 2020-05-11..2020-07-25: 80 images; post 2021-05-11..2021-07-25: 72 images
submitted severity export for 2020_65057
pre 2020-06-06..2020-08-20: 56 images; post 2021-06-06..2021-08-20: 61 images
submitted severity export for 2020_70720

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-06-01..2021-08-15: 62 images; post 2022-06-01..2022-08-15: 51 images
submitted severity export for 2021_51822

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-07-16..2021-09-29: 79 images; post 2022-07-16..2022-09-29: 68 images
submitted severity export for 2021_41614
pre 2020-05-11..2020-07-25: 44 images; post 2021-05-11..2021-07-25: 43 images
submitted severity export for 2020_66839

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-06-05..2021-08-19: 13 images; post 2022-06-05..2022-08-19: 13 images
submitted severity export for 2021_105869

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-05-09..2021-07-23: 22 images; post 2022-05-09..2022-07-23: 21 images
submitted severity export for 2021_48631
pre 2019-10-24..2020-01-07: 25 images; post 2020-10-24..2021-01-07: 25 images
submitted severity export for 2019_268326
pre 2019-11-11..2020-01-25: 29 images; post 2020-11-11..2021-01-25: 15 images
submitted severity export for 2019_193597
pre 2019-11-06..2020-01-20: 29 images; post 2020-11-06..2021-01-20: 12 images
submitted severity export for 2020_232665
pre 2019-11-12..2020-01-26: 58 images; post 2020-11-12..2021-01-26: 60 images
submitted severity export for 2019_441028
pre 2020-11-29..2021-02-12: 29 images; post 2021-11-29..2022-02-12: 14 images
submitted severity export for 2020_449973
pre 2019-11-12..2020-01-26: 33 images; post 2020-11-12..2021-01-26: 15 images
submitted severity export for 2019_193861
pre 2019-11-06..2020-01-20: 13 images; post 2020-11-06..2021-01-20: 13 images
submitted severity export for 2019_442931
pre 2019-11-10..2020-01-24: 7 images; post 2020-11-10..2021-01-24: 7 images
submitted severity export for 2019_441257
pre 2020-12-22..2021-03-07: 14 images; post 2021-12-22..2022-03-07: 14 images
submitted severity export for 2020_460400
pre 2019-11-08..2020-01-22: 54 images; post 2020-11-08..2021-01-22: 36 images
submitted severity export for 2019_195000

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-04-08..2021-06-22: 58 images; post 2022-04-08..2022-06-22: 54 images
submitted severity export for 2021_271176
pre 2020-05-01..2020-07-15: 13 images; post 2021-05-01..2021-07-15: 14 images
submitted severity export for 2020_325873
pre 2020-05-06..2020-07-20: 56 images; post 2021-05-06..2021-07-20: 52 images
submitted severity export for 2020_354548
pre 2020-05-04..2020-07-18: 28 images; post 2021-05-04..2021-07-18: 28 images
submitted severity export for 2020_358152

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-08-12..2021-10-26: 11 images; post 2022-08-12..2022-10-26: 13 images
submitted severity export for 2021_603286
pre 2020-03-05..2020-05-19: 12 images; post 2021-03-05..2021-05-19: 10 images
submitted severity export for 2020_333817
pre 2020-05-09..2020-07-23: 8 images; post 2021-05-09..2021-07-23: 7 images
submitted severity export for 2020_302951

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-02-25..2021-05-11: 9 images; post 2022-02-25..2022-05-11: 8 images
submitted severity export for 2021_284193
pre 2020-03-19..2020-06-02: 12 images; post 2021-03-19..2021-06-02: 8 images
submitted severity export for 2020_467919

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2021-04-01..2021-06-15: 8 images; post 2022-04-01..2022-06-15: 10 images
submitted severity export for 2021_401856
pre 2019-11-15..2020-01-29: 49 images; post 2020-11-15..2021-01-29: 31 images
submitted severity export for 2020_871140
pre 2019-11-21..2020-02-04: 24 images; post 2020-11-21..2021-02-04: 10 images
submitted severity export for 2020_858340
pre 2019-12-18..2020-03-02: 62 images; post 2020-12-18..2021-03-02: 52 images
submitted severity export for 2020_834756
pre 2019-11-23..2020-02-06: 24 images; post 2020-11-23..2021-02-06: 11 images
submitted severity export for 2020_858341
pre 2019-12-16..2020-02-29: 12 images; post 2020-12-16..2021-02-28: 8 images
submitted severity export for 2020_830179
pre 2019-12-20..2020-03-04: 26 images; post 2020-12-20..2021-03-04: 24 images
submitted severity export for 2020_839832
pre 2019-12-22..2020-03-06: 45 images; post 2020-12-22..2021-03-06: 37 images
submitted severity export for 2020_832636
pre 2019-12-29..2020-03-13: 25 images; post 2020-12-29..2021-03-13: 20 images
submitted severity export for 2020_833726
pre 2019-12-11..2020-02-24: 53 images; post 2020-12-11..2021-02-24: 52 images
submitted severity export for 2020_831248
pre 2019-12-01..2020-02-14: 49 images; post 2020-12-01..2021-02-14: 37 images
submitted severity export for 2020_857759
pre 2019-10-28..2020-01-11: 35 images; post 2020-10-28..2021-01-11: 32 images
submitted severity export for 2020_880556
pre 2019-10-21..2020-01-04: 17 images; post 2020-10-21..2021-01-04: 8 images
submitted severity export for 2019_873717

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

pre 2020-09-03..2020-11-17: 7 images; post 2021-09-03..2021-11-17: 13 images
submitted severity export for 2021_766525
pre 2019-11-22..2020-02-05: 19 images; post 2020-11-22..2021-02-05: 9 images
submitted severity export for 2019_873471
pre 2019-10-06..2019-12-20: 61 images; post 2020-10-06..2020-12-20: 34 images
submitted severity export for 2020_880548
pre 2019-10-14..2019-12-28: 36 images; post 2020-10-14..2020-12-28: 15 images
submitted severity export for 2019_873714
pre 2019-10-25..2020-01-08: 15 images; post 2020-10-25..2021-01-08: 7 images
submitted severity export for 2019_873720
pre 2019-10-20..2020-01-03: 22 images; post 2020-10-20..2021-01-03: 9 images
submitted severity export for 2019_873593
pre 2019-12-13..2020-02-26: 11 images; post 2020-12-13..2021-02-26: 3 images
submitted severity export for 2020_877292
pre 2019-10-25..2020-01-08: 38 images; post 2020-10-25..2021-01-08: 26 images
submitted severity export for 2020_880433

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_18444.tif...
/ [1 files][ 18.5 MiB/ 18.5 MiB]
Operation completed over 1 objects/18.5 MiB.

2020_18444: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_4073.tif...
/ [1 files][ 19.4 MiB/ 19.4 MiB]
Operation completed over 1 objects/19.4 MiB.

2020_4073: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_4466.tif...
/ [1 files][ 22.3 MiB/ 22.3 MiB]
Operation completed over 1 objects/22.3 MiB.

2021_4466: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_4403.tif...
/ [1 files][ 16.8 MiB/ 16.8 MiB]
Operation completed over 1 objects/16.8 MiB.

2020_4403: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_4159.tif...
/ [1 files][ 19.7 MiB/ 19.7 MiB]
Operation completed over 1 objects/19.7 MiB.

2020_4159: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_2313.tif...
/ [1 files][ 16.1 MiB/ 16.1 MiB]
Operation completed over 1 objects/16.1 MiB.

2020_2313: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_2474.tif...
/ [1 files][ 20.9 MiB/ 20.9 MiB]
Operation completed over 1 objects/20.9 MiB.

2021_2474: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_5536.tif...
- [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.

2021_5536: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_1512.tif...
/ [1 files][ 20.7 MiB/ 20.7 MiB]
Operation completed over 1 objects/20.7 MiB.

2021_1512: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_54726.tif...
- [1 files][ 54.6 MiB/ 54.6 MiB]
Operation completed over 1 objects/54.6 MiB.

2021_54726: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_73351.tif...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.

2020_73351: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_72488.tif...
- [1 files][ 27.2 MiB/ 27.2 MiB]
Operation completed over 1 objects/27.2 MiB.

2020_72488: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_61506.tif...
/ [1 files][ 17.9 MiB/ 17.9 MiB]
Operation completed over 1 objects/17.9 MiB.

2020_61506: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_57075.tif...
/ [1 files][ 22.8 MiB/ 22.8 MiB]
Operation completed over 1 objects/22.8 MiB.

2021_57075: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_57082.tif...
/ [1 files][ 16.6 MiB/ 16.6 MiB]
Operation completed over 1 objects/16.6 MiB.

2021_57082: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_75388.tif...
- [1 files][ 16.9 MiB/ 16.9 MiB]
Operation completed over 1 objects/16.9 MiB.

2020_75388: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_58633.tif...
/ [1 files][ 19.7 MiB/ 19.7 MiB]
Operation completed over 1 objects/19.7 MiB.

2021_58633: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_249284.tif...
/ [1 files][ 17.4 MiB/ 17.4 MiB]
Operation completed over 1 objects/17.4 MiB.

2019_249284: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_263245.tif...
/ [1 files][ 18.3 MiB/ 18.3 MiB]
Operation completed over 1 objects/18.3 MiB.

2020_263245: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_410603.tif...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.

2019_410603: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_419709.tif...
/ [1 files][ 17.9 MiB/ 17.9 MiB]
Operation completed over 1 objects/17.9 MiB.

2019_419709: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_259594.tif...
- [1 files][ 20.7 MiB/ 20.7 MiB]
Operation completed over 1 objects/20.7 MiB.

2020_259594: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_424251.tif...
/ [1 files][ 17.6 MiB/ 17.6 MiB]
Operation completed over 1 objects/17.6 MiB.

2019_424251: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_438337.tif...
/ [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

2020_438337: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_217656.tif...
/ [1 files][ 23.0 MiB/ 23.0 MiB]
Operation completed over 1 objects/23.0 MiB.

2020_217656: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_419995.tif...
/ [1 files][ 16.8 MiB/ 16.8 MiB]
Operation completed over 1 objects/16.8 MiB.

2019_419995: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_302107.tif...
/ [1 files][ 18.4 MiB/ 18.4 MiB]
Operation completed over 1 objects/18.4 MiB.

2021_302107: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_605585.tif...
- [1 files][ 30.9 MiB/ 30.9 MiB]
Operation completed over 1 objects/30.9 MiB.

2021_605585: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_576744.tif...
- [1 files][ 28.5 MiB/ 28.5 MiB]
Operation completed over 1 objects/28.5 MiB.

2021_576744: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_645771.tif...
/ [1 files][ 16.7 MiB/ 16.7 MiB]
Operation completed over 1 objects/16.7 MiB.

2021_645771: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_722362.tif...
/ [1 files][ 17.3 MiB/ 17.3 MiB]
Operation completed over 1 objects/17.3 MiB.

2020_722362: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_656640.tif...
/ [1 files][ 19.1 MiB/ 19.1 MiB]
Operation completed over 1 objects/19.1 MiB.

2021_656640: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_700666.tif...
- [1 files][ 22.0 MiB/ 22.0 MiB]
Operation completed over 1 objects/22.0 MiB.

2020_700666: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_700821.tif...
/ [1 files][ 16.7 MiB/ 16.7 MiB]
Operation completed over 1 objects/16.7 MiB.

2020_700821: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_643517.tif...
/ [1 files][ 22.6 MiB/ 22.6 MiB]
Operation completed over 1 objects/22.6 MiB.

2021_643517: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_700550.tif...
/ [1 files][ 16.7 MiB/ 16.7 MiB]
Operation completed over 1 objects/16.7 MiB.

2020_700550: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_732436.tif...
/ [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.

2021_732436: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_532233.tif...
/ [1 files][ 18.1 MiB/ 18.1 MiB]
Operation completed over 1 objects/18.1 MiB.

2020_532233: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_732468.tif...
- [1 files][ 42.6 MiB/ 42.6 MiB]
Operation completed over 1 objects/42.6 MiB.

2021_732468: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_731891.tif...
/ [1 files][ 26.8 MiB/ 26.8 MiB]
Operation completed over 1 objects/26.8 MiB.

2021_731891: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_731594.tif...
/ [1 files][ 18.8 MiB/ 18.8 MiB]
Operation completed over 1 objects/18.8 MiB.

2021_731594: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_838361.tif...
/ [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.

2020_838361: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_728841.tif...
/ [1 files][ 18.1 MiB/ 18.1 MiB]
Operation completed over 1 objects/18.1 MiB.

2021_728841: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_729725.tif...
/ [1 files][ 22.2 MiB/ 22.2 MiB]
Operation completed over 1 objects/22.2 MiB.

2021_729725: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_742140.tif...
/ [1 files][ 24.9 MiB/ 24.9 MiB]
Operation completed over 1 objects/24.9 MiB.

2021_742140: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_822693.tif...
/ [1 files][ 31.2 MiB/ 31.2 MiB]
Operation completed over 1 objects/31.2 MiB.

2020_822693: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_728758.tif...
/ [1 files][ 24.2 MiB/ 24.2 MiB]
Operation completed over 1 objects/24.2 MiB.

2021_728758: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_729445.tif...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.

2021_729445: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_13394.tif...
/ [1 files][ 16.8 MiB/ 16.8 MiB]
Operation completed over 1 objects/16.8 MiB.

2020_13394: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_10835.tif...
/ [1 files][ 18.8 MiB/ 18.8 MiB]
Operation completed over 1 objects/18.8 MiB.

2020_10835: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_819696.tif...
/ [1 files][ 16.6 MiB/ 16.6 MiB]
Operation completed over 1 objects/16.6 MiB.

2020_819696: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_728617.tif...
/ [1 files][ 17.3 MiB/ 17.3 MiB]
Operation completed over 1 objects/17.3 MiB.

2021_728617: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_4864.tif...
/ [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.

2021_4864: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_743604.tif...
/ [1 files][ 16.7 MiB/ 16.7 MiB]
Operation completed over 1 objects/16.7 MiB.

2021_743604: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_9374.tif...
/ [1 files][ 16.7 MiB/ 16.7 MiB]
Operation completed over 1 objects/16.7 MiB.

2020_9374: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_11894.tif...
/ [1 files][ 20.6 MiB/ 20.6 MiB]
Operation completed over 1 objects/20.6 MiB.

2020_11894: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_10834.tif...
/ [1 files][ 17.7 MiB/ 17.7 MiB]
Operation completed over 1 objects/17.7 MiB.

2020_10834: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_10779.tif...
/ [1 files][ 16.8 MiB/ 16.8 MiB]
Operation completed over 1 objects/16.8 MiB.

2020_10779: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_11971.tif...
/ [1 files][ 19.9 MiB/ 19.9 MiB]
Operation completed over 1 objects/19.9 MiB.

2020_11971: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_9438.tif...
- [1 files][ 23.2 MiB/ 23.2 MiB]
Operation completed over 1 objects/23.2 MiB.

2020_9438: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_71239.tif...
/ [1 files][ 16.3 MiB/ 16.3 MiB]
Operation completed over 1 objects/16.3 MiB.

2020_71239: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_67755.tif...
/ [1 files][ 18.0 MiB/ 18.0 MiB]
Operation completed over 1 objects/18.0 MiB.

2020_67755: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_3892.tif...
/ [1 files][ 17.4 MiB/ 17.4 MiB]
Operation completed over 1 objects/17.4 MiB.

2021_3892: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_137781.tif...
/ [1 files][ 20.1 MiB/ 20.1 MiB]
Operation completed over 1 objects/20.1 MiB.

2020_137781: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_65057.tif...
/ [1 files][ 21.6 MiB/ 21.6 MiB]
Operation completed over 1 objects/21.6 MiB.

2020_65057: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_70720.tif...
/ [1 files][ 21.6 MiB/ 21.6 MiB]
Operation completed over 1 objects/21.6 MiB.

2020_70720: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_51822.tif...
/ [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.

2021_51822: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_105869.tif...
/ [1 files][ 18.6 MiB/ 18.6 MiB]
Operation completed over 1 objects/18.6 MiB.

2021_105869: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_48631.tif...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.

2021_48631: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_41614.tif...
/ [1 files][ 17.3 MiB/ 17.3 MiB]
Operation completed over 1 objects/17.3 MiB.

2021_41614: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_66839.tif...
/ [1 files][ 17.4 MiB/ 17.4 MiB]
Operation completed over 1 objects/17.4 MiB.

2020_66839: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_268326.tif...
/ [1 files][ 20.6 MiB/ 20.6 MiB]
Operation completed over 1 objects/20.6 MiB.

2019_268326: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_441028.tif...
/ [1 files][ 20.4 MiB/ 20.4 MiB]
Operation completed over 1 objects/20.4 MiB.

2019_441028: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_449973.tif...
/ [1 files][ 19.6 MiB/ 19.6 MiB]
Operation completed over 1 objects/19.6 MiB.

2020_449973: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_193861.tif...
/ [1 files][ 16.4 MiB/ 16.4 MiB]
Operation completed over 1 objects/16.4 MiB.

2019_193861: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_442931.tif...
/ [1 files][ 17.0 MiB/ 17.0 MiB]
Operation completed over 1 objects/17.0 MiB.

2019_442931: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_232665.tif...
- [1 files][ 31.9 MiB/ 31.9 MiB]
Operation completed over 1 objects/31.9 MiB.

2020_232665: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_441257.tif...
/ [1 files][ 17.3 MiB/ 17.3 MiB]
Operation completed over 1 objects/17.3 MiB.

2019_441257: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_460400.tif...
/ [1 files][ 21.2 MiB/ 21.2 MiB]
Operation completed over 1 objects/21.2 MiB.

2020_460400: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_271176.tif...
/ [1 files][ 17.8 MiB/ 17.8 MiB]
Operation completed over 1 objects/17.8 MiB.

2021_271176: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_325873.tif...
/ [1 files][ 17.4 MiB/ 17.4 MiB]
Operation completed over 1 objects/17.4 MiB.

2020_325873: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_354548.tif...
/ [1 files][ 17.1 MiB/ 17.1 MiB]
Operation completed over 1 objects/17.1 MiB.

2020_354548: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_195000.tif...
- [1 files][ 24.1 MiB/ 24.1 MiB]
Operation completed over 1 objects/24.1 MiB.

2019_195000: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_193597.tif...
- [1 files][ 22.9 MiB/ 22.9 MiB]
Operation completed over 1 objects/22.9 MiB.

2019_193597: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_603286.tif...
- [1 files][ 16.7 MiB/ 16.7 MiB]
Operation completed over 1 objects/16.7 MiB.

2021_603286: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_333817.tif...
- [1 files][ 16.9 MiB/ 16.9 MiB]
Operation completed over 1 objects/16.9 MiB.

2020_333817: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_358152.tif...
/ [1 files][ 19.7 MiB/ 19.7 MiB]
Operation completed over 1 objects/19.7 MiB.

2020_358152: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_284193.tif...
/ [1 files][ 17.0 MiB/ 17.0 MiB]
Operation completed over 1 objects/17.0 MiB.

2021_284193: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_467919.tif...
- [1 files][ 21.1 MiB/ 21.1 MiB]
Operation completed over 1 objects/21.1 MiB.

2020_467919: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2021_401856.tif...
- [1 files][ 19.3 MiB/ 19.3 MiB]
Operation completed over 1 objects/19.3 MiB.

2021_401856: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_302951.tif...
/ [1 files][ 19.7 MiB/ 19.7 MiB]
Operation completed over 1 objects/19.7 MiB.

2020_302951: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_858340.tif...
/ [1 files][ 16.7 MiB/ 16.7 MiB]
Operation completed over 1 objects/16.7 MiB.

2020_858340: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_834756.tif...
/ [1 files][ 19.4 MiB/ 19.4 MiB]
Operation completed over 1 objects/19.4 MiB.

2020_834756: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_858341.tif...
/ [1 files][ 17.4 MiB/ 17.4 MiB]
Operation completed over 1 objects/17.4 MiB.

2020_858341: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_871140.tif...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.

2020_871140: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_830179.tif...
/ [1 files][ 18.2 MiB/ 18.2 MiB]
Operation completed over 1 objects/18.2 MiB.

2020_830179: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_839832.tif...
/ [1 files][ 17.6 MiB/ 17.6 MiB]
Operation completed over 1 objects/17.6 MiB.

2020_839832: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_832636.tif...
/ [1 files][ 19.0 MiB/ 19.0 MiB]
Operation completed over 1 objects/19.0 MiB.

2020_832636: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_857759.tif...
/ [1 files][ 20.3 MiB/ 20.3 MiB]
Operation completed over 1 objects/20.3 MiB.

2020_857759: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_880556.tif...
- [1 files][ 29.9 MiB/ 29.9 MiB]
Operation completed over 1 objects/29.9 MiB.

2020_880556: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_831248.tif...
/ [1 files][ 20.5 MiB/ 20.5 MiB]
Operation completed over 1 objects/20.5 MiB.

2020_831248: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_873717.tif...
/ [1 files][ 19.4 MiB/ 19.4 MiB]
Operation completed over 1 objects/19.4 MiB.

2019_873717: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_873714.tif...
/ [1 files][ 19.9 MiB/ 19.9 MiB]
Operation completed over 1 objects/19.9 MiB.

2019_873714: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2019_873593.tif...
/ [1 files][ 20.6 MiB/ 20.6 MiB]
Operation completed over 1 objects/20.6 MiB.

2019_873593: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_877292.tif...
/ [1 files][ 18.7 MiB/ 18.7 MiB]
Operation completed over 1 objects/18.7 MiB.

2020_877292: severity ready

Copying gs://tree-fire-510209-data/fire-impact-curves/data/severity/severity_2020_880433.tif...
/ [1 files][ 24.4 MiB/ 24.4 MiB]
Operation completed over 1 objects/24.4 MiB.

2020_880433: severity ready
running 2020_18444
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/48bca156d985eeedaa7153795bf83ad4-77e389c5555574e46b7226cf8c67a30d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_18444_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7ccff7f0f8a87b1e27d20f984b68369e-a51059ec7ed8bf09b8d91dfe4e54d7a1:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_18444_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/4bdfa06046cb2ace8eeb0692d6c913f8-88af57ee455f1bfebf96058ac30b883b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_18444_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_18444.tif...
/ [1 files][ 41.7 KiB/ 41.7 KiB]
Operation completed over 1 objects/41.7 KiB.

2020_18444 done: 0 cells
running 2020_4073
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2b7da863495f445bad10fc4b8c796ee8-48617bc6b219d9939c5abbcd03793d06:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4073_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e512a572dae0ae766f03cfedd95e14f9-cc9dee0d6b9ada7adb7b40eb121fa778:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4073_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/4b77bef0fb24cc05bf887f1c03096598-7c78da61461bf6b6b30ecfc4f9b4b32b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4073_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_4073.tif...
/ [1 files][ 73.9 KiB/ 73.9 KiB]
Operation completed over 1 objects/73.9 KiB.

2020_4073 done: 237 cells
running 2021_4466

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ed41987deb97ac4f06669a4919aa8eac-ad63d52e34165bbdd86dfe443b3f9809:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_4466_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c47fbe9af88f9550ce52bb7506e636f7-3ea741e00e614a0dd529b4bbc32c948e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_4466_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_4466.tif...
/ [1 files][ 88.6 KiB/ 88.6 KiB]
Operation completed over 1 objects/88.6 KiB.

2021_4466 done: 72 cells
running 2020_4403
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e9efd4bfc116914250e4bc82c569e69f-639f69994182116102ba3628faf326f9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4403_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b3babc6d6ebf63be5d3962af236eba97-823e2b40e6dcc7182f6e4e3c803aa62d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4403_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7e64fc6e19c6cc2cb7b9973b99495752-be06635bd2278c3842fabafcabc8699d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4403_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_4403.tif...
/ [1 files][ 69.3 KiB/ 69.3 KiB]
Operation completed over 1 objects/69.3 KiB.

2020_4403 done: 183 cells
running 2020_4159
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1b0ec3861fb2f5c38d0baf3769047795-1b34a1419fc3e1569bbf9527dcbb4d86:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4159_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8a1aeb7c7214919d3f210ed80485fe3d-08279741541514db93ac4a625eb14f14:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4159_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ee4fbbf1208c3a2c056914f440b8700a-ed33a27ecbf8558267e27e89506c8c7b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_4159_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_4159.tif...
/ [1 files][ 67.6 KiB/ 67.6 KiB]
Operation completed over 1 objects/67.6 KiB.

2020_4159 done: 8 cells
running 2020_2313
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b401b52a09ab3d0c7cfe6b57ba800f3b-d204ca52c6b503ea12b44f6cde56d4f2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_2313_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/66637f67311ad23e25cab912de971de4-ed62f7a0fb3556e723b91cb12b27b76d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_2313_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b8bacda0d50ffb5d2a62965e2c465211-3fd98953f5452e7abbaa140c9c0a93b9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_2313_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_2313.tif...
/ [1 files][ 65.4 KiB/ 65.4 KiB]
Operation completed over 1 objects/65.4 KiB.
Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_54726.tif...
/ [1 files][ 95.9 KiB/ 95.9 KiB]
Operation completed over 1 objects/95.9 KiB.

2021_54726 done: 4944 cells
running 2020_73351
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/bb07b93e2f5de1b4f6de89704b585423-0255d3cf0aff56c6f1b9466c397dc19b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_73351_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9af3f2480ae9c896089f0eeb3a525b60-8c3408448bfb239bbfdcdda707de679d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_73351_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e94120b702dd00ba524f30047aa162d7-01d8aa32d2629db4e171d563dd18a52e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_73351_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_73351.tif...
/ [1 files][ 39.9 KiB/ 39.9 KiB]
Operation completed over 1 objects/39.9 KiB.

2020_73351 done: 138 cells
running 2020_86085
2020_86085 FAILED: expected exactly one match for uid '2020_86085' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2
running 2020_77169
2020_77169 FAILED: expected exactly one match for uid '2020_77169' in ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2020.shp, got 2
running 2020_72488
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ba1943e8b8658f326109217f7d0e10f5-07daf49e26d83599676b148bc15afa6c:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_72488_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c1b4a14c8a135b821b5cd0b5448fe765-e4884193858b15afa86ba79f061665d9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_72488_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e255688928aa2f17c030fa2dd296f007-4e490ab7f4f72078afbd10c82004aa0d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_72488_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_72488.tif...
/ [1 files][ 46.8 KiB/ 46.8 KiB]
Operation completed over 1 objects/46.8 KiB.

2020_72488 done: 2752 cells
running 2020_61506
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/16c7c41236f5368a9e95f3228f231818-67d11c757ca6cc342e584242b144d823:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_61506_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f80ad5dd0f4c6479154de0225e0c7b95-af3270f97515868272849e56bf2e0085:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_61506_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c21cd7797998ab879e1f4be8aeec26d3-87b96f16b8c10c1397c8d28776748b97:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_61506_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_61506.tif...
/ [1 files][ 48.6 KiB/ 48.6 KiB]
Operation completed over 1 objects/48.6 KiB.

2020_61506 done: 109 cells
running 2021_57075

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/5dd6aa40bcbfe84f5f58760e473ea31c-2516a9a1e9c6e68a2ba775f928ca7f0a:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_57075_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/5e0f451741199f6f8a4e7e86490c5ec2-19cdd36ee4503b8b46352b336478773f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_57075_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_57075.tif...
/ [1 files][ 55.7 KiB/ 55.7 KiB]
Operation completed over 1 objects/55.7 KiB.

2021_57075 done: 926 cells
running 2021_57082

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/be4bfba712d62f6b571fdce45e53bce6-9c7711a6f68b7070486914f25f2be481:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_57082_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b3f367f7b522bc6cd60f9e4d64cc1261-14b4deec2ff34a049a7053f9fbedda10:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_57082_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_57082.tif...
/ [1 files][ 48.2 KiB/ 48.2 KiB]
Operation completed over 1 objects/48.2 KiB.

2021_57082 done: 44 cells
running 2020_75388
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/fe5f43589b8d3f20a770b8297a2ebda7-84555b8bf2bd88e57f7ce3de4dc7d82f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_75388_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e0fabcd66f541e53613237bef561e8c9-0855a2f12b8f941bed1c3b943835676f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_75388_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/904af7455bf87dc2c340120399a55acf-4c3a26da312273c12c6316248b629aab:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_75388_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_75388.tif...
/ [1 files][ 38.7 KiB/ 38.7 KiB]
Operation completed over 1 objects/38.7 KiB.

2020_75388 done: 12 cells
running 2021_58633

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/5e3d303af1ef1032faee1d577beb8286-320e73d6666183c7b9873a53b6de16c8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_58633_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7777f846361ed6eef711f694ab9ec86f-a5acabd9b0bc71a0804c8a7f5f2fecbc:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_58633_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_58633.tif...
/ [1 files][ 54.0 KiB/ 54.0 KiB]
Operation completed over 1 objects/54.0 KiB.

2021_58633 done: 30 cells
running 2019_249284
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/cebb79a1ba69a4a6099649cc562ff393-5a3eec3d88f08057b656585cbc153dc2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_249284_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0f3e7520512a95851537ff11beff95dc-74eda3576249411ab71d0b7358ec5924:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_249284_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d61cbda615b1605eac4dbb62a91b8819-c09d090bcc698af5f77090877c553517:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_249284_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_249284.tif...
/ [1 files][ 59.7 KiB/ 59.7 KiB]
Operation completed over 1 objects/59.7 KiB.

2019_249284 done: 3 cells
running 2020_263245
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2bc90ace642edbc7db11916b385bae4f-2db1163c4f72fdd6599c4b99e252bbda:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_263245_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f26e7ae48770b52c275ec7e25e349dd4-025d6e17c04265bc1d609a78aff50dcf:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_263245_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_263245.tif...
/ [1 files][ 45.0 KiB/ 45.0 KiB]
Operation completed over 1 objects/45.0 KiB.

2020_263245 done: 1 cells
running 2019_410603
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9e4ed79d024c1f16b0cb0d8d3574dab8-17bf13f64dafe20cda1f5b247e298169:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_410603_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8fe7c6fd7ba225a741a867c7b77c9f7a-c755259f276230fbdf06cf296df76856:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_410603_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/66a60d09247a50d0c112037ac96e088f-140a3c5797ada868cda6bf7d5709659a:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_410603_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_410603.tif...
/ [1 files][ 64.4 KiB/ 64.4 KiB]
Operation completed over 1 objects/64.4 KiB.

2019_410603 done: 6 cells
running 2019_419709
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/cdb066f295ff334321d0b1402c1a9ea0-37a46e2f243e6ad51390564a4d0604f0:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_419709_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/14b3286406c5c15b5bbdce50a2541902-3a5a9e3fdf703069630d99663b80c683:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_419709_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9a1cb5685b7c249b3ea716e17483d88b-00bc8e71f23dc85150d7bb1d4d9e9676:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_419709_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_419709.tif...
/ [1 files][ 47.8 KiB/ 47.8 KiB]
Operation completed over 1 objects/47.8 KiB.

2019_419709 done: 0 cells
running 2020_259594
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/96529c5d90963e460bca739eb1192148-7e3a98b3534e24461d47ff04a9a328a5:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_259594_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/00360c5662db77b3141b376a59190c2b-4eb86e1daa9a11766d985315ffba12cf:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_259594_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_259594.tif...
/ [1 files][ 66.9 KiB/ 66.9 KiB]
Operation completed over 1 objects/66.9 KiB.

2020_259594 done: 220 cells
running 2019_424251
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/115a73f14f226d6e3f235e263507c267-db3b5b0c2b2c6a8d1547fd7a9cd638a3:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_424251_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/5b43a30c2f224c9409b7958aade9394e-53a4b46905cb7ccbe247f6d994d03e03:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_424251_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/4b550958927e9270042e7e0f338a356b-4e820eaa8cece2040a764c4ee0880371:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_424251_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_424251.tif...
/ [1 files][ 45.1 KiB/ 45.1 KiB]
Operation completed over 1 objects/45.1 KiB.

2019_424251 done: 4 cells
running 2020_217656
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/345dc85dcfd7d17846b23ce7db6175eb-bd3aa480be6fa07bf7f8e294e6ec65fe:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_217656_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/61dc96b4d3599663093d4f78b529a541-e15464ef62965a4301f379845c1ae2e9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_217656_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2607f67d6da232a97012e83307f07c6a-372780717e36faa0e28069af7c93c3a8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_217656_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_217656.tif...
/ [1 files][ 66.7 KiB/ 66.7 KiB]
Operation completed over 1 objects/66.7 KiB.

2020_217656 done: 220 cells
running 2020_438337
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/423a96ef6b5d5842b19b6261378d2a4b-dc92e233e077992e48cb42f0ad663c0f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_438337_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/3944f6104640f866a45a8d127f4e182f-f4f93a783309edee1a0221e1c34f258a:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_438337_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_438337.tif...
/ [1 files][ 60.7 KiB/ 60.7 KiB]
Operation completed over 1 objects/60.7 KiB.

2020_438337 done: 0 cells
running 2021_576744

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/040b6ad6cfb8fd0679c7c3274bc396df-5dcf1ea73ed4ecb6c1294c15d42ea906:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_576744_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f880d07a3188746dfc3f649481b04818-ca71f5f81159c20d5be17e8d3e52b3c4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_576744_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_576744.tif...
/ [1 files][ 81.1 KiB/ 81.1 KiB]
Operation completed over 1 objects/81.1 KiB.

2021_576744 done: 20 cells
running 2019_419995
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/627f060f55f2277d3d94ed7b2a80ba82-d12ef57da1d2c005a96d7f633a0511bf:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_419995_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/58a3ec87229c704599b1cc83fae05218-4619539a8a4702e8f77b28b8b9d52fa3:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_419995_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ccff0789dbbce6bae0fc6eb8d7ffa796-a133be717282c5dfbabccaa1431256df:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_419995_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_419995.tif...
/ [1 files][ 37.9 KiB/ 37.9 KiB]
Operation completed over 1 objects/37.9 KiB.

2019_419995 done: 0 cells
running 2021_302107

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7850de4557b08c97a6453736c38a677f-679c73893fd57cc7670cf581f9732769:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_302107_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/703dde0808a1e963974023e64e51dab4-ff042ddc70318d26c25188500d85ea84:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_302107_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_302107.tif...
/ [1 files][ 58.5 KiB/ 58.5 KiB]
Operation completed over 1 objects/58.5 KiB.

2021_302107 done: 0 cells
running 2021_605585

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/4e66937fd261e7843ebb2263baa1334c-87000f66c6a94a4d94498bd90dc146f7:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_605585_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/601e8d61b33979cd067356617e0cebe8-aa041a40807a7ae5e9648c0fb0a216b3:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_605585_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_605585.tif...
/ [1 files][ 92.7 KiB/ 92.7 KiB]
Operation completed over 1 objects/92.7 KiB.

2021_605585 done: 4 cells
running 2021_645771

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0d90718a6635545b68c3a08b9c21a117-4f79c51dc963cc832d78fb0fe1e78dc2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_645771_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/954fd5890df6a28db2c652e0fbb2fdea-6b5681abda691852407e581561e80735:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_645771_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_645771.tif...
/ [1 files][ 51.0 KiB/ 51.0 KiB]
Operation completed over 1 objects/51.0 KiB.

2021_645771 done: 0 cells
running 2020_722362
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7fed021ec82208d551e358de70dc460e-521a488acaa441a1e6669dff5e801f06:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_722362_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/573db152838a1b7832ccb49b43e5dfa4-8cecd4d9d2af6d35f7a2127afee2d5c5:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_722362_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8853c9b20eec4fa5a8bf273808b92335-0e483af32e6e6586ac06c0797d408cfd:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_722362_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_722362.tif...
/ [1 files][ 66.8 KiB/ 66.8 KiB]
Operation completed over 1 objects/66.8 KiB.

2020_722362 done: 77 cells
running 2020_700666
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e7443a04549f281282f14ff7d10dd5b8-ce204909e517617dc068ee71141bc937:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700666_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/07f62a926277be42a054f254ac139acb-d29a62ff7ad274dac028923e1022c0a2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700666_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8dd5db38717f02c55af60f86a2270882-cf79b5543637a55dc571dab5a0f6aace:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700666_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_700666.tif...
/ [1 files][ 66.4 KiB/ 66.4 KiB]
Operation completed over 1 objects/66.4 KiB.

2020_700666 done: 28 cells
running 2021_656640

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e18add09320199164b71134707f3da99-febf4ad85c288cbbc587746635807d53:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_656640_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/da996287840c15f503879dd72e682f92-9f02f2b7476292a09d75470a1af1c5fc:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_656640_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_656640.tif...
/ [1 files][ 76.4 KiB/ 76.4 KiB]
Operation completed over 1 objects/76.4 KiB.

2021_656640 done: 1372 cells
running 2021_643517

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/bb550a981d7fac794b77c4a0ef7659ca-466af28b127d8b5e1e3f087434320bb2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_643517_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/13975c639ff5f2ea66e520dd62ff50e8-af82480a4ec75df8d8cee3070c4a536b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_643517_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_643517.tif...
/ [1 files][ 54.5 KiB/ 54.5 KiB]
Operation completed over 1 objects/54.5 KiB.

2021_643517 done: 103 cells
running 2020_700821
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6eedf5c0a8ca93863bb6610f28409b7b-64005387ebb34cb3ce42bfb3f4723ccf:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700821_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/57a462cd9217b8710b40eb16e26ee514-1dd440a44c842ea68716c950ae094777:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700821_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/dfae4ee2fa5e05d03933260219f6a820-10acf63eec518f26e71103682b9ff1d8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700821_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_700821.tif...
/ [1 files][ 22.7 KiB/ 22.7 KiB]
Operation completed over 1 objects/22.7 KiB.

2020_700821 done: 5 cells
running 2020_532233
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/fc7fef5e66145e2c9217faa02d1e709a-d9dda63e5195bc679f6786544e0db23b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_532233_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e79f70885419469d9a4ca99d06904dab-98dd9597cad0aedb3b075555143b0409:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_532233_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f81a36eee4fba690d3e650711a44c42d-3166e173fd0e405d9df9327e083d9c7f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_532233_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_532233.tif...
/ [1 files][ 39.0 KiB/ 39.0 KiB]
Operation completed over 1 objects/39.0 KiB.

2020_532233 done: 19 cells
running 2020_700550
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/3af633cb63bc5aa2966163cfeeab4d25-d7e6921b26ed63cd58484b61542ca37a:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700550_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ef2111d1322d6c50d46c5fd511293e6e-46caf87b48fdad0057493a412f918a33:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700550_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/cc322ba17744019fea113f9c20ddf23c-d3b44209ba653d339d59d7a1bf50c97e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_700550_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_700550.tif...
/ [1 files][ 60.6 KiB/ 60.6 KiB]
Operation completed over 1 objects/60.6 KiB.

2020_700550 done: 9 cells
running 2021_732436

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/463352dc0502881dd2b1b535521960f4-607041d46a1b8e8d568c0eb91319e7e2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_732436_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d11d7ad976a8f0e89e10a5b8cf811fa7-7404afee4000ebdff68be6750dd219ba:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_732436_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_732436.tif...
/ [1 files][ 54.8 KiB/ 54.8 KiB]
Operation completed over 1 objects/54.8 KiB.

2021_732436 done: 0 cells
running 2021_732468

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/82203d29c2379a91e9acb4b970e5ad34-be2fc99b82b48ed4d1c62f4d635b02ef:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_732468_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8bf15ba73a039c6fd161c8e994a988ae-f96d3277569797354265aeb52884234b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_732468_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_732468.tif...
/ [1 files][ 96.1 KiB/ 96.1 KiB]
Operation completed over 1 objects/96.1 KiB.

2021_732468 done: 0 cells
running 2021_731891

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/3f52603dd1b60fc44f5ef31787a6e99e-557430a38070b586201b6f94df63e39b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_731891_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/80e9c5503786f9f91b1af53c4928453b-730a7a73201d8345b488ebaf987137e9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_731891_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_731891.tif...
/ [1 files][ 92.2 KiB/ 92.2 KiB]
Operation completed over 1 objects/92.2 KiB.

2021_731891 done: 5 cells
running 2021_731594

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/cc4831165ce9d11672eef0e8da5ce13b-44e7e0dd21bf9cf82ce30c8e5a6346ef:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_731594_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/fcc8d177c028ba0f0d093df638a15bf1-97ab48a1967d2db5f016c0e9ac6174e5:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_731594_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_731594.tif...
/ [1 files][ 65.5 KiB/ 65.5 KiB]
Operation completed over 1 objects/65.5 KiB.

2021_731594 done: 0 cells
running 2021_742140

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/49d4492b05269aa144f6ce4ed13adcf6-1827dfd86857a7c371b2d7be2ceb2430:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_742140_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7c0ddcf82f1951dc571b0fed0afb50f0-64a62f9f31933b54b88318ed1ba58ff4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_742140_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_742140.tif...
/ [1 files][ 97.6 KiB/ 97.6 KiB]
Operation completed over 1 objects/97.6 KiB.

2021_742140 done: 2 cells
running 2020_838361
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b103dfd391f3c2686a9ffc4bad1a42fd-a4ce085cff27e5da278b73acd74c89c4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_838361_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6195c956662857af4382a5a9ce231e90-c2b6c3ceceb57e7953d6978781d346e8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_838361_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/812eb4f12b6b57708e40a5dbf7dc0573-462aa213fec0471b60ec42433c846f7e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_838361_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_838361.tif...
/ [1 files][ 52.4 KiB/ 52.4 KiB]
Operation completed over 1 objects/52.4 KiB.

2020_838361 done: 1141 cells
running 2021_729725

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f4ec27aa0f7909902998ee5d8a50ca0f-137b7f70e337b4a3f99e8a1e55bafe2b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_729725_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c6b57bc67c3cb82522fe646eb44ead60-7a0ed89f40f2d604ef44367b7a51f79b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_729725_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_729725.tif...
/ [1 files][ 44.3 KiB/ 44.3 KiB]
Operation completed over 1 objects/44.3 KiB.

2021_729725 done: 289 cells
running 2021_728841

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0715e4591202d1568b9747e251745bd5-869f7b1084494b8228589659990c9517:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_728841_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d2e204e72ce7fe9a95665d013f71ee9b-25145d7e5694cf98ff7eeec86d789ae7:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_728841_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_728841.tif...
/ [1 files][ 51.3 KiB/ 51.3 KiB]
Operation completed over 1 objects/51.3 KiB.

2021_728841 done: 65 cells
running 2020_822693
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2be66a2727dd5bd3a1a43f7a073e0960-86ae7c99a1a1a7e60224a25cf656dfbd:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_822693_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e319a8d58d53050b56e3e4a99f2dfe7c-85c618007fc5876f2e169dc2b3df8116:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_822693_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c81b01357d311034949d428818a67deb-748f6931b44731137a17f1e355417d91:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_822693_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_822693.tif...
/ [1 files][ 72.4 KiB/ 72.4 KiB]
Operation completed over 1 objects/72.4 KiB.

2020_822693 done: 4797 cells
running 2021_728758

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ccbfb7dcec41daced3839f3e821430b6-c8a390882b3fd439612a8cf0db58bce5:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_728758_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ab786b69bbb887eebdedc040e243f474-1dc3f0dde2294bef54d6bc85aff2894f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_728758_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_728758.tif...
/ [1 files][ 41.2 KiB/ 41.2 KiB]
Operation completed over 1 objects/41.2 KiB.

2021_728758 done: 1 cells
running 2020_819696
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9cac71b2c569e4566e126536c80a0742-cffd2d3b88cef08cfb26778d81c20c6c:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_819696_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c9a284a84d62e49f4d513d647bc04e55-24093f9f53dac8444bd63c5f8ee6722f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_819696_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/62d34bec3e28c7cc85ef8bbc690dcd05-4cfc74755e19497889e2dea6f50ffc2f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_819696_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_819696.tif...
/ [1 files][ 70.4 KiB/ 70.4 KiB]
Operation completed over 1 objects/70.4 KiB.

2020_819696 done: 94 cells
running 2021_743604

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/37cb61203d61e47ff1ee9fa7062a27b0-705af8a733d98f2aaa0ec8e0a51fff41:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_743604_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/20ef1d469791e158682d08756f04755a-a3f4ce518c486ffdbc090aac4a8b52f3:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_743604_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_743604.tif...
/ [1 files][ 57.2 KiB/ 57.2 KiB]
Operation completed over 1 objects/57.2 KiB.

2021_743604 done: 6 cells
running 2021_729445

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e73cc1fc29cf9bc0daa053f8aeb64579-e0f586f0a428a80516d3065f8f37c7f8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_729445_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/39a95882540c2ea40a43b8eb36482efa-6dc388c4abce20ace3f37585d7a55437:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_729445_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_729445.tif...
/ [1 files][ 41.9 KiB/ 41.9 KiB]
Operation completed over 1 objects/41.9 KiB.

2021_729445 done: 0 cells
running 2021_728617

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/a51645c0c569434917284e43c0a2c844-97028f3482fdc27d308aa0d145e7f29e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_728617_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c71e68dbfbdd70fb2619cd7320ba0a1b-bb164a9cf8d0090e79ed55c6414027a8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_728617_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_728617.tif...
/ [1 files][ 35.3 KiB/ 35.3 KiB]
Operation completed over 1 objects/35.3 KiB.

2021_728617 done: 64 cells
running 2020_13394
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/af942571f5a3b6e6dd4989fe6fad2171-5d3f5dd60cd5523930e6f4f3e220fde6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_13394_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c66f196c67ae0e7488f88f0b23de593d-b915347c16aace70ace32ac4bfd3a6e2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_13394_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/429835ad17ce8c84026b865e22b18fa7-04f0b5dd59e508e5bff5e3e547fc8750:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_13394_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_13394.tif...
/ [1 files][ 38.0 KiB/ 38.0 KiB]
Operation completed over 1 objects/38.0 KiB.

2020_13394 done: 354 cells
running 2020_10835
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/95ac3ea045c496e552287ae47de1f71e-7d01e4604974a873616bee7f0a2e7ae9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10835_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/95f56505d55380e189c269fb8c010e21-6a1afb55cdef2329af53de7928e1874f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10835_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6589683587fdc373d70de6f6b79c21c7-1d7c85bbaa05118cffa51dcad9fb6ffa:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10835_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_10835.tif...
/ [1 files][ 34.4 KiB/ 34.4 KiB]
Operation completed over 1 objects/34.4 KiB.

2020_10835 done: 395 cells
running 2021_4864

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ba94dbe7f8807df7798b5675d93c0e94-e1cd39e7a7e3a71b1e94e2fcf8d913cf:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_4864_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c02adff7cea1edac32b1f76783127504-d2a31815cf17cf6864c603eba1f2c217:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_4864_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_4864.tif...
/ [1 files][ 46.0 KiB/ 46.0 KiB]
Operation completed over 1 objects/46.0 KiB.

2021_4864 done: 140 cells
running 2020_9374
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0a5cd19e86f835bb3a9b10067c3e3d4f-91e9948e2de200a8bde23fac9de3f53e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_9374_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/78707275eabbd0257bf65679b6dee26c-82be73888db10123642eef8a3430c07c:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_9374_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/dad78d311d1f52e0fe9138fbdb28be36-3ed903332f5f19b3200306bfd94965dd:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_9374_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_9374.tif...
/ [1 files][ 36.0 KiB/ 36.0 KiB]
Operation completed over 1 objects/36.0 KiB.

2020_9374 done: 101 cells
running 2020_11894
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c2746d4ab88a87202834ec8b7d277c44-fee6a947552e167a59c3133d7b3fb837:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_11894_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2e4e7c6d75876bacc02a70b6415b17a3-69537247471ffa4c5efe9ca3647ded80:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_11894_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/4d12d00ecc88cb6c789edabab1afa640-03df935f2e53a2085b73836152159b26:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_11894_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_11894.tif...
/ [1 files][ 37.3 KiB/ 37.3 KiB]
Operation completed over 1 objects/37.3 KiB.

2020_11894 done: 53 cells
running 2020_10834
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2d030853656eda6862fcac97d55d2466-f3dc972ad314c39da6f91f5e0d86d1e2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10834_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b94ea7b75d97da06e86ef8de26f89058-929fc56cb6ce709e218e57d2ccb969b8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10834_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/eff7f22469ca05364100a51b2304ca5c-a2fbd06333dad9aa4ddfaf8c7977f874:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10834_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_10834.tif...
/ [1 files][ 32.9 KiB/ 32.9 KiB]
Operation completed over 1 objects/32.9 KiB.

2020_10834 done: 212 cells
running 2020_10779
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/158737bf3f8e9aee1e46fb4902b682ef-28c3bcfd32c9f550126c25e43aa5b9dd:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10779_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8eba32bed788481e66f46aec496a63e4-e6c844945f97b47012fdc9a763dcb3db:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10779_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/157cb9196a017226dd1af6ef3ec6ee2a-1109c210add9095f68248ce894bc0256:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_10779_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_10779.tif...
/ [1 files][ 29.7 KiB/ 29.7 KiB]
Operation completed over 1 objects/29.7 KiB.

2020_10779 done: 346 cells
running 2020_11971
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f17a3c09aad87e633a1fe384d7be7fa0-8a4580f50a214e1e040e2da0439b95b1:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_11971_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/199d072bbb08547f45206f0323dda12f-a4aa27eb254269c3bab1778132a81d1c:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_11971_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d8419b38da6bb53bf85549ef82c8ad97-509a19f3b7618e37d11f766d28798a89:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_11971_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_11971.tif...
/ [1 files][ 38.2 KiB/ 38.2 KiB]
Operation completed over 1 objects/38.2 KiB.

2020_11971 done: 6 cells
running 2020_9438
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/3ea8a7fa9cb8522b7f158852b231875a-036b47f2257d5a12bdcaed96a8303692:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_9438_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7de71894feacfabf2ed29eb9570e4061-776bb7f3d2d36ee61c7966090bb1150d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_9438_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/cbd870b1e566704f1342b1dfdf28ed61-84b2f00a10692ac0f0049ffe0c6883a8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_9438_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_9438.tif...
/ [1 files][ 61.4 KiB/ 61.4 KiB]
Operation completed over 1 objects/61.4 KiB.

2020_9438 done: 779 cells
running 2021_3892

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0be3a00ab238e0e92227d0df58bbf293-39f59c53c968bb7b117828d0527600c4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_3892_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/424d3948dc1f070f1cf797f629a2607c-8579033982703c0b5a7f1cfbad315232:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_3892_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_3892.tif...
/ [1 files][ 55.2 KiB/ 55.2 KiB]
Operation completed over 1 objects/55.2 KiB.

2021_3892 done: 519 cells
running 2020_71239
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/5037f58d2dbe3894c50ccf0d916d23fa-309f22e003cf1c9a71399f3ce8dcc694:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_71239_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/a8f2727228166dcf6e1a4d4fda11eaef-62a97d5ffb2fc40e50230d680a3cdf39:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_71239_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/a59e33ebf8f14cb20cf0f1aa71adb0d9-3781ccc4b9e9cb87df27989311f28890:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_71239_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_71239.tif...
/ [1 files][ 27.6 KiB/ 27.6 KiB]
Operation completed over 1 objects/27.6 KiB.

2020_71239 done: 474 cells
running 2020_67755
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1a3aa749f480be8dd47bbe70d3728f6e-c409b788c2f647bdae857cd5b85cde1b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_67755_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/73b5dc27b750e1b14e33dc7ff6dfdec0-1f61d2d69fce56a43697adf055088f1e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_67755_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/631a063dd8b9c11b4f097b3eebe33c73-f10cf686257a790d0d5bf607f5f02623:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_67755_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_67755.tif...
/ [1 files][ 12.8 KiB/ 12.8 KiB]
Operation completed over 1 objects/12.8 KiB.

2020_67755 done: 331 cells
running 2020_137781
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8917c4c050eb744a2c2a6af02d472403-5e3198d92681fabeec8c21b704da65bd:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_137781_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b45354bce14538e6e9b0dd2a2dab3dbf-0b10f9a68e0cba995ee3d53a76d9f9d1:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_137781_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/31769c618063dacbd22ef140ef19c1a5-bc4da0f23db0fd5c2be58145c7f8ee0b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_137781_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_137781.tif...
/ [1 files][ 41.5 KiB/ 41.5 KiB]
Operation completed over 1 objects/41.5 KiB.

2020_137781 done: 1254 cells
running 2020_65057
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/854a76075cc1cea39c2ed834dc1bbf0e-980e5f126243acb94123f6fbc84c3eae:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_65057_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7d7d0c32fa70fec0aaf3fe4d15c7b9ff-cbda651d3e63aafcfd051c026f3b4889:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_65057_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/bc5c83de6015955476addbaa58025e4a-9472090339911aacebeb491ace72cc37:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_65057_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_65057.tif...
/ [1 files][ 30.9 KiB/ 30.9 KiB]
Operation completed over 1 objects/30.9 KiB.

2020_65057 done: 915 cells
running 2020_70720
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2fba38db55883e1ab68a81984045635c-63a95702bb7ec0b37291a29d0b326caf:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_70720_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f0f76e4fe48bbfed75c6e2c17d9c0210-68e5dfa8c0b73e64ace03f5e28784fe1:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_70720_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/a8b6d23e4acdc7b77dbe36eb46fb412d-fb911e94bd8f52872bde7469018028f7:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_70720_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_70720.tif...
/ [1 files][ 32.2 KiB/ 32.2 KiB]
Operation completed over 1 objects/32.2 KiB.

2020_70720 done: 3297 cells
running 2021_51822

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9c4af813e1e727816d043ec1a04e5dd9-93c8db2ba5db34fbddf1ef516b050d47:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_51822_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/288575044e6bc170a5e73800b2f653f6-5750b0eb727d5002bbdc1ed28f7c64d9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_51822_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_51822.tif...
/ [1 files][ 26.7 KiB/ 26.7 KiB]
Operation completed over 1 objects/26.7 KiB.

2021_51822 done: 105 cells
running 2021_41614

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/af5a5ca0713a976f13ef6530762b9d93-4591d35e9be37a0d831f431ac7c4a216:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_41614_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/00f17d542fb97875f35085e3905727ff-0dc2d5d95e76c9a3e43fb3d978b1446e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_41614_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_41614.tif...
/ [1 files][ 18.0 KiB/ 18.0 KiB]
Operation completed over 1 objects/18.0 KiB.

2021_41614 done: 998 cells
running 2020_66839
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/907bb99d6d71ae53855dedd0a1dceab8-df6cb8aa3aa5a5811062830514189c81:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_66839_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e669761002b5b6bc82aeb64a8dab5a41-a511fc08f1638fd8b77b2562c85198e6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_66839_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/17a4240c46c866fdb6ac3b9cd4179596-81429e872796ae0e20bef109eb02f0e9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_66839_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_66839.tif...
/ [1 files][ 32.9 KiB/ 32.9 KiB]
Operation completed over 1 objects/32.9 KiB.

2020_66839 done: 64 cells
running 2021_105869

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/33ca089f8e96e109364af1b706032fa4-b6b7f3729f2397e716e6dfd6f51fe9f6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_105869_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7be5954124b7bfe70039291bcde72d23-7e8ac0bd458a1f9a7633e8b95b81041a:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_105869_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_105869.tif...
/ [1 files][ 51.8 KiB/ 51.8 KiB]
Operation completed over 1 objects/51.8 KiB.

2021_105869 done: 687 cells
running 2021_48631

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8f943fa844a46d3f70a77cde171b620f-f802f7b4d7f7ffd4b04f12e7dd3a43ac:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_48631_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d743e414068788e91ab0930c963eb8ca-b9e4561d7d227c1de54d85a62d8a1c4f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_48631_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_48631.tif...
/ [1 files][ 27.0 KiB/ 27.0 KiB]
Operation completed over 1 objects/27.0 KiB.

2021_48631 done: 395 cells
running 2019_268326
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6351ff4a9692c3de6061f8cfe33fc70e-809e4ecc8210abb009c5c60081e5a214:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_268326_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b9c432b286fdce11f6bb4e639e24dc03-7fdeec29acef7d15e35b053fccd6118b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_268326_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/87ba025f02addc06e6d0696e44f9fd00-f66a9cd3297b983e9a088af3e2a07cad:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_268326_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_268326.tif...
/ [1 files][ 57.2 KiB/ 57.2 KiB]
Operation completed over 1 objects/57.2 KiB.

2019_268326 done: 0 cells
running 2019_193597
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/098a6851f9f468c6f84f3f38df837378-7d6231098e46ec0253f9ee76586500ae:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_193597_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/41bfcfe1abc72fbbca1570e4c01128a1-f5b0d23ad658b1e36bccf02709e07629:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_193597_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/20e0964cbbe9412722644bbd26788f77-969ec5fcdc34d5b5247c42275b985e1c:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_193597_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_193597.tif...
/ [1 files][ 83.8 KiB/ 83.8 KiB]
Operation completed over 1 objects/83.8 KiB.

2019_193597 done: 35 cells
running 2020_232665
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0369aa59365c04d6056f4880fdf4635e-3d7a4692f75b1fb69ab2cf13201a2456:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_232665_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c0a7a433d79d67101a6dd8876965df37-9f6e25b0d66eff5e0dbec0407a65eae9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_232665_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/78642a2d7ee950774c861276efc595d2-eff4126a7c11f2c60e71ad2d1c62b2ab:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_232665_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_232665.tif...
/ [1 files][ 67.4 KiB/ 67.4 KiB]
Operation completed over 1 objects/67.4 KiB.

2020_232665 done: 773 cells
running 2019_441028
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/648ce66f229faf0ac2d081dcc701b4ef-cf3d8ef28e7e171262a2d2a8e1cf91a1:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_441028_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f0acf02d157e3e7cd4d7425f7546a39b-fbd89897f7c7e94040a8cd71e09b6b20:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_441028_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ed943aa99ce13d87280cbe7ed7de02c9-83f2689d7f257aef3cbce24b6b68f801:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_441028_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_441028.tif...
/ [1 files][ 12.8 KiB/ 12.8 KiB]
Operation completed over 1 objects/12.8 KiB.

2019_441028 done: 282 cells
running 2020_449973
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/33f9f64b177dc398e85f8568baa546d1-db5d7e2125eb76b2f284d3e5ad4c5524:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_449973_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e5233179b0a869cca7b2079cd022c5f0-c9be68acd846c9d329b068f558d004f2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_449973_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_449973.tif...
/ [1 files][ 24.4 KiB/ 24.4 KiB]
Operation completed over 1 objects/24.4 KiB.

2020_449973 done: 68 cells
running 2019_193861
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c6d7137ea117b9be515fad9c8ad9c98f-67b7026e2e393fc6734461773848c0ce:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_193861_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b0e0097eba9dee40ccee14574e78b1de-7d2853fd30ca46bc722a22f3bd26b0cd:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_193861_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6db8fed03ab4886311a5cdb3f3740ec7-90b8cab05af79e6c3c8a3bd69bf75879:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_193861_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_193861.tif...
/ [1 files][ 58.2 KiB/ 58.2 KiB]
Operation completed over 1 objects/58.2 KiB.

2019_193861 done: 20 cells
running 2019_442931
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6c2a2914de411d62c66e3aad824ffc40-17d5808794830e578f7af08497d92f7e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_442931_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/a67396d69a86cb1d88c46899ff6f844e-601d75c33f4293441d9acd7e6b86b136:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_442931_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/a4afcbd238043bf9497e5e57a0b23562-30b247570696d6d0e2858045941657cf:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_442931_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_442931.tif...
/ [1 files][ 19.7 KiB/ 19.7 KiB]
Operation completed over 1 objects/19.7 KiB.

2019_442931 done: 190 cells
running 2019_441257
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6d2be22314bcae51ba5b226ece282ec5-8a76d95797866fba5ccaa942d73aa42c:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_441257_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0c9e95dbec949721c41f39c062385278-36f748fba5587ef36311fe11f746c63d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_441257_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/14f75ea6bb63e02ae98a06d7731ac4aa-d268172105e218dedf71dd20ab5f32a3:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_441257_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_441257.tif...
/ [1 files][ 12.4 KiB/ 12.4 KiB]
Operation completed over 1 objects/12.4 KiB.

2019_441257 done: 623 cells
running 2020_460400
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/3c420edf7e0831b76f7ec088432e2050-3ef438b8d36b6d008df88c943305f4e6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_460400_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e6a864892181e4bc780a7fe73629aa17-53764053c21213522896f65c0002c0e0:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_460400_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_460400.tif...
/ [1 files][ 27.0 KiB/ 27.0 KiB]
Operation completed over 1 objects/27.0 KiB.

2020_460400 done: 365 cells
running 2019_195000
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/08472257c2069b192152ffa6c292d9b4-56b3fb68f1096d4b242cb7b36938b807:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_195000_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ecc06a287c25e04c392b0652dc96b4ca-a0a6fb1871a33f77b50ad2820bda1f4e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_195000_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9990736cd5047ae89fa6be7f2c6a5b1b-b5c0d3353041ee3edc2c0d46e55c98f4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_195000_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_195000.tif...
/ [1 files][ 71.4 KiB/ 71.4 KiB]
Operation completed over 1 objects/71.4 KiB.

2019_195000 done: 314 cells
running 2021_271176

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/450718b4ff306843df0488c05444ba09-ecb5535a0382022fcd79655a412ce767:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_271176_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/81bae2148e90a3c2edcf615e44c9fc6a-9d6a6d9ec7ed6deb6c32f9258dacff3a:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_271176_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_271176.tif...
/ [1 files][ 39.8 KiB/ 39.8 KiB]
Operation completed over 1 objects/39.8 KiB.

2021_271176 done: 2 cells
running 2020_325873
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0a430ce225559a8655b0e2ad76cf34d7-65b5c0247ca2821cf2621d74ce276bc9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_325873_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/879f4b19fc1bafe7e465dd98d5a75d8d-bcecdb2889cacbd8f02504bee7779fc6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_325873_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e64bbd6b3b8297b5df8d9e8a46594875-5377d9dedc97eb18ce7dffcd054cafee:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_325873_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_325873.tif...
/ [1 files][ 52.7 KiB/ 52.7 KiB]
Operation completed over 1 objects/52.7 KiB.

2020_325873 done: 0 cells
running 2020_354548
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c9d1ad91f632e2e1e47a40add26246fa-0ffdd7102008a086ba1daccca4a7886b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_354548_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/42ccf3d76c971c51899e153c9ecaafbc-e0ab59c039d7f55d266ffec84d45351e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_354548_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/3c28eaa25f53779838a49a2122687285-1a87ee6d651c197447c677fd1fca96f8:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_354548_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_354548.tif...
/ [1 files][ 37.6 KiB/ 37.6 KiB]
Operation completed over 1 objects/37.6 KiB.

2020_354548 done: 0 cells
running 2020_358152
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/fea0a40dd2dd04d384fb7e4bd91e842d-e0e7acb0556731a4d69a83e9f1b18f33:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_358152_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/518c7ff9222b282f3e38ba24770d17ce-ef8bc752b89011aba0066edbf1739cd2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_358152_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/31ff2e9aa1607581644beea6b35c056a-b53b9e149e7b1839efab5912c72b9fb7:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_358152_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_358152.tif...
/ [1 files][ 32.1 KiB/ 32.1 KiB]
Operation completed over 1 objects/32.1 KiB.

2020_358152 done: 0 cells
running 2021_603286

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7b778901c581548e24abb23e702066a6-f8c394571a23d2480942e8bd6a9103c6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_603286_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1bfcc052660d071928f7ea7c8276a556-28e6ce8b945b5052424b573fbb861575:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_603286_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_603286.tif...
/ [1 files][ 57.8 KiB/ 57.8 KiB]
Operation completed over 1 objects/57.8 KiB.

2021_603286 done: 130 cells
running 2020_333817
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/b44e49a72a0d39dac4963a200a4840f9-c530ac430cf6b67e3a0d09c730f885a3:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_333817_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e7a8d2e50fad5556261c0afb13eb49e1-49ae733b05bba1925143a9ad4a86a773:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_333817_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/db67c2ea1883149558969c05070c006e-a5e5d0b3306f4b4038834fdac2db44e4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_333817_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_333817.tif...
/ [1 files][ 38.5 KiB/ 38.5 KiB]
Operation completed over 1 objects/38.5 KiB.

2020_333817 done: 0 cells
running 2020_302951
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f1a6e3416c2ff17cc6ec46b3400b0ae9-1be2813f42afb2283f69a108825c5c66:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_302951_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6f47b7abe85786e0738a027073a4ba7d-046e06af5d78ea0899539ae46b9fad6f:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_302951_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/28d90f2595caae0f47c5db3522c4daa2-5f7614e246ca169d28db72c7a4408298:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_302951_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_302951.tif...
/ [1 files][ 27.9 KiB/ 27.9 KiB]
Operation completed over 1 objects/27.9 KiB.

2020_302951 done: 34 cells
running 2021_284193

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/34f39b6fd3b9380c18a65a9fefbf2419-9ad2971fac5d599edf131e738c3f8491:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_284193_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/4439a57424d18086b5d139b7a266aebc-aae8d5f1210aef0aeec2dda7e390e868:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_284193_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_284193.tif...
/ [1 files][ 38.5 KiB/ 38.5 KiB]
Operation completed over 1 objects/38.5 KiB.

2021_284193 done: 0 cells
running 2020_467919
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f60584ad6374051e68f86ee928a97c51-5cbcc014adc7685d7dc9cfd7667cfec6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_467919_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ec650e6493e75c989bbedc1bdf101a24-f907d94928f24f145c4122f6257aae47:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_467919_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/5b7f848d4d42dd7a5e3d940a197852fc-b1fd40e9fcb26549ed4891abb84cfb3d:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_467919_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_467919.tif...
/ [1 files][ 25.9 KiB/ 25.9 KiB]
Operation completed over 1 objects/25.9 KiB.

2020_467919 done: 11 cells
running 2021_401856

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7c7f6afc5fb5d5976d4c885b5d71b9aa-ca9b775fcdbaff886e21aec9b259c61e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_401856_2020.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8409ae08f3bfa14ee5c52ed0abc64137-c65711b6f5583382b4c644030b570ee4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_401856_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_401856.tif...
/ [1 files][ 29.8 KiB/ 29.8 KiB]
Operation completed over 1 objects/29.8 KiB.

2021_401856 done: 39 cells
running 2020_871140
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9e3a8848878883794bc5220515aad244-9bf9e1f9f0fd3bc107696c02d9a1db05:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_871140_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ddd0d424abf40c31fee67d6bf22542df-ffc82e71932c4edb312a1ea13c2a2508:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_871140_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1cfc6f9bd2e9efe1066914194db3abe7-dd9e5f94ffac8ed7a401e530aa79480a:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_871140_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_871140.tif...
/ [1 files][ 29.5 KiB/ 29.5 KiB]
Operation completed over 1 objects/29.5 KiB.

2020_871140 done: 4 cells
running 2020_858340
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2533502a2c589e9c88356b9d4e5ea3f2-c3ecbd758b80c5fec9e779bb70811fc3:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_858340_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0e4467937e5db7349f5467fb3ad64d11-dd5e12b3ea241f92bf69ff52701c52ae:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_858340_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/fec2f3bc65a2686bb64ae85825458724-7919377a267cb898e721764b6512c723:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_858340_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_858340.tif...
/ [1 files][ 27.7 KiB/ 27.7 KiB]
Operation completed over 1 objects/27.7 KiB.

2020_858340 done: 79 cells
running 2020_834756
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/a7e2ce181229d5d8afa05a9418a73402-1e8056a6ea94804b6b82026b0062c218:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_834756_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/594de349a7c2789b09f33d1f4f4019c8-c0dd17079e04c46e780d34c7afeabb10:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_834756_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f0d0f058905d396d62331040b0204bd6-6386427026e6252cf733685f5a8c9d5e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_834756_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_834756.tif...
/ [1 files][ 29.7 KiB/ 29.7 KiB]
Operation completed over 1 objects/29.7 KiB.

2020_834756 done: 85 cells
running 2020_858341
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e5056447d4e104bcd7e0285352048844-f649e1affd7ac526fc1de1f198c0275b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_858341_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1afe820bd9bc2ba8f6ef05e5dac4f4ba-354b067bd5b92b2847b5969a44c8ebf5:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_858341_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8980a61805c71034c0d11336973e2bda-9fe419ca9f6882006daea1967f3e00ec:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_858341_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_858341.tif...
/ [1 files][ 21.0 KiB/ 21.0 KiB]
Operation completed over 1 objects/21.0 KiB.

2020_858341 done: 2 cells
running 2020_830179
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f73edb30c3dc1811f7571c3ab52d81c3-31c7bf06c3bf8896a2cbcb213b930139:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_830179_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0b76145f01318d6142b0a693a83b0dc9-1bffc6bd8cce1d620512ce332a86840e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_830179_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8729a2314416694844b2fbb8c6862aaa-8e92dbcedd4470dc123df4de9f8ce5d1:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_830179_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_830179.tif...
/ [1 files][ 28.6 KiB/ 28.6 KiB]
Operation completed over 1 objects/28.6 KiB.

2020_830179 done: 176 cells
running 2020_839832
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d02fc7fac48a53668820f997495016ec-d015efd99d953f0ad32aa001d2c39331:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_839832_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d18935014614c969c3e9446becbf2841-61a025830ee27ec93be7d3c466162508:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_839832_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/fd8e199d5ddc112c2f4bb444f910fb39-ea551a5d89c59c3945f50727d7f92ecc:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_839832_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_839832.tif...
/ [1 files][ 36.3 KiB/ 36.3 KiB]
Operation completed over 1 objects/36.3 KiB.

2020_839832 done: 547 cells
running 2020_832636
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/563fe6b8c3ab2ea51613d898464ef70b-8e243a0184a26b9335ab727e8378b264:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_832636_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1b58acc43de202fef2075c28860eacb1-37df16f932269ba5b58cbece84438918:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_832636_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d07842cf59c763b1f17386f76bc1e1b4-7534a1667d3cdd1aa5640a9778e33d4c:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_832636_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_832636.tif...
/ [1 files][ 37.4 KiB/ 37.4 KiB]
Operation completed over 1 objects/37.4 KiB.

2020_832636 done: 356 cells
running 2020_833726
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/7c3b4a91fd988005136560a0b162141a-db1500f2d111cc1e216ddefaaf1c5795:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_833726_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/916450f484c204f22c71069f7a29083a-da02468e3306130725792b1ec47fa4f4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_833726_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1df7460745cec30bedc0c474f534b7e7-a301c04ea99e702a56d2a5c46c8273e4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_833726_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_833726.tif...
/ [1 files][ 42.5 KiB/ 42.5 KiB]
Operation completed over 1 objects/42.5 KiB.

2020_833726 done: 428 cells
running 2020_831248
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c5983824a899a7cca76d73c9106707d8-7e86f1552f5c28965c86d581c9c5875b:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_831248_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/6b729d3967abd2a59e7dec42c88399c1-e482a3cc506970309ca8b4488952d371:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_831248_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f1c98295b1443f63de16b9745c2b0de1-147f0fc0e39c64895f995c208df15f29:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_831248_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_831248.tif...
/ [1 files][ 29.4 KiB/ 29.4 KiB]
Operation completed over 1 objects/29.4 KiB.

2020_831248 done: 71 cells
running 2020_857759
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/a3ec4922492cf08beb6e914c60a6b9ea-41d2af3de262c98430b2a097621fa7ff:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_857759_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/dea583566c767a7f471cb12f94a64d57-a6b7c0dea950065aff55988436544ab6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_857759_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/444b40ea148bb187d0986de29a3092f1-e46f133569b484bd588e342c38f0d804:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_857759_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_857759.tif...
/ [1 files][ 19.1 KiB/ 19.1 KiB]
Operation completed over 1 objects/19.1 KiB.

2020_857759 done: 0 cells
running 2020_880556
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/5f6d0fa0fa5cfc94524a66cb8c3f61fb-777f1b2e5fbeb1680c1ef6e2d9d50d06:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880556_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/cd4df13ab58ae5bde233f5bc4a971352-9cc4f616062a9dfdcddb02c0765f3d4c:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880556_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/60d361ce1e52bcdcbb40c7c7451c69dd-4fa58fd01407415c829663389537f8c6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880556_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_880556.tif...
/ [1 files][ 49.5 KiB/ 49.5 KiB]
Operation completed over 1 objects/49.5 KiB.

2020_880556 done: 9654 cells
running 2019_873717
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/fd91c84253fd7dd34572b6a767330879-09522e03e10ea878cba812bf5c9d01e4:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873717_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9d30cf1b1cf76fd0ad3dafaa48469dd6-868489b719c405d8755baa2a309dc683:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873717_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/8f16259e4cbf2d5f6dfecdb8593ad308-1e3d078c4b6e4405e2e7cd8a91f636b2:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873717_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_873717.tif...
/ [1 files][ 20.3 KiB/ 20.3 KiB]
Operation completed over 1 objects/20.3 KiB.

2019_873717 done: 654 cells
running 2021_766525

/home/jupyter/fire-impact-curves/.venv/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: ../data/fire_atlas/SHP_perimeters/GFA_v20240409_perimeters_2021.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/0a887482fb31c3234266b8d6e54fd556-7343e393502546f11b5348a414b29b66:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_766525_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e4a3b958fd9e5dbd2aae0020cdaec565-a1917e4a52ebb297412814e9978b4c2e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_766525_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/3379650dcaa0611e8350aa533d91b5f9-8308478ab2889206fd2f63edfcc27ed1:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2021_766525_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2021_766525.tif...
/ [1 files][ 25.2 KiB/ 25.2 KiB]
Operation completed over 1 objects/25.2 KiB.

2021_766525 done: 90 cells
running 2019_873471
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9e705e70a73a207c4d5013bd7bdaeb90-d4018f1d5136795c7a5b55c541b92075:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873471_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/36391eb4b667c8201c84530820914d88-a728e0007e5a41588695687987abba94:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873471_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/435cc696bf88bbadbc65b1abd4a313bb-8693ec763c66c548e0620cd9015fb3d1:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873471_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_873471.tif...
/ [1 files][ 25.9 KiB/ 25.9 KiB]
Operation completed over 1 objects/25.9 KiB.

2019_873471 done: 1685 cells
running 2020_880548
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/38a871760d94f23a08000c923e73370b-2eb891d5507faa4109d549226dced245:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880548_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/acb98c66710203a34954a2d8c16efb75-0b58e81e0fe8de8e92f916897eaba099:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880548_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/77b9ebe22bc97af14953c90d4fa75c22-1cf27f6e0229868609e258ceef967003:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880548_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_880548.tif...
/ [1 files][ 48.5 KiB/ 48.5 KiB]
Operation completed over 1 objects/48.5 KiB.

2020_880548 done: 29057 cells
running 2019_873714
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/643a069946d96a722e59a2a7fe4e5710-970634192ff3fbd6806b8de7c1a16de9:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873714_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1166213f2203e324f2d797b4707b8f23-f74a842a5f613f307aeee2f5ed3bc451:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873714_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/d963efb822e40f0f6d7247ff37fdd4df-27aed5c8199e2fdf07afbf60f4df17b3:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873714_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_873714.tif...
/ [1 files][ 28.1 KiB/ 28.1 KiB]
Operation completed over 1 objects/28.1 KiB.

2019_873714 done: 1315 cells
running 2019_873720
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/f4ae99271a4d76f2fdf64d08eed954ae-e2622ac65ea47e046e7e772f6b28a9f5:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873720_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/2c16edc12445159773a4acebd946a7dc-6b66c9e7ea15b992922db853076b5990:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873720_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/5c17864064accb5c86a6d8191938e47c-c2c0909a49540185e501219e75c5b2da:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873720_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_873720.tif...
/ [1 files][ 22.9 KiB/ 22.9 KiB]
Operation completed over 1 objects/22.9 KiB.

2019_873720 done: 405 cells
running 2019_873593
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/c3a75b9be691a04ff387e03b90bf60e2-86eacc4b43a4490202349e4c080aa5bf:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873593_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/155c90ae1aac3ec836f7b040c77c97de-0f7f729393627dbc2f18dc801b42c228:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873593_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/9a7cb78fbc0f26f1976743b3b232d4a8-16fc74ad6a38635f3e66b191a44c70bb:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2019_873593_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2019_873593.tif...
/ [1 files][ 38.6 KiB/ 38.6 KiB]
Operation completed over 1 objects/38.6 KiB.

2019_873593 done: 477 cells
running 2020_877292
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/ad2320723d309bc9615ab9899857ffb3-6280f58782fb52fe279614695b33c9be:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_877292_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/bc5a25c7f1dffe6dc4b321f572b08476-e8b63a1ab03927a4e8559d8ab6db9ac6:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_877292_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/1d7438ca47d0187c7dad6ff68ab19f41-1ccdac0140f51b7e6b32a775a915f029:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_877292_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_877292.tif...
/ [1 files][ 30.9 KiB/ 30.9 KiB]
Operation completed over 1 objects/30.9 KiB.

2020_877292 done: 289 cells
running 2020_880433
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/4d3b1cbb16130c830f2b40d0229e65d8-88f84bc2ffa5681fb90eca13997ccc34:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880433_2019.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/380e9c9465676ef91f364c1eba5e6d75-8f9671044d39b13466817ec335a8319e:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880433_2021.tif
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/tree-fire-510209/thumbnails/e7ce7cfd5d523405186a161bbac5bd6e-20e539ef1cf91e3b5d6c913e7bc035ed:getPixels
Please wait ...
Data downloaded to /home/jupyter/fire-impact-curves/data/cci_agb_ee/agb_2020_880433_2022.tif

Copying gs://tree-fire-510209-data/fire-impact-curves/data/forest_type/landcover_2020_880433.tif...
/ [1 files][ 40.7 KiB/ 40.7 KiB]
Operation completed over 1 objects/40.7 KiB.

2020_880433 done: 4384 cells
full: 507169 cells -> new_full: 592048 cells (111 new fires)

In [46]:
print(f"{len(full)} cells in full")
print(f"{len(new_full)} cells in new_full")
print(f"{len(topup2_results)} of {len(topup2_configs)} new fires succeeded")

missing = [cfg["uid"] for cfg in topup2_configs if cfg["uid"] not in topup2_results]
print(f"{len(missing)} failed/missing:", missing)

507169 cells in full
592048 cells in new_full
111 of 113 new fires succeeded
2 failed/missing: ['2020_86085', '2020_77169']

In [50]:
full = new_full
print(len(full), "cells now in full")

592048 cells now in full

In [56]:
print(full["height_class"].isna().sum())
print(full["height_class"].value_counts(dropna=False))

85946
height_class
10-20m    218540
>20m      201515
<10m       86047
NaN        85946
Name: count, dtype: int64

In [57]:
full["height_class"] = pd.cut(full["height"], [0, 10, 20, 100], labels=["<10m", "10-20m", ">20m"])
print(full["height_class"].isna().sum())

2629

In [58]:
import importlib, src.curves
importlib.reload(src.curves)
from src.curves import fit_all_groups, bootstrap_curve_band, logistic, per_fire_severity_means

fit_table = fit_all_groups(full)
print(fit_table)

                                        status     l_max          k        x0  \
<10m   deciduous_broadleaf              fitted  0.158763  18.495918  0.296037
       deciduous_needleleaf  insufficient_data       NaN        NaN       NaN
       evergreen_broadleaf              fitted  0.470637  10.248645  0.302133
       evergreen_needleleaf     degenerate_fit  0.001085  25.498799  1.991538
       mixed                    degenerate_fit  0.305551       50.0  0.772501
10-20m deciduous_broadleaf              fitted  0.201581  41.062436  0.264482
       deciduous_needleleaf     degenerate_fit    0.1633  16.366795  1.689707
       evergreen_broadleaf              fitted  0.313728   6.181493   0.51356
       evergreen_needleleaf             fitted  0.170938  20.785748  0.521445
       mixed                            fitted  0.155505  13.923409  0.722965
>20m   deciduous_broadleaf      degenerate_fit  0.046382  14.792658  1.831468
       deciduous_needleleaf  insufficient_data       NaN        NaN       NaN
       evergreen_broadleaf      degenerate_fit  0.152915  29.294306   1.36638
       evergreen_needleleaf             fitted  0.395952  13.900746  0.553664
       mixed                            fitted  0.182942  31.900488  0.202727

                                                                 param_std_err  \
<10m   deciduous_broadleaf   [0.03246788111781721, 7.945690431619213, 0.039...
       deciduous_needleleaf                                                NaN
       evergreen_broadleaf   [0.019305751276890323, 0.6800895270943993, 0.0...
       evergreen_needleleaf  [16201052.254997583, 14179092374.021143, 10711...
       mixed                 [0.1243914817169417, 53.42631999610187, 0.0322...
10-20m deciduous_broadleaf   [0.02007680528299016, 13.88682269783681, 0.012...
       deciduous_needleleaf  [16811415.5075291, 115500299.41801153, 9276454...
       evergreen_broadleaf   [0.02650263616221628, 0.47799610664986225, 0.0...
       evergreen_needleleaf  [0.004193868604570109, 2.2707634511580297, 0.0...
       mixed                 [0.02480902099941676, 3.602240401537015, 0.033...
>20m   deciduous_broadleaf   [31406493.17543168, 1021743147.5567564, 913652...
       deciduous_needleleaf                                                NaN
       evergreen_broadleaf   [3726711.484830095, 484501.6360045889, 833020....
       evergreen_needleleaf  [0.002469647573829727, 0.4949861615493144, 0.0...
       mixed                 [0.026059580107488056, 19.864024517216823, 0.0...

                            n_fires n_cells
<10m   deciduous_broadleaf       86    3924
       deciduous_needleleaf       3     118
       evergreen_broadleaf      128   19674
       evergreen_needleleaf      34   22846
       mixed                     25    2383
10-20m deciduous_broadleaf      102    8014
       deciduous_needleleaf       4    1515
       evergreen_broadleaf      145   72625
       evergreen_needleleaf      40  122250
       mixed                     35   10214
>20m   deciduous_broadleaf       17     352
       deciduous_needleleaf       2     119
       evergreen_broadleaf       93   76745
       evergreen_needleleaf      33  167826
       mixed                     24     842

In [59]:
import importlib, src.curves
importlib.reload(src.curves)
from src.curves import cross_validate_all_groups

cv_summary = cross_validate_all_groups(full)
cv_summary

   height_class           forest_type  n_folds       mae      rmse      bias
0          <10m   deciduous_broadleaf      117  0.259769  0.407146  0.084116
1          <10m  deciduous_needleleaf        0       NaN       NaN       NaN
2          <10m   evergreen_broadleaf      209  0.257623  0.362358 -0.030389
3          <10m  evergreen_needleleaf        0       NaN       NaN       NaN
4          <10m                 mixed        6  0.284786  0.312611 -0.284786
5        10-20m   deciduous_broadleaf      140  0.248639  0.319160  0.121691
6        10-20m  deciduous_needleleaf        0       NaN       NaN       NaN
7        10-20m   evergreen_broadleaf      250  0.215715  0.302849  0.069410
8        10-20m  evergreen_needleleaf       98  0.159621  0.222241  0.007627
9        10-20m                 mixed       64  0.156400  0.239757  0.040235
10         >20m   deciduous_broadleaf        0       NaN       NaN       NaN
11         >20m  deciduous_needleleaf        0       NaN       NaN       NaN
12         >20m   evergreen_broadleaf        0       NaN       NaN       NaN
13         >20m  evergreen_needleleaf       86  0.209912  0.329270  0.007005
14         >20m                 mixed       35  0.237264  0.297000  0.030901